### ISSUE TITLE
Remote certificate validation

### ISSUE THREAD

**Issue by scalablecory** [microsoft/msquic#1063]
In .NET we have a callback that allows checking the remote certificate during the TLS handshake. I'd like to see a connection event that we can plug into to do this.

```
bool RemoteCertificateValidationCallback(object sender, X509Certificate? certificate, X509Chain? chain, SslPolicyErrors sslPolicyErrors)
```

If user returns true, accept the cert. If false, reject. Beyond allowing users finer control over validation, we use this often during testing with a blanket `return true` to allow self-signed certs that aren't trusted.

@bartonjs what (CAPI, OpenSSL) structures would we need MsQuic to pass us in order to light this up?

I don't feel that this is P0 for us, but would be very useful. CC @samsp-msft

**Comment by nibanks** [comment]
@scalablecory let's just add all this context to #107, since that's tracking the work to support client certificates in general.

**Comment by bartonjs** [comment]
> @bartonjs what (CAPI, OpenSSL) structures would we need MsQuic to pass us in order to light this up?

For OpenSSL I think it's the whole `SSL*` and/or `SSL_CTX*`.  It's somewhere in the SafeFreeCredentials/SafeDeleteCredentials part of SslStream, I'm having trouble finding it.

> I don't feel that this is P0 for us, but would be very useful. 

I expect it'll be P0/essential-for-ingestion, since the callback is the only way to do cert pinning.

> let's just add all this context to #107, since that's tracking the work to support client certificates in general.

This isn't client certificates, it's the client deciding if it wants to keep talking to the server after an early stage of the handshake.

**Comment by scalablecory** [comment]
> For OpenSSL I think it's the whole `SSL*` and/or `SSL_CTX*`. It's somewhere in the SafeFreeCredentials/SafeDeleteCredentials part of SslStream, I'm having trouble finding it.

To throw a wrench into this -- msquic comes with a private copy of OpenSSL, so the handle used by .NET will probably be incompatible with these handles. Maybe a serialized pfx? Seems like it might be perf-killing to run this for every connection. @bartonjs @wfurt
