### ISSUE TITLE
Support Client Certificates

### ISSUE THREAD

**Issue by Tratcher** [microsoft/msquic#107]
## Client scenarios:
- Single cert: The user specifies one certificate before creating a new connection. That cert is sent (if the server asks for it?).
- Multiple certs: The user provides a list of possible certificates. The implementation selects one from the list that matches the issuers list provided by the server. (Compare to SslStream's [client cert list](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.clientcertificates?view=netcore-3.1#System_Net_Security_SslClientAuthenticationOptions_ClientCertificates)).
  - Once the connection is established the user can call an API to find out which cert was used.
- Dynamic cert: The caller provides a callback that is invoked when the server asks for a certificate. The input is the issuers list (is there any other data available?) and the result is an optional certificate. (Compare to SslStream's [callback](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.localcertificateselectioncallback?view=netcore-3.1)).

If MSQuic provided only the dynamic option then the caller could implement the other two on top.

## Server scenarios:
- Settings can be provided per connection after seeing the SNI, ALPN, and other Client Hello data.
- Client certs can be set to Required, Requested/Optional, or Disabled/Ignored.
- Flags for what types of validation to enable/disable for the client cert.
- A callback that is shown the validation results and can accept or reject the cert and/or connection. Compare to SslStream's [callback](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.remotecertificatevalidationcallback?view=netcore-3.1).
- Once the connection is established the server user can call an API to retrieve the client cert that was negotiated, if any.
- ~~Dynamic renegotiation to retrieve a client cert~~ - Not supported by TLS 1.3.

**Comment by DemiMarie** [comment]
In many cases, choosing a certificate will involve user interaction.  Therefore, it must be asynchronous.  Since client certificates are often on smart cards, signing will also be asynchronous.

**Comment by anrossi** [comment]
For Client scenarios:
 - #1262 and #1243 Add single client certificate support for Schannel. OpenSSL will follow later.
 -  Multiple certs is not in plan.
 - #1249 tracks Dynamic Client Certificates.

For Server scenarios:
- Client certs can be Required or Ignored with the new `QUIC_CREDENTIAL_FLAG_REQUIRE_CLIENT_AUTHENTICATION` flag in #1243
- #1208 and #1190 Provide the client certificate to the server app and allow it to reject the certificate and connection based on that.
