### ISSUE TITLE
Querying the handshake results

### ISSUE THREAD

**Issue by Tratcher** [microsoft/msquic#110]
Compare to [SslStream](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream?view=netcore-3.1#properties).

When the handshake completes the caller may need to know the details of what was negotiated. This information is used for auditing, compatibility checks, and migrations. E.g. "Can I disable this old protocol now or are clients still using it?"

- [x] ALPN
- [x] SNI
- [ ] Server certificate
- [ ] Client certificate
- [ ] Any suppressed remote certificate validation errors
- [x] TLS protocol version (by the time TLS 1.4 gets started)
- [x] CipherAlgorithm
- [x] CipherStrength
- [x] HashAlgorithm
- [x] HashStrength
- [x] KeyExchangeAlgorithm
- [x] KeyExchangeStrength
- [x] CipherSuite

**Comment by ThadHouse** [comment]
For Schannel, CipherSuite is grabbed with the following C# code.

https://github.com/dotnet/runtime/blob/f5874b08b53665ce950b76b628deb63abecaee85/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs#L326

The code for linux openssl is here.
https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Net.Security/src/System/Net/Security/SslConnectionInfo.Linux.cs#L11

**Comment by ThadHouse** [comment]
For an API, based on the existing .NET types, we're looking at something like this struct, which can be read using GetParam at the connection level.

```
struct QUIC_HANDSHAKE_INFO {
    uint32_t TlsProtocolVersion;
    uint32_t CipherAlgorithm;
    uint32_t CipherStrength;
    uint32_t Hash;
    uint32_t HashStrength;
    uint32_t KeyExchangeAlgorithm;
    uint32_t KeyExchangeStrength;
    // All fields above this map directly to SecPkgContext_ConnectionInfo from schannel. Openssl can be mapped to these easily.
    uint32_t CipherSuite; // Maps to dwCipherSuite in SecPkgContext_CipherInfo 
}
```

SNI, Client Cert, Server Cert would likely need to be passed during the QUIC_CONNECTION_EVENT_CONNECTED event as additional parameters.

**Comment by ThadHouse** [comment]
This has been completed, other then a getter API for getting server and client certificate. However, for these, we think it would be better to use the events received to get these, and store them for later use if necessary.
