### ISSUE TITLE
QuicCertCreate uses wrong check variable for QUIC_CREDENTIAL_TYPE_CERTIFICATE_HASH

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#1127]
https://github.com/microsoft/msquic/blob/main/src/platform/cert_capi.c#L511

This should be checking CredConfig->CertificateHash instead of CredConfig->CertificateContext. Because of the union this actually works fine, but still something to be fixed.

**Comment by nibanks** [comment]
I believe there are static asserts that guarantee the offsets for these are the same.

**Comment by ThadHouse** [comment]
Theres none for this one specifically, but all objects in the union are pointers, so theyre all the same currently. Thats why we've never noticed this. The fix is in the password adding PR, and I can always PR it separately if needed.

**Comment by ThadHouse** [comment]
This was closed by #1093
