### ISSUE TITLE
Support Static Library Build Option

### ISSUE THREAD

**Issue by okbaswc** [microsoft/msquic#1133]
How can I properly do a static library build of msquic? I think this should be an option in the build scripts.

I do believe many developers could prefer to link statically to this, for all the typical reasons.

**Comment by nibanks** [comment]
I'm not necessarily opposed to supporting this, but one point of complexity will be the static libraries MsQuic currently links (such as OpenSSL) that the app will have to deal with.

**Comment by ThadHouse** [comment]
Another issue is we do initialization at the dll entry point, both on linux and windows. So in order to do this, a user would have to explicitly call those initialization functions in order to prepare the library for use. Its not impossible, but it would require extra calls to work in a statically linked context.

**Comment by jeremyong** [comment]
I may give this a try this weekend. For the DLL entry replacement, would it be better to do lazy initialization (say, the first time the API table is retrieved) as opposed to user-driven initialization?

**Comment by nibanks** [comment]
> I may give this a try this weekend. For the DLL entry replacement, would it be better to do lazy initialization (say, the first time the API table is retrieved) as opposed to user-driven initialization?

The problem with that is synchronization of two simultaneous initialization calls. That requires a lock to synchronize, but some platforms require a function call **first** to initialize that lock. So lazy initialization isn't possible there.

**Comment by jeremyong** [comment]
OK it didn't occur to me that retrieving the function table needed to be threadsafe (and that this isn't C++ where we can invoke a static initializer on a static constructor in the global namespace)

**Comment by nibanks** [comment]
It's theoretically possible to "roll your own" thing here that's based on interlocked operations in a loop with the first caller just initializing the lock, and the others just spinning until that's done, but I'd prefer not to do that.

**Comment by jeremyong** [comment]
My initial gut is honestly just to use an atomic plus mutex (disabled in the shared lib case). Without contention, the overhead of a mutex/atomic-load is surely negligible right? That said, in my usage of the library, I cache the pointer to the function table, so I assume the concern is the pattern where people retrieve the function table frequently. One remedy is to simply say "don't do that" in the particular case of when the user opts to employ static linkage.

**Comment by jeremyong** [comment]
It took me a moment to remember the pattern I was thinking of but I remembered just now: https://en.wikipedia.org/wiki/Double-checked_locking

In particular, the "problems" with the pattern are relatively easily resolved with new primitives for declaring memory order acquire/release semantics, so the implementation should be portable to Arm or other processors with weaker consistency guarantees.

**Comment by nibanks** [comment]
.NET might need/want support for statical linking for their model of packaging the entire runtime in the consuming app.

**Comment by jeremyong** [comment]
👍🏻 about to look at this now. I glanced over it briefly on the weekend.

**Comment by nibanks** [comment]
Closing this as I believe @thhous-msft finished up the Linux/macOS support of this,
