### ISSUE TITLE
Support QuicTransport (from WebTransport) Protocol

### ISSUE THREAD

**Issue by okbaswc** [microsoft/msquic#1139]
Has msquic been tested against a browser client, like Chrome? I can't seem to get a connection to the mquic sample server (no sign from server that anything is attempted) with Chrome's example WebTransport over Quic client, but maybe it's too early in the game to expect this to work, or I'd be better off looking into quiche.

Example client here:
https://googlechrome.github.io/samples/webtransport/client.html

edit: Is this because msquic is just a component of WebTransport+Quic, and requires more code to work with WebTransport?

**Comment by nibanks** [comment]
Yes, we have compatibility with pretty much all known QUIC implementations. Feel free to see [this interop matrix](https://interop.seemann.io/). It sounds like you're trying to test HTTP/3 interop, which is **not** included with MsQuic. MsQuic is purely a QUIC library, not HTTP or any other application layer. In the future, these types of questions are better suited for https://github.com/microsoft/msquic/discussions. Thanks!

**Comment by nibanks** [comment]
Specifically, for WebTransport that's a pretty thin layer on top of pure QUIC, but we don't yet have a sample for that. We'd be happy to accept a PR that adds a sample for that.

**Comment by erscorms** [comment]
Hi, I recently connected the Chrome WebTransport sample to a project I'm working on using msquic. Looking at the sample code, you'd likely need to make two changes: change the ALPN to be "wq-vvv-01" and add a unidirectional stream to the server configuration. 

In ServerLoadConfiguration:

Settings.PeerUnidiStreamCount = 1;
Settings.IsSet.PeerUnidiStreamCount = TRUE;

If it would fit with the design of the sample, we could probably make it support WebTransport with a few additional flags to customize the stream counts & ALPN. 

Note: I did not test using the certificate workflow outlined in the sample, so that may require additional work.

**Comment by nibanks** [comment]
Hi @erscorms, we'd gladly accept any changes to that effect. I think I'd prefer a separate tool/dir though for this so we can keep the sample clean. Feel free to copy/paste and use it as a base though.

**Comment by nibanks** [comment]
@okbaswc or @erscorms, any hope of a PR to add support, otherwise I'll likely close this issue. We can't sign up to support protocols built on top of QUIC right now.

**Comment by nibanks** [comment]
QuicTransport support was abandoned by the WG, in favor of HTTP based solution. While I disagree with that path, there's not much to do now. No need to implement this in MsQuic.

**Comment by unicomp21** [comment]
Ummm @nibanks, if QuicTransport was abandoned, why did Webtransport recently go GA in Chrome?

https://blog.chromium.org/2021/11/chrome-97-webtransport-new-array-static.html

**Comment by nibanks** [comment]
This is because QuicTransport was over just the QUIC layer. WebTransport is on top of HTTP/3.

**Comment by unicomp21** [comment]
@nibanks what .net lib do I use for supporting server side of webtransport and http/3?

**Comment by nibanks** [comment]
As far as I know, .NET does not support WebTransport; just HTTP/3 (client and server).

**Comment by kdzapp** [comment]
@nibanks For a .NET kestrel web server, does the http3 impl support uni/bidirectional streaming? Assuming yes because it looks like the .NET lib is just using this library, but just wanted to confirm.

I believe that's all we'd need for WebTransport.

**Comment by nibanks** [comment]
No, I believe you're going to need more than that.
