### ISSUE TITLE
Properly handling connection shutdown is difficult to get right

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#1144]
Currently, we have some API issues around connection opening and closing, that we've ran into multiple times, and it would be nice to find a solution to. Take the following example.

```
ConnCallback(Conn, Context, Event) {
   if (Event->Type == QUIC_CONNECTION_TYPE_SHUTDOWN_COMPLETE) {
      MsQuic->ConnectionClose(Conn);
   }
}

// Somewhere not in the worker threads
MsQuic->ConnectionOpen(...) // Assume status is successful here
MsQuic->ConnectionStart(...) // Assume status is successful here
MsQuic->GetParam(Conn, ...) // Get some connection level parameter
```
The following code has a chance to crash, even though it seems fine. At a point during ConnectionStart (even before it returns) and GetParam, the shutdown on the connection can occur. This means GetParam would be called with an invalid handle. 

If we move the ConnectionClose from the event to some point not on the worker thread, we run into a synchronization issue in the other direction, where external code would be required to do cleanup of the handle. This means external code needs to keep a handle for all connections, and explicitly clean them up. We've also seen other issues related to this pop up with closing external code references. 

This is not an unsolvable problem, but is difficult and non obvious. A solution to this currently requires external code to make Close both in the event and externally work. Some code currently uses Ref Counting of the connection to solve this issue, but that is difficult to set up correctly. Others involves specifically checking on flags to see if its safe to close, but that is difficult as well.

**Comment by ThadHouse** [comment]
Currently, I can think of a few solutions to this problem, but there are for sure many more.

1. Add a `QUIC_CONNECTION_TYPE_STARTED` Event that gets called when a connection is first started. This would be where users could do all their initialization code, knowing that references would not be deleted from under them. This is probably the least invasive change, as all old code would still work, and new code could just be cleaned up. As long as you only access the handle from in this event, it will not be deleted from under you.
2. Add a way for a user to increment and decrement the internal ref counts for objects. This is a lot more explicit, and we would need to decide if we want a bumped ref count coming out of ConnectionOpen, which would break all existing code. Lots of devs are used to this, as this is how COM works, but its fairly breaking. We might be able to do this with a parameter or something like that, to make it less breaking.
3. Punt on this issue in C, and in C++ wrappers add an external ref count to handle this. This is easily done, but likely not the scenario we would want to go in.

I'm sure there are more ideas as well, this is just a quick brain dump.

**Comment by nibanks** [comment]
Synchronization is hard. True of any/all multi-threaded programming.

The MsQuic API is definitely design to _try_ to make it easier to clean up connections on the callback thread, but it definitely can lead to issues such as you describe above. Part of this I see as a documentation issue. The follow must be clear:

> If `ConnectionStart` succeeds, then it is possible for the SHUTDOWN_COMPLETE event to have **already been delivered**. If the application calls `ConnectionClose` in response to that event, then the application **must not** use the Connection handle any more.

At a first glance, this is not particularly clear; but once pointed out, I believe it becomes so very quickly. So, first off, we need to make sure this scenario is clearly documented.

Beyond that though, I'm not quite convinced of the need to add the STARTED event. What exactly do you think needs to be done here?

As for ref counting, I believe that is the real solution if multiple parallel threads needs to access the object handle. The follow up question then is if we should expose that functionality from MsQuic or just require the app to deal with it. I'll have to think more about that.

**Comment by nibanks** [comment]
At this point, I feel we should do one of the following:

- Put some extra documentation around this in the API docs warning of this behavior, recommending an app-level ref count solution instead of immediately calling ConnectionClose in the callback.
- Expose APIs for ref counting directly to the app; something like an `AddRef` and `Release` function (following the COM model) for handle objects. The last `Release` call (releasing the last reference) would call <Object>Close implicitly.

**Comment by thhous-msft** [comment]
I think this issue generally can be closed. https://github.com/microsoft/msquic/pull/2226 solves the main issue here, where a handle can be closed before open even finishes. That made things much easier, and much more possible to handle at higher layers.
