### ISSUE TITLE
Remove use of POOL_FLAG_UNINITIALIZED

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#1194]
POOL_FLAG_UNINITIALIZED is now considered unacceptable in kernel code except in exceptional performance scenarios. We need to have actual numbers of performance impact to continue use.

**Comment by nibanks** [comment]
Well, let's just simply remove it and see how the perf numbers look; and go from there.

**Comment by ThadHouse** [comment]
I think we've decided to punt on this. We have a lot of test coverage to make sure we did this right.
