### ISSUE TITLE
Accept Valid Certificates on OpenSSL

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#1202]
Right now, unless the options to skip validation are enabled, OpenSSL will not accept any certificates (after #1190 is merged) by default (peer certificate validation enabled). We should look into making this work. On Linux, the cert files are fine, however on Windows, we likely would like a way to check against the windows certificate store.

Here's how to enable it on Linux
https://mta.openssl.org/pipermail/openssl-users/2018-September/008691.html

Here's some samples for loading from the Windows certificate store.
https://stackoverflow.com/questions/9507184/can-openssl-on-windows-use-the-system-certificate-store

Although for Windows, I want to try using a custom verify callback that we could pass the certificate to Windows directly and get that validated, rather then needing to load everything in.

**Comment by ThadHouse** [comment]
It looks like if we want to use the windows verification method, we can use 
https://docs.microsoft.com/en-us/windows/win32/seccrypto/cryptography-functions#certificate-chain-verification-functions
 and https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certgetcertificatechain
 
 Will investigate.

**Comment by nibanks** [comment]
This might also be of interest on Windows: https://docs.microsoft.com/en-us/windows/win32/api/wintrust/nf-wintrust-winverifytrust, because that's how (AFAIK) Schannel validates certs internally.
