### ISSUE TITLE
Clang: -Wextra-semi warnings

### ISSUE THREAD

**Issue by gvanem** [microsoft/msquic#1220]
Hello, my 1st *"Bug report"* to this project. 

Not exactly a bug, but a nuisance. When downloading the latest Release .zip and trying to compile 
a .c-file with `clang-cl`, I get tons of these warnings:
```c
In file included from ./urldata.h:142:
In file included from ./quic.h:35:
include\msquic.h(101,50): warning: extra ';' outside of a function
      [-Wextra-semi]
DEFINE_ENUM_FLAG_OPERATORS(QUIC_CREDENTIAL_FLAGS);
                                                 ^
include\msquic.h(108,62): warning: extra ';' outside of a function
      [-Wextra-semi]
DEFINE_ENUM_FLAG_OPERATORS(QUIC_CERTIFICATE_HASH_STORE_FLAGS);
                                                             ^
...
```
(in libcurl in my feeble attempt to support QUIC on Win-10)

`<winnt.h>` (or `<ntdef.h>`) already has an empty C-macro for `DEFINE_ENUM_FLAG_OPERATORS()`. 
So those lines in `<msquic.h>` adds this extra `;` on each line (I've not tried with C++).

Looks like you got this correct for Linux and Mac, but not for Windows. Or are we supposed to add some extra `CFLAGS` when using MsQuic? AFAICS, there's not way in my Win-SDK to avoid this silly warning.

**Comment by nibanks** [comment]
Sure, I think all that needs to happen is to remove the `;` right? I can try to get a PR out later, but feel free to send one as well!

**Comment by gvanem** [comment]
Line 110 still has one.

**Comment by nibanks** [comment]
Ah! You're right. I just checked the fix directly in. Thanks for letting me know!
