### ISSUE TITLE
Reset Congestion Control State on Spurious Loss Detection

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#1237]
### Describe the bug

When a congestion event is determined to be spurious, we leave the CC window in the reduced state. We should revert the window in this situation.

### Steps to reproduce the behavior

1. Run WAN perf test with random reordering.
2. See goodput drop significantly.

**Comment by maolson-msft** [comment]
@nibanks  So the problem is bad throughput with random reordering? Did you consider tuning the reordering window rather than adding this new logic on top?

**Comment by nibanks** [comment]
> @nibanks So the problem is bad throughput with random reordering? Did you consider tuning the reordering window rather than adding this new logic on top? We're actively researching that in TCP right now; you should talk to @csujedihy .

I see that as a parallel solution to the same fundamental problem with reordering. Fixing the reordering window can (hopefully) account for future reordering, assuming you can figure out the right threshold to change to. My current PR helps undo the damage for every time the threshold is wrong (including the first time).

**Comment by maolson-msft** [comment]
@nibanks you say parallel but I was thinking more like alternative. Ideally we should prevent the problem from happening in the first place, rather than fixing it afterward, and if we manage to prevent the problem and then there's no more problem, then we don't need to fix it afterward. And we also wouldn't have to deal with "the PrevXxx variables were uninitialized etc etc" type bugs.

**Comment by nibanks** [comment]
Are you suggesting a dynamic threshold solution that isn't "correct after failure" based (i.e. might never actually trigger loss for the first reordering outside the initial threshold)? If not, then I'd argue this logic can/would still apply.

**Comment by maolson-msft** [comment]
That's a decent argument.
