### ISSUE TITLE
Add method to limit partition count on a per app basis

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#1266]
Currently, there is no way to limit partition count on a per app basic. It can only be done globally, which also means it doesn't work on unix platforms.

For user mode clients, creating 2 threads per worker can potentially result in a large amount of memory overhead, especially for 32 bit apps. Lots of apps are still 32 bit for compatibility and to reduce memory footprints. On a 32 core system (not super common, but will get up there pretty soon), 2 threads per core results in 128 MB (1/16th of available address space) of memory usage, which is a bit crazy. Most client apps will never need that many workers, and it really would just be wasted overhead. They could limit themselves to 1-4 and likely be perfectly fine for their use cases.

**Comment by ThadHouse** [comment]
So it turns out 32 bit processes only show up as having 32 cores at max. So the 32 bit side of this isn't a huge deal. However, there still is a ton of overhead when most client apps will never need that.

**Comment by nibanks** [comment]
_If_ we were to do this, it would be through the `QUIC_REGISTRATION_CONFIG`. We already support a means to set the max count to 1 when the app uses the `QUIC_EXECUTION_PROFILE_TYPE_SCAVENGER` profile. We could add a new "custom" profile where the app can directly tune of these internal threading configuration.

All that being said,32-bit is **not** the primary goal here, and I would prefer not to do anything unless an actual customer complained.

**Comment by ThadHouse** [comment]
Once an app like Office or Teams starts shipping, I would be creating an issue as a customer. 128 threads per instance of any office apps or teams would be a bug to me. So once that ships, i would for sure be filing a bug report against office. Even for 64 bit that's a lot of waste.

**Comment by nibanks** [comment]
I agree that it would generally be waste, but it's relative. I've never seen a client machine with that many cores; especially 32-bit. Also for 64-bit, that many cores on a machine generally comes with a lot of RAM as well, so even 128 MB isn't a huge amount. Could we fix it? Yes, but it will add complexity that so far hasn't been worth it. We can keep this issue around to track the problem, but I don't see an immediate need to focus on this.

**Comment by thhous-msft** [comment]
We've not had enough 64 bit customers to worry. Additionally, with windows dropping 32 bit clients all together, there is even less of a case.
