### ISSUE TITLE
CxPlatRandom extremely slow on Linux

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#1282]
I was looking into test run time, and realized PartitionTest.RandomPartitionId takes over 2 minutes to run on linux platforms, even on a fast system. Looking into this, the only noteworthy thing this test does is call CxPlatRandom 131,328,800 times, and then a little bit of logic. Thats a lot of calls, but its fairly quick on windows, so we should look into this. Not sure how often this is called during execution, but its definitely expensive.

**Comment by nibanks** [comment]
@maximus- any ideas on this one?

**Comment by Maximus-** [comment]
I suspect this is a non-issue. /dev/urandom is pretty fast, but reading from it 131mil times just takes actual time, especially since it requires a syscall. If you want the test to run faster, you could just use `srand()/rand()`  which are of course non-cryptographically secure RNGs

**Comment by ThadHouse** [comment]
Realistically, I guess that only comes out to about a microsecond per call. Thats not that unrealistic for a syscall IMO. So I'll likely just close this, and I can look into making the test a bit less duplicative later.

**Comment by Maximus-** [comment]
I was able to repro this - 

![image](https://user-images.githubusercontent.com/628527/109365577-5e4bc580-7846-11eb-9f58-f73d4638fbb2.png)

You are correct that /dev/urandom is *very* slow. I wrote a small test program to read from it 130mil times and it completed in <1s. I don't fully understand what's going on or why there's heavy lock contention.... (https://elixir.bootlin.com/linux/v4.19.177/source/drivers/char/random.c#L431)

Continuing to look into it with perf
