### ISSUE TITLE
Improve debuggability of Random Loss tests

### ISSUE THREAD

**Issue by anrossi** [microsoft/msquic#1286]
Random loss tests use the system RNG to determine whether to drop a packet or not. This makes it hard to reproduce test failures.
Using a deterministic RNG, and logging the seed value, would make it easier to debug random loss test failures.
This would also require adding test support for passing the seed value as a parameter.

**Comment by nibanks** [comment]
@anrossi this has been around a long time and hasn't really been an issue. I think we should just close this. Ok?

**Comment by anrossi** [comment]
Agreed. It would be nice to have a deterministic RNG for testing, but it doesn't really get us anything at this time. Most of our RNG-based tests either pass all the time, or fail every time. We don't have any which are rare repros and might benefit from repeatable RNG sequences.
