### ISSUE TITLE
clang-cl error in 'core/stream.c'

### ISSUE THREAD

**Issue by gvanem** [microsoft/msquic#1310]
Compiling with `clang-cl` v.11 generates this error for `src/core.c`:
```
core/stream.c(454,1): error: conflicting types for 'QuicStreamShutdown'
QuicStreamShutdown(
^
core/stream.h(542,1): note: previous declaration is here
QuicStreamShutdown(
^
1 error generated.
```

Since in the prototype, the `Flags` is an `uint32_t`. Whereas in the implementation it's an
`enum QUIC_STREAM_SHUTDOWN_FLAGS`. `clang-cl` is rather picky on such things; many warnings like:

`anonymous structs are a Microsoft extension [-Wmicrosoft-anon-tag]`

I fixed it by simply:
```diff
--- a/core/stream.h 2021-03-04 13:48:31
+++ b/core/stream.h  2021-03-04 16:37:26
@@ -537,11 +537,13 @@
 //
 // Initiates an asychronous shutdown of one or both directions of the stream.
 //
+enum QUIC_STREAM_SHUTDOWN_FLAGS; // in 'core/msquic.h'
+
 _IRQL_requires_max_(PASSIVE_LEVEL)
 void
 QuicStreamShutdown(
     _In_ QUIC_STREAM* Stream,
-    _In_ uint32_t Flags,
+    _In_ enum QUIC_STREAM_SHUTDOWN_FLAGS Flags,
     _In_ QUIC_VAR_INT ErrorCode
     );
```

**Comment by nibanks** [comment]
Good catch. Feel free to send a PR. For issues as trivial as this, we don't necessarily need an issue first.

**Comment by gvanem** [comment]
There are more issues with `clang-cl` I do not understand. E.g. it triggers on:
```c
static_assert(
    FIELD_OFFSET(QUIC_BUFFER, Length) == FIELD_OFFSET(WSABUF, len),
    "WSABUF is assumed to be interchangeable for QUIC_BUFFER");
```

in `src/platform/datapath_winuser.c`. I fail to see why since after pre-processing a `QUIC_BUFFER::Length` and a `WSABUF::len`
are both the same (at `0`).

**Comment by ThadHouse** [comment]
I actually tried doing clang-cl at one point, and definitely ran into issues like this. I'm not shocked that it has issues. Since MSVC works, we'll accept a PR to get those builds working, but likely we will not have any time to work on it.

**Comment by nibanks** [comment]
I agree with @thadhouse. Feel free to try to fix these with a PR; but it's not high enough priority for us to spend any significant time on it.

**Comment by gvanem** [comment]
Folks, please stick to `CXPLAT_STATIC_ASSERT()` throughout the code 
(and do not use `static_assert()`). I just did:
```diff
--- a/inc/quic_platform_winuser.h 2021-03-04 13:48:31
+++ b/inc/quic_platform_winuser.h 2021-03-04 16:25:46
@@ -145,7 +145,11 @@
 #endif // DEBUG
 #endif // _PREFAST_

-#define CXPLAT_STATIC_ASSERT(X,Y) static_assert(X,Y)
+#ifdef __clang__
+  #define CXPLAT_STATIC_ASSERT(X,Y) _Static_assert(X,Y)
+#else
+  #define CXPLAT_STATIC_ASSERT(X,Y) static_assert(X,Y)
+#endif

 #define CXPLAT_ANALYSIS_ASSERT(X) __analysis_assert(X)
```

and `clang-cl` compiles and builds `msquic.dll` just fine. Some C-11 standard issue going on?

**Comment by nibanks** [comment]
Sounds good. Do you plan to send a PR?

**Comment by gvanem** [comment]
I suck at writing git PR ans such.

**Comment by nibanks** [comment]
> I suck at writing git PR ans such.

:) Very well. I will send a PR to hopefully fix up some of these things, if you're willing to validate it?

**Comment by ThadHouse** [comment]
@gvanem Just curious, how did you enable a clang-ci build? I've tried to do it a few times without success. I'd like to onboard probably 1 clang-ci build just to make sure we don't accidentally break it in the future. And the more compilers we compile with the better.

**Comment by gvanem** [comment]
> how did you enable a clang-ci build? 

My own home-brewed GNU-makefile.
