### ISSUE TITLE
Some benchmarks available.

### ISSUE THREAD

**Issue by stefbon** [microsoft/msquic#1319]
Hi,

I'm writing a set of tools to create an "Open Secure Network" for Linux (and maybe others) using SSH (secure transport), Avahi (detection hosts and services), FUSE and SFTP (for a filesystem). After login user gets a network mountpoint:

/run/network/%USER%/fs/Open Secure Network

where he/she can browse the SSH hosts providing SFTP access. A network path may look like:

/bononline.nl/alarm/{public, sbon}/.... files on host alarm in domain bononline.nl 

See: https://github.com/stefbon/OSNS

I've been looking for a faster data transport than the default over a SSH CHANNEL using SSH_MSG_CHANNEL_DATA message. The way I want is that via the SSH Extensions hosts can exchange data about available alternative transports like libudt and quic.
Now are there any testresults comparing quic using msquic comparing it with libudt and the default tcp?

Thanks in advance.
Stef Bon

BTW: I'm also investigating the use of the library libsmb2 by Ronnie Sahlberg (https://github.com/sahlberg/libsmb2) to have access to Windows Network (ing). Right now I'm busy writing a osns sftp subsystem, so this will have to wait.

**Comment by nibanks** [comment]
Are you looking for data in a network limited or CPU limited environment? https://microsoft.github.io/msquic/wanperf.html includes data for many different network limited scenarios and numbers from TCP/TLS vs QUIC. As far as CPU limited, for TCP/TLS we can achieve ~10 Gbps in the same environment as these tests: https://microsoft.github.io/msquic/detailed.html

**Comment by nibanks** [comment]
Closing. Let me know if you have any other questions.

**Comment by stefbon** [comment]
well if you create a new transport protocol specially for better performance, you want to know how it is doing compared to normal connections over TCP.

**Comment by nibanks** [comment]
Sure. That makes sense. We just haven't collected that data with the same regularity as QUIC data (since this isn't a TCP repo) and haven't added it to the dashboard. I'll see about getting some TCP comparison info on the dashboard.
