### ISSUE TITLE
unable to run tests using test.ps1 on Windows

### ISSUE THREAD

**Issue by wfurt** [microsoft/msquic#1355]
### Describe the bug
I did run `prepare-machine.ps1 -configuration Dev`. Running test as documented using scripts\test.ps1 fails.

### Steps to reproduce the behavior

```
C:\Users\test\github\wfurt-msquic>pwsh scripts\test.ps1
[03/19/2021 14:37:07] C:\Users\test\github\wfurt-msquic\artifacts\bin\windows\x64_Debug_schannel\msquiccoretest.exe (208 test case(s))
New-Item: C:\Users\test\github\wfurt-msquic\scripts\run-gtest.ps1:556
Line |
 556 |      New-Item -Path $WerDumpRegPath -Force | Out-Null
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access to the registry key 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps\msquiccoretest.exe' is denied.
```

Same workflow sequence works on Linux. 

### Expected vs actual behavior

It seems like the documentation should either state that elevate shell is not needed. Preferably IMHO, collecting dump/traces should be optional and not breaking test runs.

**Comment by nibanks** [comment]
We should recommend that the script run while elevated (documentation or perhaps a warning message if not), but also support running it when not elevated.
