### ISSUE TITLE
fail to run quicsample on Linux server, fixed by set SO_REUSEADDR and delete IPV6_DONTFRAG 

### ISSUE THREAD

**Issue by JonathanHsuHH** [microsoft/msquic#1357]
### Describe the bug

I compiled the library on Ubuntu 20.04，and encounter some error when running quicsample as server.
1、exit with ENOPROTOOPT, fixed after delete IPV6_DONTFRAG option
2、exit with EADDRINUSE, fixed after set SO_REUSEADDR to socket

### Steps to reproduce the behavior
Running Linux version is  Ubuntu 20.04.
./quicsample -server -cert_file ./server.cert -key_file ./server.key
ListenerStart failed, 0x5c!

./quicsample -server -cert_file ./server.cert -key_file ./server.key
ListenerStart failed, 0x62!

### Expected vs actual behavior

IPV6_DONTFRAG option seems to be unavailable in linux.
In server with multiple cores,  SO_REUSEADDR option is required since we need to create several listen fd.

**Comment by nibanks** [comment]
That's very weird. They've worked on Ubuntu when we tried. I assume you are running it on the same machine you compiled it? Do you have anything special about your set up?

**Comment by nibanks** [comment]
Also, from a quick search on the internet, it seems that first error would indicate you're using an IP (not IPv6 socket):

> ENOPROTOOPT
> An IP socket option was attempted on an IPv6 socket, or an IPv6 socket option was attempted on an IP socket.

Did you modify any other code?

**Comment by ThadHouse** [comment]
That's very odd, as all of our tests run on Ubuntu 20.04, and on machines with up to 80 cores. A quick Google search shows that the dontfrag issue might occur if your system doesn't support ipv6 at all, or as nick posted above switching to an ipv4 only socket.

Reuseaddr being required is weird, and we use reuseport instead to enable RSS. Reuseport should do everything reuseaddr does and more.

**Comment by JonathanHsuHH** [comment]
I did not modify other code, but my test enviroment is the WSL in windows10.  Maybe this is the difference,  I'll try more efforts to figure this out.

**Comment by ThadHouse** [comment]
Are you using WSL1 or WSL2. I wouldn't be surprised if WSL1 has issues like that, it never had full supported networking anyway. WSL2 definitely should work, and its what I was doing for a lot of the linux development anyway.

**Comment by JonathanHsuHH** [comment]
It's WSL1! I will upgrade to WSL2.
Thank you for your help~
