### ISSUE TITLE
Building on Linux fails due to a openSSL binary not being present

### ISSUE THREAD

**Issue by sebiiV** [microsoft/msquic#1358]
### Describe the bug

Attempting to build fails.
I'm building under a docker environment provided by winAFL but I've tried a "standard" ubuntu distro as well and the same error occurs.

I've included the docker image stuff but I don't think it's pertinent to the issue.

### Steps to reproduce the behavior
Get AFL
```bash
docker pull aflplusplus/aflplusplus
docker run -ti -v /location/of/your/target:/src aflplusplus/aflplusplus
```
In the docker container install ``msquic`` deps
```bash
apt-get update &&
apt-get install build-essential -y &&
apt-get install liblttng-ust-dev -y &&
apt-get install lttng-tools -y
```
Install a correct version of cmake (19.7)
```bash
wget https://github.com/Kitware/CMake/releases/download/v3.19.7/cmake-3.19.7-Linux-x86_64.sh
bash cmake-3.19.7-Linux-x86_64.sh  # Follow instructions
ln -s /src/cmake-3.19.7-Linux-x86_64/bin/cmake /usr/bin/cmake
```
Generate the makefiles
```bash
mkdir build && cd build
cmake -g 'Unix Makefiles' -DCMAKE_C_COMPILER=afl-cc -DCMAKE_CXX_COMPILER=afl-c++ -DQUIC_BUILD_TEST=off ..
```
Build!
```bash
cmake --build .
```
### output
```
Scanning dependencies of target mkdir_openssl_build
[ 40%] Built target mkdir_openssl_build
Scanning dependencies of target OpenSSL_Build
[ 41%] Generating openssl/lib/libcrypto.a, openssl/lib/libssl.a
/bin/sh: 1: /src/submodules/openssl/config: not found
make[2]: *** [CMakeFiles/OpenSSL_Build.dir/build.make:81: openssl/lib/libcrypto.a] Error 127
make[1]: *** [CMakeFiles/Makefile2:469: CMakeFiles/OpenSSL_Build.dir/all] Error 2
```
### Expected vs actual behavior

a msquic binary to be produced.

I've attempted to build via powershell (the ``build.ps1``) and with a "standard" compiler rather than the AFL one but the issue is present in all of them.

**Comment by ThadHouse** [comment]
Did you also clone the submodules? Since you disabled tests, you won't get an error during configuration time.

**Comment by sebiiV** [comment]
Following fixed the issue.
```bash
git submodule init
git submodule update
```
Something so simple 🤦🏾 

Thanks for the nudge.
