### ISSUE TITLE
CLOG Still Executes when -DisableLogs Specified

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#1403]
### Describe the bug

CLOG is still run when I specify the -DisableLogs arg for build.ps1 (on Windows). This should be unnecessary.

### Steps to reproduce the behavior

1. Run `.\build.ps1 -DisableLogs`
2. View output
3. See that CLOG was run

**Comment by nibanks** [comment]
Hmmm. If I add the `-Clean` arg it fixed the problem. Not sure why it didn't figure it out by itself, but I'll go ahead and close this.

**Comment by ThadHouse** [comment]
If you don't add -Clean, it's not actually going to regenerate the build. Same thing if you pass DisableTests. Expected behavior of cmake.
