### ISSUE TITLE
could you provide a usable echo sample?

### ISSUE THREAD

**Issue by warm-dawn** [microsoft/msquic#1413]
### Describe the feature you'd like supported

Example of echo server based on msquic

### Proposed solution

Other examples are slightly more complicated for application development. An echo example is provided for developers to get started.

**Comment by nibanks** [comment]
Have you taken a look at our current sample: https://github.com/microsoft/msquic/blob/main/src/tools/sample/sample.cpp? What more exactly would you like beyond that?

**Comment by warm-dawn** [comment]
What I mean is that the effect of the sample is not intuitive enough, so that beginners will not understand what it is doing, and the echo server can be more intuitive.
I am totally thinking about others 
https://github.com/warm-dawn/MsQuicPP.git
I can also use this thing I made to achieve this goal.
It's just that I think it will be better for you to achieve it.
