### ISSUE TITLE
Datagram perf tracking in performance dashboard

### ISSUE THREAD

**Issue by jeremyong** [microsoft/msquic#1418]
### Describe the feature you'd like supported

It would be great to understand the relative overhead of per-datagram DTLS vs the stream-encoded throughput and latency numbers in the performance dashboard.

### Additional context

One thing I'm not sure about reading the charts are how performance is measured under lossier conditions (e.g. when packets drop due to signal degradation, network congestion, or any other problem). It's also possible the data requested in this ticket is already there and I just don't know how to navigate the data.

Thanks!

**Comment by nibanks** [comment]
Generally, all the dashboards (except https://microsoft.github.io/msquic/wanperf.html) are for loss-less, CPU bound/limited testing. The data in https://microsoft.github.io/msquic/wanperf.html represents the result of the effect of different simulated network conditions. What else are you looking for exactly?

**Comment by jeremyong** [comment]
Specifically, I'm curious about the per-packet processing overhead differences between the reliable streams and datagrams. There's a lot of data out there about the overhead per-packet (since TLS frames are not fragmented), but not as much data about the datagrams as far as I can tell.

**Comment by nibanks** [comment]
>Specifically, I'm curious about the per-packet processing overhead differences between the reliable streams and datagrams.

First what exactly do you mean by "reliable streams" and "datagrams" in this context? Second, how **exactly** do you expect that "overhead" to be measured?

**Comment by jeremyong** [comment]
AFAIK (and keep in mind, I don't consider myself a networking engineering expert in the slightest), independent streams in a QUIC connection can exhibit HOL blocking because packets within a stream cannot be reordered. I was under the impression that TLS decryption for a reliable QUIC stream (the standard stream) is order-dependent. Datagrams I assume must use DTLS or some other datagram-based scheme that allows order-independent decryption. I'm mainly interested in the performance differences between the two.

For example, consider comparing a single stream on a lossless connection vs an equivalent payload of datagrams. Is there a measurable perf impact? What happens if the connection remains lossless but packets arrive out of order? What happens if the connection is lossy?

Feel free to correct me if I'm misunderstanding any of the concepts, as I'm still learning the protocol (I certainly haven't read all the RFCs to the letter, although I am working through them).

**Comment by nibanks** [comment]
QUIC is very different from TCP in these regards:

1. QUIC packet decryptions are completely independent. They can be decrypted in any order and are perfectly fine if some are lost.
2. Data on a single stream can be suffer HOL blocking. Data on separate streams are completely independent and don't suffer HOL blocking.
3. QUIC doesn't use DTLS. It takes the basic TLS 1.3 protocol and strips off the TLS record layer, exchanging just the TLS messages in what QUIC calls CRYPTO frames.

Hopefully this answered all your questions, but feel free to ask more clarifying questions!

**Comment by jeremyong** [comment]
Thanks for the answers! Based on 3, am I correct in understanding that datagrams also use TLS 1.3 then? Based on 2, I can infer that if you don't need reliable ordering, datagrams would be a strict performance win?

**Comment by nibanks** [comment]
Both QUIC streams and QUIC datagrams are just frames (i.e. messages) inside a QUIC packet. All QUIC packets are encrypted using the secrets negotiated via the TLS handshake.

**Comment by nibanks** [comment]
Closing this issue, as I _think_ I've answered all the questions. Feel free to reopen if I'm mistaken!

**Comment by jeremyong** [comment]
Thanks again for answering!
