### ISSUE TITLE
 Shut down by transport, 0xbebc32b All done

### ISSUE THREAD

**Issue by lantiaoxian** [microsoft/msquic#1465]
hi,friend
 
 I run the command powershell under windows system:
 .\quicsample.exe -client -target:192.168.110.51 4567 -unsecure 
 
 error：
   .\quicsample.exe -client -target:192.168.110.51 4567 -unsecure
[conn][00000207993146E0] Connecting...
[conn][00000207993146E0] Shut down by transport, 0x8041012b
[conn][00000207993146E0] All done
 
 
 Run commands under linux system：
 ./quicsample -server -cert_file:server.cert -key_file:server.key
 
 error：
  ./quicsample -server -cert_file:server.cert -key_file:server.key
Press Enter to exit.

[conn][0x7fd4c4000b20] Shut down by transport, 0xbebc32b
[conn][0x7fd4c4000b20] All done

How to solve it, please

**Comment by ThadHouse** [comment]
That error corresponds to a TLS error for unsupported certificate. Are you using a self signed certificate, or an actual certificate. If self signed, how did you generate it?

**Comment by lantiaoxian** [comment]
hi,friend
Under the LINUX system, I use
openssl req  -nodes -new -x509  -keyout server.key -out server.cert
Generate certificate

**Comment by lantiaoxian** [comment]
hi,friend ,Do you have any good suggestions, please，thanks.

**Comment by nibanks** [comment]
Can you follow the instructions [here](https://github.com/microsoft/msquic/blob/main/docs/Diagnostics.md) to collect logs to see what's failing?
