### ISSUE TITLE
Single File QuicTrace.exe

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#1491]
### Describe the feature you'd like supported

Right now, quictrace.exe depends on a lot of stuff. It might be better to make it a single file executable and package up all the stuff in a single binary.

**Comment by ThadHouse** [comment]
It looks like .NET 6 fixes the issues I was running into with this. An untrimmed binary sits at 62 MB, whereas trimmed in 20 MB. We'd just need to check that the trimmed version doesn't break anything. It does have warnings though in some of the ETW code, so its possible. I'll investigate when I have some free time.

**Comment by thhous-msft** [comment]
Turns out this is actually blocked on the WPA SDK. Theyre plugin loading will only load from a directory, which a single file exe breaks. I made an issue to report this to them.

https://github.com/microsoft/microsoft-performance-toolkit-sdk/issues/177
