### ISSUE TITLE
CMake Error at CMakeLists.txt:308 (configure_file):   Invalid argument

### ISSUE THREAD

**Issue by dbyoung720** [microsoft/msquic#1494]
CMake Error at CMakeLists.txt:308 (configure_file):
  Invalid argument

WIN10+VS2019+X64

**Comment by ThadHouse** [comment]
What version of cmake. And the latest vs 2019 update, correct?

**Comment by dbyoung720** [comment]
CMAKE3.19.1 +VS2019 latest

**Comment by ThadHouse** [comment]
Are you attempting to build using cmake directly instead of using the build powershell scripts? The powershell scripts are the main way we build and it looks like there might be a big with a direct cmake build on windows.

**Comment by dbyoung720** [comment]
CMake 3.19.1 + VS2019 + X86 is OK

**Comment by dbyoung720** [comment]
PS build OK
