### ISSUE TITLE
Improve configuration documentation

### ISSUE THREAD

**Issue by JamesNK** [microsoft/msquic#1506]
Improve the configuration docs at https://github.com/microsoft/msquic/blob/main/docs/Deployment.md. Today it is unclear about what some settings do and what value msquic will use by default.

* Add description to all settings
* Add msquic's default value to all settings

Example: https://docs.microsoft.com/en-us/aspnet/core/grpc/configuration

**Comment by nibanks** [comment]
@JamesNK would you mind taking a look at the latest docs and let us know if you'd like us to do anything else before we close this issue? Thanks!

**Comment by JamesNK** [comment]
Looks much better. There are some TODOs for MinimumMtu. Fix those before closing?
