### ISSUE TITLE
Client UDP Stops Working

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#1553]
### Describe the bug

I was looking at a recent one-off test failure's logs and it seems that after some time, we just stop getting any UDP operations (send or receive) on the client side. This happened with the Windows user mode client, and I have no reason to believe it would affect any other platform specific data path. No errors were spit out, which seems to indicate that we're posting completions to the IOCP but they aren't happening somehow. Only seen this the one time so far...

[quic.log](https://github.com/microsoft/msquic/files/6436955/quic.log)

**Comment by ThadHouse** [comment]
We found a case where this could occur without a log. The following PR fixed this to ensure if this case occured a log would happen, and would also retry a few times to get past the failing case.

https://github.com/microsoft/msquic/pull/1739

**Comment by thhous-msft** [comment]
I found another way UDP receive could die.

https://github.com/microsoft/msquic/blob/main/src/platform/datapath_winuser.c#L4100

If this for some reason returns false, UDP receive will stop without a log, as a receive will not be restarted.

**Comment by nibanks** [comment]
> I found another way UDP receive could die.
> 
> https://github.com/microsoft/msquic/blob/main/src/platform/datapath_winuser.c#L4100
> 
> If this for some reason returns false, UDP receive will stop without a log, as a receive will not be restarted.

This is supposed to fail when the binding is shutting down.

**Comment by thhous-msft** [comment]
I agree its supposed to, but what if it fails in the normal case. I know it shouldn't, but I've seen too many shouldn'ts come true to trust that thinking. Just a log in that case would be enough.

**Comment by nibanks** [comment]
@thhous-msft what's the latest on this? Do we need to make a change here or can we close this?

**Comment by thhous-msft** [comment]
I think its fine. We haven't seen this bug again since we added the retries.
