### ISSUE TITLE
Memory Leak in QuicPacketBuilderFinalize

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#156]
While looking at the code, I noticed there are several failure paths in the QuicPacketBuilderFinalize function that don't result in the current packet metadata being cleaned up. It could have a reference to a stream, which doesn't get released. This will at best leak additional memory, and at worst cause a hang in clean up.

**Comment by Ethan-Arrowood** [comment]
Hi! Can I take a crack at this if possible? I'm not a super experienced C developer but I know a thing or two about network programming and some of the basics of QUIC

**Comment by nibanks** [comment]
Feel free to take a look. We're still not taking non-MSFT contributions quite yet, but since you are MSFT go ahead! Thanks!

**Comment by Ethan-Arrowood** [comment]
Sounds good! Thank you 😄

**Comment by Ethan-Arrowood** [comment]
I'm having a hard time building the repo on Mac. Using cmake from root and its failing because I'm missing some variables `LTTNGUST_LIBRARIES LTTNGUST_INCLUDE_DIRS`?

If dev on Mac isn't totally supported yet I don't want to make more work for y'all so I'll unassign myself from this issue and let someone else pick it up instead!

**Comment by nibanks** [comment]
Mac is completely unsupported right now. Only Linux (Ubuntu) and Windows are currently supported.

**Comment by Ethan-Arrowood** [comment]
Understandable! I'm going to try and get an Ubuntu box up and running cause I would really like to contribute. I'll comment here if I need to give this up or not by the end of the day.

**Comment by Ethan-Arrowood** [comment]
I was able to get things building with VSCode Dev Containers 😄

**Comment by AntoniMordor** [comment]
hello can someone help me with a project.
The project I want to do is an editor with html text created with c ++ tell me if possible here is the link [https://github.com/AntoniMordor/Html-text-editor-/tree/master/project](url)

**Comment by alomoshaver** [comment]
سلام میتوانید به من کمک کنید برنامه اپ اندرویید وبسایت موتور جستجوگر املاک مستغلات لازم دارم
