### ISSUE TITLE
Test Failure in ParameterValidation.ValidateConnection

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#1582]
### Describe the bug

```
/home/vsts/work/1/s/src/test/lib/ApiTest.cpp:518: Failure
ConnectionSendResumptionTicket has unexpected error! Expected 0xbebc202, actual 0x0
```

We don't have logs because it happened on an ASAN run, where LTTng doesn't work. I took a quick look at the code and I'm not sure why the following code would be succeeding instead of failing:

```c
    if (Event->Type == QUIC_CONNECTION_EVENT_CONNECTED) {
        QUIC_STATUS Status =
            MsQuic->ConnectionSendResumptionTicket(
                Connection,
                QUIC_SEND_RESUMPTION_FLAG_NONE,
                0,
                nullptr);
        if (Status != QUIC_STATUS_INVALID_STATE) {
            TEST_FAILURE(
                "ConnectionSendResumptionTicket has unexpected error! Expected 0x%x, actual 0x%x",
                QUIC_STATUS_INVALID_STATE,
                Status);
        }
```
According to the checks in api.c, that means it must be connected with resumption enabled:
```c
    if (!Connection->State.ResumptionEnabled ||
        !Connection->State.Connected ||
        !Connection->Crypto.TlsState.HandshakeComplete) {
        Status = QUIC_STATUS_INVALID_STATE; // TODO - Support queueing up the ticket to send once connected.
        goto Error;
    }
```
Only seen it the one time, but creating this bug to track. Currently marking it as a test bug, as that is where I suspect the issue is.

**Comment by ThadHouse** [comment]
Happened again in https://dev.azure.com/ms/msquic/_build/results?buildId=166045&view=logs&j=e2236ac7-b409-5bb1-0b69-b4a92122e36a&t=0d0e0a7c-7680-52dc-f392-89c1db582d99&l=293 on macOS.

**Comment by nibanks** [comment]
Happened again in https://dev.azure.com/ms/msquic/_build/results?buildId=167594&view=logs&j=8d15ad05-97f2-503a-4cb9-fd8e4623ece2&t=8830fbc6-153a-5278-9084-09bec77a606f&l=293 on Linux (ASAN).

**Comment by Maximus-** [comment]
What's the barrier of LTTng and ASAN?

**Comment by nibanks** [comment]
I believe https://github.com/google/sanitizers/issues/723 covers it.

**Comment by nibanks** [comment]
Another hit: https://dev.azure.com/ms/msquic/_build/results?buildId=179016&view=logs&j=8d15ad05-97f2-503a-4cb9-fd8e4623ece2&t=8830fbc6-153a-5278-9084-09bec77a606f&l=293

**Comment by nibanks** [comment]
Another hit: https://dev.azure.com/ms/msquic/_build/results?buildId=203845&view=logs&j=8d15ad05-97f2-503a-4cb9-fd8e4623ece2&t=8830fbc6-153a-5278-9084-09bec77a606f
