### ISSUE TITLE
QuicTestKeyUpdateRandomLoss Test Failure

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#1596]
### Describe the bug

On the latest main CI, the QuicTestKeyUpdateRandomLoss test failed once (logs attached). There were quite a large number of packets dropped, so I wonder if the test is just being too aggressive.

[quic.zip](https://github.com/microsoft/msquic/files/6487748/quic.zip)

**Comment by ThadHouse** [comment]
That's a new test, and it's very possible it's too aggressive.

**Comment by nibanks** [comment]
Another failure (Windows kernel) here: https://dev.azure.com/ms/msquic/_build/results?buildId=167832&view=logs&j=43391c15-1fb0-558b-e071-5b6c483c562b&t=1ccedb59-1ddf-5d57-a60f-3e61dbf09531

**Comment by ThadHouse** [comment]
Closing, as the test was being too aggressive and cared how the connection was shutdown. For this test specifically the only thing we care about is that no decryption failures occur.
