### ISSUE TITLE
Test Failure in ParameterValidation.ValidateConnection (Peer never signaled connected event)

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#1616]
### Describe the bug

Might be related to #1582, but might not.

In the latest main CI run, on Windows OpenSSL, we hit the following failure:
```
[ RUN      ] ParameterValidation.ValidateConnection
D:\a\1\msquic\src\test\lib\ApiTest.cpp(492): error: Peer never signaled connected event
[  FAILED  ] ParameterValidation.ValidateConnection (11589 ms)
```
This corresponds to this code:
```c++
#ifndef QUIC_DISABLE_0RTT_TESTS
static
QUIC_STATUS
AutoShutdownConnectionCallback(
    MsQuicConnection* Connection,
    void* Context,
    QUIC_CONNECTION_EVENT* Event
    )
{
    if (Event->Type == QUIC_CONNECTION_EVENT_CONNECTED) {
        if (Context != nullptr) {
            if (!((CxPlatEvent*)Context)->WaitTimeout(1000)) {
                TEST_FAILURE("Peer never signaled connected event");              <=========HERE
```
It seems bad that we are waiting on a callback thread. I am guessing we happen to hit a case where both connections were being serviced by the same worker thread, and blocking this one caused the other to block. The test code needs to be updated not to wait on the callback.

Logs: [quic.zip](https://github.com/microsoft/msquic/files/6510678/quic.zip)

**Comment by ThadHouse** [comment]
Seen again at https://dev.azure.com/ms/msquic/_build/results?buildId=183992&view=logs&s=be89ece8-b1db-5b53-5b1d-fe3b3196925d&j=d91c8496-843a-5c6a-cc6b-c76b8a319d75
