### ISSUE TITLE
Legend is missing in the perf dashboard

### ISSUE THREAD

**Issue by pravb** [microsoft/msquic#1627]
### Describe the bug

Add a legend or note to the performance dashboard https://microsoft.github.io/msquic/index.html summarizing hardware specs used and microbenchmark/commands used

### Steps to reproduce the behavior

Navigate to https://microsoft.github.io/msquic/index.html. There is no information about system specs or commands used.

### Expected vs actual behavior

Some way to access the legend information.

**Comment by nibanks** [comment]
I added some info on the hardware specs here: https://microsoft.github.io/msquic/index.html#hardware. I'll add more about how we test things too.

**Comment by nibanks** [comment]
Now there is a methodology section as well: https://microsoft.github.io/msquic/index.html#methodology. Please suggest any additional changes you may think would improve this.
