### ISSUE TITLE
Entry zero is repeatedly overwritten?

### ISSUE THREAD

**Issue by larseggert** [microsoft/msquic#1663]
https://github.com/microsoft/msquic/blob/main/src/core/library.c#L965-L969 seems odd, entry zero is repeatedly overwritten?

**Comment by nibanks** [comment]
Good catch. I'll fix, or feel free to send a PR.

**Comment by larseggert** [comment]
If you used clang-tidy it would have alerted you :-) it finds more stuff in the current code FWIW.

**Comment by nibanks** [comment]
> If you used clang-tidy it would have alerted you :-) it finds more stuff in the current code FWIW.

I thought you already onboarded all that stuff to MsQuic? (I'm quite ignorant when it comes to clang* stuff)

**Comment by larseggert** [comment]
Yes, but it's apparently not used during CI, and I don't k ow how to add it
