### ISSUE TITLE
msquic.hpp use #include "msquic.h" instead of #include <msquic.h>

### ISSUE THREAD

**Issue by timprepscius** [microsoft/msquic#1702]
In msquic.hpp:

#pragma once

#include <msquic.h>

probably should be:

#pragma once

#include "msquic.h"

because:
1.  msquic.h is in the same directory as msquic.hpp
2. unless you are going to separate into two libraries, msquic.h would be the same library as msquic.hpp and therefore should be " instead of <, as < references libraries outside of your own, and " references files local to your own project
3.  I use #include <msquic/msquic.h> where I symbolic link the directory.

Alternatives is that you could have a #ifndef _MSQUIC_ -- #include <msquic.h> some libraries do this, or some libraries do #define MSQUIC_HEADER_FILE  and then #include MSQUIC_HEADER_FILE

**Comment by nibanks** [comment]
Feel free to send PRs!
