### ISSUE TITLE
possibly make param ids non overlapping

### ISSUE THREAD

**Issue by timprepscius** [microsoft/msquic#1708]
I wrote the code:		
Status = quic->GetParam(acceptor->handle, QUIC_PARAM_LEVEL_LISTENER, QUIC_PARAM_CONN_LOCAL_ADDRESS, &Size, &Address)

And it didn't fail.

It would be nice if it failed.  If the PARAM_CONSTANTS were non overlapping, then you could detect misuse and fail (actually I think your code already would detect misuse).

**Comment by nibanks** [comment]
We will think about it. My biggest problem is that it would be a breaking change for the API, which I'd like to avoid if at all possible.
