### ISSUE TITLE
> 33 connections between two sockets

### ISSUE THREAD

**Issue by timprepscius** [microsoft/msquic#1710]
I start a listener.
I initiate 100 connections to the listener.

Only 33 show up.  Exactly on each run.

After 33rd, the listener callback is not being called.

Does this ring any bells?

**Comment by nibanks** [comment]
You will need to grab logs to see why. It might be that you're hitting CPU limit threshold that cause it's to reject new connections.

**Comment by nibanks** [comment]
https://github.com/microsoft/msquic/blob/main/docs/Diagnostics.md#trace-collection

**Comment by timprepscius** [comment]
There is a high probability that this was being caused by my not doing:

MsQuicSettings()
            .SetServerResumptionLevel(QUIC_SERVER_RESUME_AND_ZERORTT)
            .SetPeerBidiStreamCount(1)
# other settings
