### ISSUE TITLE
Stream Priorities

### ISSUE THREAD

**Issue by anrossi** [microsoft/msquic#1716]
### Describe the feature you'd like supported

Stream data is currently framed in a first-come, first-served (FCFS) basis by order of call to `StreamSend`, or optionally a round-robin basis.  HTTP3 supports priorities, and MsQuic should also support priorities on streams.
Imagine a scenario where an application has a control stream, and a data stream. The data stream queues a single large send (100s of MB), while the control stream occasionally queues small sends (100s of bytes) every 10 seconds. The control stream data will not send at all until all data stream data has sent.  This is problematic for the control stream since it is starved until all data has sent.

### Proposed solution

Stream would have a new parameter where you can set a `uint16_t` priority value; higher values are higher priority.  Stream data queued for sending is framed FCFS within a given priority level, and higher priorities will be completely flushed before lower priorities are framed for sending.
In the example application above, the control stream would be configured with a high priority (e.g. 65535), and the data stream would be configured with low, default priority (e.g. 0). The control stream data would be flushed in each send, before MsQuic would continue sending the lower priority stream.

**Comment by nibanks** [comment]
Fixed by https://github.com/microsoft/msquic/pull/1778.
