### ISSUE TITLE
404 occours with https://github.com/microsoft/msquic/blob/main/src/tools/sample/sample.cpp

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/msquic#1785]

**Comment by ThadHouse** [comment]
We recently switched the sample to c, so it ends with .c and not .cpp. Do we have this linked somewhere we need to update?

**Comment by xspeed1989** [comment]
> We recently switched the sample to c, so it ends with .c and not .cpp. I'll update the readme tomorrow.

you need update url in readme
