### ISSUE TITLE
Bad Certificate via OpenSSL on Windows

### ISSUE THREAD

**Issue by wegylexy** [microsoft/msquic#1794]
After updating OpenSSL, which now requires `nasm` x86 or x64, v1.4.0 can no longer be built for ARM64 (or ARM64EC for Windows 11 on ARM). How to support older Windows 10 on ARM where SChannel did not support TLS1.3?

**Comment by nibanks** [comment]
I'm pretty sure `nasm` has always been a requirement to build OpenSSL on Windows. @thadhouse knows more though, most likely.

**Comment by ThadHouse** [comment]
It definitely should support arm64, and I've built it recently. What error are you seeing?

**Comment by wegylexy** [comment]
Maybe something in Windows 10 Insider Preview Build 21390 that breaks OpenSSL. Can't even build v1.3.0 with OpenSSL 1.1.1k+quic now, previously worked. Then v1.4.0 requires `nasm` for OpenSSL 3 alpha but no `arm64` version is available.

By the way, when the openssl build is wrapped in .NET 6 preview 5, `crypt32` crashes on receiving a peer certificate due to access violation, even for v1.3.0 win-x64 which previously worked. The SChannel one works fine.

**Comment by ThadHouse** [comment]
I just double checked, and our ci does build on arm64 openssl. So it definitely works. Can you try the latest main. The arm work was done I think after we did 1.4, so I'm surprised it worked at all before.

Do you have a backtrace or dump for the crash? Also does it reproduce with latest main?

**Comment by wegylexy** [comment]
Switched back to `Visual Studio 16 2019` from `Ninja`, then v1.3.0 builds fine again.
Will try latest.

**Comment by wegylexy** [comment]
Still crashes at the same place with latest main in .NET 6 preview 5.
![image](https://user-images.githubusercontent.com/8196926/124332305-c11de680-dbc3-11eb-85be-3735888c8a08.png)

**Comment by ThadHouse** [comment]
That's calling through .NET. I thought you ment internal errors. I think on windows .NET assumes Schannel, so check that openssl windows is a supported configuration with them.

**Comment by wegylexy** [comment]
The non-Windows branch would check if it's a certificate chain and then extract the first one. It appears that when using OpenSSL, the remote cert is wrapped in a chain. Now I get `0x8041012A` or Bad Certificate. Though the same .NET code works on Linux in docker, which uses OpenSSL too.

**Comment by ThadHouse** [comment]
.NET's QUIC wrappers require schannel on Windows. They do not support OpenSSL on Windows, and that would cause the crashes you are seeing. The way the certificates are returned are different for the different providers, so the higher level code must match the TLS provider used. Unless you are seeing this using schannel builds on windows, this is not anything we can solve, and it would need to be an ask on the .NET team to support OpenSSL on windows.

**Comment by wegylexy** [comment]
Right, I need to make .NET skip validation when the user-provided validation callback simply returns true.
