### ISSUE TITLE
Support OSX

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#18]
Along with Windows and Linux, we need OSX support as well.

**Comment by larseggert** [comment]
I have some very rough changes to make this compile under Darwin in https://github.com/larseggert/msquic/tree/darwin. 

There are a lot of FIXMEs, so this clearly won't run.

But it compiles with `cmake -DQUIC_ENABLE_LOGGING=OFF -DQUIC_BUILD_TEST=OFF ..`.

I also had to suppress some additional warnings due to `-Werror` being used. Some of those looked like they might actually be worth fixing...

**Comment by nibanks** [comment]
Thanks @larseggert! That seems like a great start! I know @maximus- was looking more into this. It might be worth starting a `feature/mac` branch for this work.

**Comment by Maximus-** [comment]
I googled around a bit and couldn't get a firm answer on whether or not LTTng works on macOS. I'm also wondering if kqueue is the best for high performance IO on macOS.. I think it is?

**Comment by larseggert** [comment]
I have no idea if LTTNG works on MacOS, but `-DQUIC_ENABLE_LOGGING=OFF` removes the dependency.

I think `kqueue` is the logical choice, esp. since it also provides some functionality that `eventfd` on Linux is used for. I think it might be possible to replace `epoll` and `eventfd` with `kqueue`.

**Comment by Maximus-** [comment]
I've made a branch users/mxms/macos to track this work. This looks a lot like @larseggert's work so far, except everything is just empty. Currently building with `-DQUIC_ENABLE_LOGGING=OFF -DQUIC_BUILD_TEST=OFF -DQUIC_TLS=stub`. Also lots of CMake hackery.

**Comment by Maximus-** [comment]
Eventually we should implement support for `sendmsg_x` in the macOS datapath as well. This is the analog to sendmmsg. I don't think it has the striping-like feature though, will still need multiple iovecs. Surely the iovecs can just be pointers to different places in the same buffer, though. Just putting this here so we don't forget. :)

**Comment by larseggert** [comment]
Wow, I didn't know about `sendmsg_x`! There isn't much documentation about it - do you have a pointer on how to use it?

**Comment by Maximus-** [comment]
Indeed, it seems ancillary data is unsupported. However, at least for client-side bound sockets, it might be worthwhile. I have an example I posted here https://gist.github.com/Maximus-/487c70508e161680d550ccb343781859

**Comment by larseggert** [comment]
`user/mxms/macos` seems to be broken at the moment? 

```
# cmake -DQUIC_ENABLE_LOGGING=OFF -DQUIC_BUILD_TEST=OFF ..
-- CMAKE Version: 3.18.0
-- Source Dir: /Users/lars/Documents/Code/msquic
-- Host System name: Darwin
-- Setting policy 0091
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- System name: Darwin
-- System version: 19.6.0
-- Platform version:
-- QUIC Platform: darwin
CMake Error at CMakeLists.txt:165 (include):
  include could not find load file:

    /Users/lars/Documents/Code/msquic/build/clog/CLog.cmake


-- Disabling tracing
-- Disabling session resumption support
-- Disabling 0-RTT support
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMake Error at src/core/CMakeLists.txt:47 (CLOG_GENERATE_TARGET):
  Unknown CMake command "CLOG_GENERATE_TARGET".


-- Configuring incomplete, errors occurred!
See also "/Users/lars/Documents/Code/msquic/Darwin/CMakeFiles/CMakeOutput.log".
```

Looks like #612 is to blame.

**Comment by ThadHouse** [comment]
Did you run the prepare machine script with the Build configuration? Builds currently require a tool called CLOG to be installed as a dotnet global tool. So you need dotnet core 3.1, and then to run that script.

**Comment by nibanks** [comment]
Also, we've got https://github.com/microsoft/msquic/pull/652 in PR right now that will allow you to build with just cmake without these extra dependencies, provided you disable logging.

**Comment by larseggert** [comment]
Remember that I am trying to build on OSX - I don't think `scripts/prepare-machine.ps1` supports that?

But it looks like #652 would fix the issue.

**Comment by nibanks** [comment]
For those who are interested in contributing to OSX support, please direct your PRs to the `feature/mac-os` branch. Thanks!

**Comment by ThadHouse** [comment]
The mac-os feature branch has been brought up to date, and merged into master.

Currently, the datapath does not work as expected, because of some issues in macos regarding dual mode sockets and getting connection data. This is the big thing that needs to be fixed to have macos support.

The other thing is we have no logging support currently for mac. We do have a way to log to stdout, but that is very chatty. Being able to log to macOS unified logging would be nice. It would require the work to be done in CLOG to make that work.

**Comment by ThadHouse** [comment]
With the merge of #1260 we can consider macOS support in general complete. We can make individual feature requests for things like integrating the macOS keystore and logging, but for now you can run MsQuic on macOS.

**Comment by larseggert** [comment]
Might want to add OSX to the CI matrix, if it isn't there already.

**Comment by ThadHouse** [comment]
It's running the BVTs, and we're going to enable interior tests too.
