### ISSUE TITLE
PEER_CERTIFICATE_RECEIVED emitted multiple times on Linux client

### ISSUE THREAD

**Issue by wfurt** [microsoft/msquic#1810]
With simple QUIC client trying to connect to server I get following events on Linux:
```
  [conn][0x7F0B14186A50] Connection received event IDEAL_PROCESSOR_CHANGED
  [conn][0x7F0B14185E30] Connection received event PEER_CERTIFICATE_RECEIVED
  [conn][0x7F0B14185E30] Connection received event PEER_CERTIFICATE_RECEIVED
  [conn][0x7F0B14185E30] Connection received event PEER_CERTIFICATE_RECEIVED
  [conn][0x7F0B14185E30] Connection received event PEER_CERTIFICATE_RECEIVED
  [conn][0x7F0B14185E30] Connection received event STREAMS_AVAILABLE
  [conn][0x7F0B14185E30] Connection received event DATAGRAM_STATE_CHANGED
  [conn][0x7F0B14185E30] Connection received event CONNECTED
  [conn][0x7F0B14186A50] Connection received event CONNECTED
  [conn][0x7F0B14186A50] Connection received event SHUTDOWN_COMPLETE
  [conn][0x7F0B14185E30] Connection received event SHUTDOWN_COMPLETE
```
0x7F0B14185E30 is the client. 
This has two issue:
1) Functionally int breaks validation in .NET for HTTP https://github.com/dotnet/runtime/issues/55192
There is code to map the event to original HttpRequest and it fails when the callback is invoked multiple times. 
2) Verifying the certificate is not cheap. Building the X509Chain and doing the crypto is not trivial. 

This looks platform specific as same code executed on Windows gives expected outcome:
```
     System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateChain [STARTING]
  [conn][0x1E4EEC86F60] Connection received event IDEAL_PROCESSOR_CHANGED
  [conn][0x1E4EEC63D40] Connection received event STREAMS_AVAILABLE
  [conn][0x1E4EEC63D40] Connection received event DATAGRAM_STATE_CHANGED
  [conn][0x1E4EEC63D40] Connection received event PEER_CERTIFICATE_RECEIVED
  [conn][0x1E4EEC63D40] Connection received event CONNECTED
  [conn][0x1E4EEC86F60] Connection received event SHUTDOWN_COMPLETE
  [conn][0x1E4EEC63D40] Connection received event SHUTDOWN_COMPLETE
      System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateChain [FINISHED] Time: 0.9379798s
    Finished:    System.Net.Quic.Functional.Tests
```

I did some quick checking and this seems to some from OpenSSL. CxPlatTlsCertificateVerifyCallback is truly invoked multiple times.  

cc: @manickap

**Comment by ThadHouse** [comment]
When originally writing the code, I did notice we'd get the callback twice from OpenSSL. Based on the documentation, it seems like its called for each certificate in the chain, starting from the bottom. I'm assuming .NET's OpenSSL support has similar behavior, but its handled in its PAL. Do you know where the code is in .NET for handling this?

**Comment by ThadHouse** [comment]
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L415

Ah. It looks like .NET just lets OpenSSL's verification always pass, and then does the checking afterwards. Hmm. So fixing this is likely going to require just handling the verification in a slightly different spot. I'll look into this.

```
// Full validation is handled after the handshake in VerifyCertificateProperties and the
// user callback.  It's also up to those handlers to decide if a null certificate
// is appropriate.  So just return success to tell OpenSSL that the cert is acceptable,
// we'll process it after the handshake finishes.
```

**Comment by wfurt** [comment]
Thanks @ThadHouse, that would make sense. Even if I don't know how one would know from the call what certificate to verify. The Cert passed to the callback is always the same e.g. 
```
 X509* Cert = X509_STORE_CTX_get0_cert(x509_ctx);
```
gives the leaf.

**Comment by wfurt** [comment]
And yes, .NET is different. When handshake is done we ask for peer certificate and we do validation afterward.
