### ISSUE TITLE
Expand Version Negotiation Extension testing

### ISSUE THREAD

**Issue by anrossi** [microsoft/msquic#1831]
Test scenarios that are not currently tested:
- [ ] Third party tries to force version downgrade via injected VN packet
- [ ] Third party changes the version field during handshake
- [ ] Server initiates incompatible version negotiation, and also does compatible version negotiation on the second attempt.

**Comment by nibanks** [comment]
I think it'd be best to just copy these to https://github.com/microsoft/msquic/issues/1218 and close this issue.

**Comment by anrossi** [comment]
Copied to 1218.
