### ISSUE TITLE
Centos7 compile error after RSS support added in #1217

### ISSUE THREAD

**Issue by Matt-DWA** [microsoft/msquic#1842]
### Describe the bug

When compiling on centos7, we are seeing the following error:

```
[ 30%] Building C object src/platform/CMakeFiles/platform.dir/datapath_epoll.c.o
/git/msquic/src/platform/datapath_epoll.c: In function 'CxPlatSocketConfigureRss':
/git/msquic/src/platform/datapath_epoll.c:814:13: error: 'SO_ATTACH_REUSEPORT_CBPF' undeclared (first use in this function); did you mean 'SO_ATTACH_FILTER'?
             SO_ATTACH_REUSEPORT_CBPF,
             ^~~~~~~~~~~~~~~~~~~~~~~~
             SO_ATTACH_FILTER
/git/msquic/src/platform/datapath_epoll.c:814:13: note: each undeclared identifier is reported only once for each function it appears in
gmake[2]: *** [src/platform/CMakeFiles/platform.dir/build.make:83: src/platform/CMakeFiles/platform.dir/datapath_epoll.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:676: src/platform/CMakeFiles/platform.dir/all] Error 2
gmake: *** [Makefile:161: all] Error 2
```

This was introduced in commit: 
7dca51521c1ea307febaab8c3b79cafedc8601b8 Add support for RSS on linux (#1217)

The prior commit compiled with no errors:  c6a23f377d4001a9c5d933bfb1d33ba8576a24de

### Steps to reproduce the behavior
We are running the build in a centos7 docker container. Here is the pertinent version and dependency info:
```
FROM centos:7

RUN yum install -y wget && \
    wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y ./epel-release-latest-7.noarch.rpm && \
    yum install -y centos-release-scl && \
    yum install -y lttng-ust-devel cmake3 libatomic devtoolset-7 git perl-Data-Dumper cpan openssl
```
We can provide the dockerfile if that is helpful.

### Expected vs actual behavior

We would expect the build to complete successfully without the above error.

**Comment by ThadHouse** [comment]
Are you attempting to build from the latest main? This was reported a few months ago, and was fixed. The line numbers are off from where that macro is currently used, so thats my guess is just an out of date commit.

**Comment by Matt-DWA** [comment]
Ahg. You are right. Everything is working. Sorry for wasting your time.
