### ISSUE TITLE
Support epoll Without Using sendmmsg

### ISSUE THREAD

**Issue by hros** [microsoft/msquic#1884]
I am trying to port msquic to Julia
The Julia packaging framework, [BinaryBuilder](https://github.com/JuliaPackaging/BinaryBuilder.jl), is based on a relatively old version of `libc` which does not support `sendmmsg` which is used in `src/platform/datapath_epoll.c`
The library versions used by BinaryBuilder, are listed in this [page](https://github.com/JuliaPackaging/Yggdrasil/blob/master/RootFS.md)

Is it possible to build msquic for Linux without the use of `sendmmsg`?
Would it impact performance?
Is there an option to add the necessary support without relying on a new version of `glibc`?

**Comment by thhous-msft** [comment]
There will be a performance impact removing sendmmsg. Likely a significant one as well. Currently there is no build option to fall back to sendmsg, but that is potentially something that can be looked at in the future.

**Comment by hros** [comment]
Then, if I understand correctly there is no way to build the project with older glib libraries?

What about adding the `sendmmsg` functionality as an external file when linking with older glib libraries?

**Comment by thhous-msft** [comment]
Right now now sendmmsg is a requirement. Not something that couldn't be fixed, but 2.14 (which was the first release to have sendmmsg) is 10 years old at this point, so we would need to prioritize it appropriately.

**Comment by thhous-msft** [comment]
One other thing to add is that with older glibc versions you won't have GSO support either. So both features combined missing will result in the largest performance drop, as you only will be able to send a single UDP packet at a time.
