### ISSUE TITLE
Replace Submodules with CMake Build Instructions

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#19]
Instead of submoduling all the possible dependencies of msquic, should we instead use CMake to dynamically grab/build/install what ever is needed for the current build configuration? I think it would improve things. It would definitely improve CI time for configurations that don't need to openssl.

**Comment by AndrewGaspar** [comment]
Consider a package manager like [vcpkg](https://github.com/microsoft/vcpkg).

**Comment by nibanks** [comment]
I've decided to leave things as they are for now and just continue to use submodules.
