### ISSUE TITLE
MsQuicConnection on Linux

### ISSUE THREAD

**Issue by hros** [microsoft/msquic#1912]
`MsQuicConnection depends on `InterlockedIncrement` which is a Windows API
Is there support for Linux/POSIX?

**Comment by thhous-msft** [comment]
The C++ API in msquic.hpp is not part of the public API, and is not maintained. Its only there for test code, where we have shims for InterlockedIncrement on POSIX platforms. If trying to use MsQuic externally the C API is the only public API.
