### ISSUE TITLE
Use of InterlockedIncrement in msquic.hpp

### ISSUE THREAD

**Issue by ran-proshan** [microsoft/msquic#1920]
I am using Ubuntu 20.04 and gcc 9.3.0. 

When I include the header src/inc/msquic.hpp in a project I get an "_‘InterlockedIncrement’ was not declared in this scope_" error (used in line 1032) as it is a WIN API function call. I found no parallel for it in Linux.

Is this by design? 
Am I missing a header possibly?

Thanks.

**Comment by nibanks** [comment]
Duplicate of #1912. Please see the discussion there.
