### ISSUE TITLE
Will ‘SetParamDelegate’ handler in msquic cause si_family missing on macos?

### ISSUE THREAD

**Issue by shuxinqin** [microsoft/msquic#1967]
https://github.com/microsoft/msquic/blob/main/src/inc/msquic_posix.h#L156
https://github.com/microsoft/msquic/blob/main/src/core/connection.c#L5766 msquic handling SetParamDelegate

I see the QUIC_ADDR in msquic_posix.h without ‘si_family’ field, but the corresponding class struct in System.Net.Quic(https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Interop/MsQuicNativeMethods.cs#L610)  include the si_family field,  so I have a question if the following call method will cause the si_family data loss?
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs#L643

**Comment by thhous-msft** [comment]
Because of the FieldOffset in C#, si_family is at the same address as both SOCKADDR fields (That's how to do a union in C#). That works because the first field of both SOCKADDR_IN and SOCKADDR_IN6 are the family field. That field was added by the C# team to make it easier to get to the family field, but the code is correct.

**Comment by shuxinqin** [comment]
I run the System.Net.Quic successful on windows and linux. But it can not run on macos, the exception message is 'Connection has been shutdown by transport. Error Code: 0x0000002F(47)',. So i debug msquic and found the address family was missing when excuting the connect method(https://github.com/microsoft/msquic/blob/main/src/platform/datapath_kqueue.c#L884) and the last errno is 47. The meaning of 47 is ‘Address family not supported by protocol family.’ on macos（https://github.com/apple/swift/blob/main/stdlib/public/Platform/POSIXError.swift#L119）. So I wonder if the si_family is lost when System.Net.Quic excuting the 'SetParamDelegate'?

msquic: v1.7.0
System.Net.Quic: last version

![SOCKET_ERROR](https://user-images.githubusercontent.com/11437679/132611229-a88161e4-4eff-4ac2-9912-397c8c2da3e8.png)

**Comment by thhous-msft** [comment]
Its a union, so there shouldn't be anything causing it to be missing from our end. However, I know .NET doesn't currently do a ton of QUIC testing on macOS, so its possible there is a bug on their end. Its probably worth opening a bug in dotnet/runtime, as from C and C++ we know macOS works.

**Comment by thhous-msft** [comment]
I just did some testing, and yes this is a .NET bug, but not for the reason expected. In macOS, sa_family is _not_ the first field of sockaddr, its actually the 2nd. So this means .NET's mapping of QUIC_ADDR is incorrect. Definitely open an issue in https://github.com/dotnet/runtime

**Comment by shuxinqin** [comment]
Thanks for your reply!

**Comment by thhous-msft** [comment]
Since this is a .NET bug, I'm going to close this on our end, since theres nothing we will be able to do, and the bug is now open on the .NET team.

**Comment by wfurt** [comment]
thanks for looking  @thhous-msft. I'm slowly working towards builds and test automation on macOS
