### ISSUE TITLE
Build against lttng 2.13 fails

### ISSUE THREAD

**Issue by ManickaP** [microsoft/msquic#2026]
After a recent update of lttng-ust from 2.12 to 2.13 it's not possible to build msquic with logging on.
Build error (whole [build.log](https://github.com/dotnet/msquic/files/7219860/build.log) attached):
```
[ 79%] Building CXX object src/tools/attack/CMakeFiles/quicattack.dir/attack.cpp.o
In file included from /usr/include/lttng/ust-utils.h:16,
                 from /usr/include/lttng/ust-tracer.h:14,
                 from /usr/include/lttng/tracepoint.h:21,
                 from /home/manicka/repositories/msquic/src/generated/linux/operation.h.clog.h:10,
                 from /home/manicka/repositories/msquic/src/core/operation.h:9,
                 from /home/manicka/repositories/msquic/src/core/precomp.h:55,
                 from /home/manicka/repositories/msquic/src/tools/attack/attack.cpp:14:
/usr/include/c++/11.1.0/type_traits:56:3: error: template with C linkage
   56 |   template<typename _Tp, _Tp __v>
      |   ^~~~~~~~
In file included from /home/manicka/repositories/msquic/src/tools/attack/attack.cpp:14:
/home/manicka/repositories/msquic/src/core/precomp.h:40:1: note: ‘extern "C"’ linkage started here
   40 | extern "C" {
      | ^~~~~~~~~~
```

Also sharing the lttng header files [lttng-headers.tar.gz](https://github.com/dotnet/msquic/files/7219881/lttng-headers.tar.gz)

I'm not blocked by this, I can downgrade and keep the older version. I just thought this might be something that would need to be solved in the future anyway.

cc: @wfurt

**Comment by nibanks** [comment]
If this is just for .NET, don't build tools/tests. There are CMAKE defines to disable them.

**Comment by thhous-msft** [comment]
Thats slightly annoying. I know the fix for it, its just going to be time consuming. But yeah for now you can disable tools, test and perf and it will only build C code, which will work fine.

**Comment by ManickaP** [comment]
> If this is just for .NET, don't build tools/tests. There are CMAKE defines to disable them.

Awesome, this helped, thanks!

**Comment by thhous-msft** [comment]
@ManickaP this should be fixed now in main. I don't have a way to install 2.13, can you try it out if you still have access to that system?

**Comment by ManickaP** [comment]
>  I don't have a way to install 2.13, can you try it out if you still have access to that system?

It helped, the current main now builds with lttng 2.13. Thanks, that was fast.
