### ISSUE TITLE
Support QuicTLS (OpenSSL) 3.0

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#2039]
### Describe the feature you'd like supported

We need to support the latest version of quictls/openssl (3.0).

### Proposed solution

Move to OpenSSL 3.0

**Comment by wfurt** [comment]
since this is general META issue, I feel we should not close this until we have packages posted the linked issues can consume. Let me know @nibanks if you want to do it otherwise.

**Comment by nibanks** [comment]
Closing this as Fixed.
