### ISSUE TITLE
Docker build failed by forked repository

### ISSUE THREAD

**Issue by ami-GS** [microsoft/msquic#2041]
### Describe the bug

I tried to build Dockerfile using forked repository, but got error when building OpenSSL related part in `cmake --build .`

### Affected OS

- [ ] Windows Server 2022
- [ ] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [X] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### Additional OS information

Ubuntu20.04 on WSL2 on WIndows 10

### MsQuic version

main

### Steps taken to reproduce bug

> git clone https://github.com/ami-GS/msquic
> cd msquic
> sudo docker build .

### Expected behavior

Step 11/23 : RUN     cmake --build .
 ---> Running in 20fbc50190d9
Scanning dependencies of target msquic.lttng
[  1%] Building C object src/generated/CMakeFiles/msquic.lttng.dir/linux/quic.clog_ApiTest.cpp.clog.h.c.o
< skip lines...... >
[ 87%] Linking C static library ../../obj/Release/libcore.a
[ 87%] Built target core
Scanning dependencies of target OpenSSL_Target
[ 87%] OpenSSL configure
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 1.1.1l+quic (0x101010cfL) for linux-x86_64
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

\**********************************************************************
\***                                                                ***
***   OpenSSL has been successfully configured                     ***
\***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
\***                                                                ***
***       perl configdata.pm --dump                                ***
\***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
\***                                                                ***
\**********************************************************************
[ 87%] OpenSSL build
ar: creating apps/libapps.a
ar: creating libcrypto.a
ar: creating libssl.a
created directory `/src/Debug/_deps/opensslquic-build/openssl/lib`
*** Installing runtime libraries
*** Installing development files
created directory `/src/Debug/_deps/opensslquic-build/openssl/include/openssl`
install ../../../../../submodules/openssl/include/openssl/aes.h -> /src/Debug/_deps/opensslquic-build/openssl/include/openssl/aes.h
< skip lines...... >
[ 99%] Building CXX object src/tools/spin/CMakeFiles/spinquic.dir/spinquic.cpp.o
[100%] Linking CXX executable ../../../bin/Release/spinquic
[100%] Built target spinquic
Removing intermediate container 20fbc50190d9
 ---> 203b2c477a1b
< skip lines...... >
Removing intermediate container 2769a1e6c1c8
 ---> ebe2fcd19285
Successfully built ebe2fcd19285

### Actual outcome

Step 11/23 : RUN     cmake --build .
 ---> Running in c7c86427359e
Scanning dependencies of target msquic.lttng
[  1%] Building C object src/generated/CMakeFiles/msquic.lttng.dir/linux/quic.clog_ApiTest.cpp.clog.h.c.o
< skip lines...... >
[ 87%] Linking C static library ../../obj/Release/libcore.a
[ 87%] Built target core
Scanning dependencies of target OpenSSL_Target
[ 87%] OpenSSL configure
/bin/sh: 1: /src/submodules/openssl/config: not found
make[2]: *** [_deps/opensslquic-build/CMakeFiles/OpenSSL_Target.dir/build.make:69: _deps/opensslquic-build/submodules/openssl/Makefile] Error 127
make[1]: *** [CMakeFiles/Makefile2:450: _deps/opensslquic-build/CMakeFiles/OpenSSL_Target.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
The command '/bin/sh -c cmake --build .' returned a non-zero code: 2

**Comment by nibanks** [comment]
Can you make sure you have the submodules checked out too?

**Comment by nibanks** [comment]
Pretty sure your steps should have been:
```shell
git clone --recursive https://github.com/ami-GS/msquic
cd msquic
sudo docker build .
```

**Comment by ami-GS** [comment]
I did not git clone recursive. and works now....
Sorry and thanks🤦‍♂️
