### ISSUE TITLE
Data and SEND_SHUTDOWN won't get sent to the peer

### ISSUE THREAD

**Issue by ManickaP** [microsoft/msquic#2063]
### Describe the bug

This is fairly reproducible in our HTTP/3 stress tests. At around 20 minutes mark (~300 000 requests), a request will fail with timeout. It doesn't seem like we do something wrong, but it still might be our fault. I also collected dump from about 5 seconds after the requests gets stuck and haven't seen anything suspicious in it.

Attached log:
client stream 0x7f18f4010150
server stream 0x7f6b80027090

Request gets send around 02:36:30 and then at 02:36:40 it gets cancelled on a timeout so the streams get shutdown and closed eventually.

This is the filtered msquic.log (full [msquic.log](https://github.com/microsoft/msquic/files/7305310/msquic.log)):
```
  142: [1][7193.71d1][02:36:31.488590][strm][0x7f18f4010150] Received ack for 326 bytes, offset=102, FF=0x0
  143: [1][7193.71d1][02:36:31.488590][strm][0x7f18f4010150] SF:0 FC:32768 QS:428 MAX:428 UNA:428 NXT:428 RECOV:0-0
  146: [1][7193.71d1][02:36:31.488591][strm][0x7f18f4010150] Received ack for 0 bytes, offset=428, FF=0x2
  147: [1][7193.71d1][02:36:31.488592][strm][0x7f18f4010150] Send queue completely drained
  148: [1][7193.71d1][02:36:31.488592][strm][0x7f18f4010150] Send State: 5
  149: [1][7193.71d1][02:36:31.488593][strm][0x7f18f4010150] Indicating QUIC_STREAM_EVENT_SEND_SHUTDOWN_COMPLETE
  150: [1][7193.71d1][02:36:31.488621][strm][0x7f18f4010150] SF:0 FC:32768 QS:428 MAX:428 UNA:428 NXT:428 RECOV:0-0
  168: [8][7137.74ef][02:36:31.488652][ api] Enter 22 (0x7f6b80027090).
  175: [5][7137.716c][02:36:31.488666][strm][0x7f6b80027090] Send Request [0x7f6bc0011080] queued with 398 bytes at offset 6 (flags 0x0)
  176: [5][7137.716c][02:36:31.488667][strm][0x7f6b80027090] Indicating QUIC_STREAM_EVENT_SEND_COMPLETE [0x7f6bc0011080]
  177: [5][7137.716c][02:36:31.488678][strm][0x7f6b80027090] SF:16 FC:32768 QS:404 MAX:0 UNA:0 NXT:0 RECOV:0-0
  181: [9][7137.742d][02:36:31.488793][ api] Enter 21 (0x7f6b80027090).
  188: [1][7137.716c][02:36:31.488807][strm][0x7f6b80027090] Setting flags 0x64 (existing flags: 0x16)
  190: [1][7137.716c][02:36:31.488809][strm][0x7f6b80027090] SF:80 FC:32768 QS:404 MAX:0 UNA:0 NXT:0 RECOV:0-0
  191: [1][7137.716c][02:36:31.488810][strm][0x7f6b80027090] Send State: 4
```

Also I'm running debug build of msquic.

### Affected OS

- [ ] Windows Server 2022
- [ ] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [ ] Ubuntu
- [ ] Debian
- [X] Other (specify below)

### Additional OS information

Arch Linux kernel 5.14
But seeing the same timeout in our stress pipeline - Debian bullseye docker image - as well.

### MsQuic version

main

### Steps taken to reproduce bug

Run dotnet/runtime HTTP/3 [stress](https://github.com/dotnet/runtime/tree/main/src/libraries/System.Net.Http/tests/StressTests/HttpStress) tests for about 20 minutes and you'll see HTTP request failing with timeout.

### Expected behavior

Client to receive the data and SEND_SHUTDOWN from the server.

### Actual outcome

It seems like server tries to send the data and shutdown its sending side, but it never gets reported on the client side (no RECEIVE event, no PEER_SEND_SHUTDOWN).

**Comment by nibanks** [comment]
> So I assume that msquic expect the app to drain all data from all streams before it shuts them down and closes them? Even if we abort reads?

No, if you abort the stream receive path, then you don't have to drain the receives.
