### ISSUE TITLE
Interesting "bug" in debug mode

### ISSUE THREAD

**Issue by Wizmann** [microsoft/msquic#2298]
My long running test for MsQuic hits this [assertion error][1]. 

Callstack: (MsQuic 1.9 with my little change)

![image](https://user-images.githubusercontent.com/1270921/149627159-30c1dcf4-ae20-4132-a5ec-bd73dc97b4b9.png)

I checked the `QUIC_SENT_PACKET_METADATA` entry but it doesn't seem like a double free error as all fields are valid.

Further, I viewed the memory of the entry and the first 38 bytes of the entry are:

![image](https://user-images.githubusercontent.com/1270921/149626714-70ea4947-9ce2-4c47-8baf-98ca6306f273.png)

When we interpret the entry with type `QUIC_SENT_PACKET_METADATA`, it's like:

* `struct QUIC_SENT_PACKET_METADATA *Next` = 0x 0000 0229 92F9 1590
* `uint64_t PacketNumber` = 0x 0000 0001 B0C4 242A
* `uint32_t SentTime` = 0x AAAA AAAA 
* (other fields...)

When we interpret the entry with `CXPLAT_POOL_ENTRY`, it's like:
* `SLIST_ENTRY ListHead` = 0x 0000 0229 92F9 1590 + 0x 0000 0001 B0C4 242A (as it marks `DECLSPEC_ALIGN(16)`)
* `uint32_t SpecialFlag` = 0x AAAA AAAA

It means that if the `SentTime` of the packet just equals 2,863,311,530 (0xAAAAAAAA in hex),we will unfortunately trigger the assertion error, which is absolutely unexpected.

----

The struct `QUIC_SENT_PACKET_METADATA` has changed in PR #2045, but when the low bits of `uint64_t PacketNumber` is 0xAAAAAAAA, the problem still exists.

[1]: https://github.com/microsoft/msquic/blob/19c9424ddeebd59838a0607e1eb23ab65f371cb2/src/inc/quic_platform_winuser.h#L332

**Comment by nibanks** [comment]
Interesting. We could always make the special pattern longer to reduce the chances of this, but otherwise there will always be a possibility.

**Comment by Wizmann** [comment]
I can understand the dilemma that:

1. We need a special flag to detect the "double free" bug
2. The value of sepcial flag might equal to value of some user fields, which is inevitable

Appearently, this could add some predictable noise for debugging, which makes no sense and confusing.

As I can't find out another way to solve problem either. I will temporarily disable the check in my code.

**Comment by nibanks** [comment]
Let's start by making it a `uint64_t`. That'd fix your scenario at least, because you're never practically going to get that high in time. Want to make a PR?

**Comment by Wizmann** [comment]
haha, sure.
