### ISSUE TITLE
OpenSSL build has SChannel code path for CxPlatTlsSecConfigCreate

### ISSUE THREAD

**Issue by TYoungSL** [microsoft/msquic#2306]
### Describe the bug

Debugging it I ran into this... This symbol binding is putting me in tls_schannel.c but this is the OpenSSL build.
![image](https://user-images.githubusercontent.com/70316188/149969102-09a28e04-51e6-4a5c-836c-da95193cec19.png)
The loaded msquic.dll module, verifying it's not the one in system or distributed with dotnet:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/70316188/149969185-7d8dbc21-6e6e-46df-a624-25a2189020f8.png">
Verification the module is what it is, the v1.9.0 x64 **OpenSSL** release from github;
<img width="658" alt="image" src="https://user-images.githubusercontent.com/70316188/149969442-bb13b158-70df-440c-9515-15ccc23455e4.png">

Am I doing something wrong?

Why am I arriving [here in tls_schannel.c](https://github.com/microsoft/msquic/blob/v1.9.0/src/platform/tls_schannel.c#L911) instead of [here in
tls_openssl.c](https://github.com/microsoft/msquic/blob/v1.9.0/src/platform/tls_openssl.c#L866) after stepping from the call to CxPlatTlsSecConfigCreate in MsQuicConfigurationLoadCredential?

### Affected OS

- [ ] Windows Server 2022
- [X] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [ ] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

1) Explicitly load the v1.9.0 x64 OpenSSL version of msquic.dll.
2) Call RegistrationOpen to create a registration
3) Call ConfigurationOpen to create a configuration
4) Invoke ConfigurationLoadCredential for a server with a valid config that uses `QUIC_CREDENTIAL_FLAG_USE_TLS_BUILTIN_CERTIFICATE_VALIDATION`.
5) Succeed and end the test or get `QUIC_STATUS_INVALID_PARAMETER` because it's invalid on schannel builds.

### Expected behavior

OpenSSL builds should not be able to take the SChannel code paths.

### Actual outcome

Got `QUIC_STATUS_INVALID_PARAMETER` instead of success (0).

**Comment by thhous-msft** [comment]
Just to double check, are you attempting to use .NET's QUIC wrappers, or your own P/Invoke calls into msquic.dll? This seems more like an issue on the .NET side where its still loading either the schannel PDB's or the schannel binary itself. The openssl binary doesn't have the schannel code in it at all, its not a runtime switch. 

Can you share the full stack trace, including the managed code, and maybe even the project youre attempting to use?

**Comment by TYoungSL** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/70316188/149976314-295fb537-e424-43fc-86a0-b23fd4eee1f3.png">

Yeah. Both were loaded.
