### ISSUE TITLE
Fix Security Warning from sscanf Usage in Posix Code

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#2410]
### Describe the bug

Code scanning warns that the Posix usage of `sscanf` in cgroup.c could be an unbounded write. Not really, but we should fix it to make the tool happy.

### Affected OS

- [ ] All
- [ ] Windows Server 2022
- [ ] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [X] Ubuntu
- [X] Debian
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

Go to https://github.com/microsoft/msquic/security/code-scanning to see the "Unbound write" warnings, such as https://github.com/microsoft/msquic/security/code-scanning/169?query=ref%3Arefs%2Fheads%2Fmain.

### Expected behavior

No warnings should be present

### Actual outcome

The code scanning fears that there might be an unbound write, but it shouldn't be the case considering how we allocate the space. But to make things a little safer, I think we should update the code to do something like the first answer here: https://stackoverflow.com/questions/5873402/is-sscanf-considered-safe-to-use.

**Comment by liveans** [comment]
A pull request has opened for it, but the compiler's `-Werror=format-nonliteral` flag doesn't let it do it in a good way.

**Comment by nibanks** [comment]
Closing this now since there's no easy fix to make it happy and the issue really is a false positive.
