### ISSUE TITLE
CI tests for LoLa builds

### ISSUE THREAD

**Issue by maolson-msft** [microsoft/msquic#2428]
### Describe the feature you'd like supported

We need to enable the existing tests on LoLa builds. Most of them should work, except the ICMP Unreachable test, for which we can make an exception (similar to the exception that exists currently for 2019 tests).

We also need to add tests for network-layer-specific functionality that's been implemented for LoLa, like routing and neighbor resolution. These new tests will also be applicable for QUIC using regular sockets, so there's no need to restrict them to LoLa builds.

### Proposed solution

Currently loopback is used for most tests; for LoLa, we'll need to use duonic instead.

Implementing tests for route and neighbor changes is an open issue and might be significantly harder.

**Comment by nibanks** [comment]
Closing this as Matt already onboarded most things.
