### ISSUE TITLE
Onboard Codecoverage to AZP

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#252]
We should collect code coverage in the Azure Pipeline builds. Some helpful info:

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops

**Comment by anrossi** [comment]
Resolved by #607
