### ISSUE TITLE
StreamReceiveSetEnabled cannot be used to disable a peer started stream upon start

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#2541]
StreamReceiveSetEnabled always delegates to the operation queue, even if running from the worker thread. This means if called from `QUIC_CONNECTION_EVENT_PEER_STREAM_STARTED` to disable stream receive, a receive can happen before the operation can run, making the call pointless. At minimum we need to add this quirk to the documentation, preferably I'd like to fix it.

**Comment by nibanks** [comment]
The best solution without changing any MsQuic code is to simply reject the first receive (drain zero bytes).

**Comment by thhous-msft** [comment]
We fixed the documentation here. I don't think fixing the underlying issue is actually feasable or worth doing.
