### ISSUE TITLE
Advanced client certificate support

### ISSUE THREAD

**Issue by Techwolfy** [microsoft/msquic#2573]
### Describe the feature you'd like supported

MsQuic supports client certificates, but provides few options to configure validation. To bring Windows HTTP/3 client certificate support up to parity with HTTP/1.1, we will need the following features:

1. Support for anonymous client authentication on server-side
2. Support for configuring an arbitrary SecPkgCred_ClientCertPolicy
3. Support for disabling SCH_CRED_NO_SYSTEM_MAPPER
4. Support for querying the security context token post-handshake

### Proposed solution

1. SECPKG_ATTR_CERT_CHECK_RESULT_INPROC will return SEC_E_NO_CREDENTIALS, which causes MsQuic to fail the handshake with CXPLAT_TLS_RESULT_ERROR; we need this to go through the PEER_CERTIFICATE_RECEIVED callback instead. This can be resolved by updating the error check at `/src/platform/tls_schannel.c:2127` to store and ignore the error:

```
if (SecStatus == SEC_E_NO_CREDENTIALS) {
    CertValidationResult.hrVerifyChainStatus = SecStatus;
} else if (SecStatus != SEC_E_OK) {
```

The call to SECPKG_ATTR_REMOTE_CERTIFICATES may fail with SEC_E_NO_CREDENTIALS in this case as well. That error can be ignored.

2. Currently SECPKG_ATTR_CLIENT_CERT_POLICY uses a locally-defined struct supporting configuration of only 3 flags. HTTP.SYS uses every field in that structure, so it's likely more efficient to enable passing a pointer in via SetParam or the QUIC_CREDENTIAL_CONFIG than to add support for each field individually.

3. A new QUIC_CREDENTIAL_FLAG_USE_SYSTEM_MAPPER to control the behavior at `/src/platform/tls_schannel.c:1053` would be sufficient. This is dependent on the prior feature, as use of the system mapper depends on several currently-unsupported fields in SecPkgCred_ClientCertPolicy.

4. A new QUIC_PARAM_TLS_SCHANNEL_CONTEXT_TOKEN GetParam that calls QuerySecurityContextToken on the SChannel context handle would be enough here.

**Comment by nibanks** [comment]
Related to https://github.com/microsoft/msquic/issues/1953.

**Comment by macoxms** [comment]
Per our conversation please also switch from using SECPKG_ATTR_REMOTE_CERTIFICATES to the in-proc version given that the call is always done when the in-proc version is available.

**Comment by macoxms** [comment]
FYI, the in-proc version actually returns a different data set, which while providing more data is not compatible with http.sys server APIs.  So, one way or another http.sys will need to use SECPKG_ATTR_REMOTE_CERTIFICATES.  However, it seems advantageous for your callback to not call the slow version.  http.sys can always call it by itself as long as the call isn't blocked in this path.
The HTTP/3 client already uses the in-proc version directly.

**Comment by Techwolfy** [comment]
We will also need MsQuic flags to enable the CERT_CHAIN_CACHE_ONLY_URL_RETRIEVAL and CERT_CHAIN_REVOCATION_CHECK_CACHE_ONLY certificate chain build flags.
