### ISSUE TITLE
ASSERT, \src\platform\datapath_raw.c:533 - Route->State == RouteResolved.

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#2614]
### Describe the bug

We've seen this assert hit a couple times now. The Nth alloc test hits it occasionally ([quic.log](https://github.com/microsoft/msquic/files/8428730/quic.log)). It seems there are some code paths where the route isn't correctly resolved first.

### Affected OS

- [ ] All
- [X] Windows Server 2022
- [X] Windows 11
- [X] Windows Insider Preview (specify affected build below)
- [ ] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

Run MsQuic with XDP.

### Expected behavior

No asserts

### Actual outcome

Hits an assert.

**Comment by maolson-msft** [comment]
Fixed by PR 2618
