### ISSUE TITLE
Need to add a memory barrier in `MsQuicAddRef` before checking MsQuicLib is loaded

### ISSUE THREAD

**Issue by Wizmann** [microsoft/msquic#2641]
Suppose we have 2 threads call `MsQuicOpenVersion` at the same time with `MsQuicLib.Loaded = FALSE;`.

Thread1 called `MsQuicLibraryLoad` successfully and set `MsQuicLib.LoadRefCount = 1` and `MsQuicLib.Loaded = TRUE`, while Thread2 is shorted.

After that Thread2 will probably return `QUIC_STATUS_INVALID_STATE` in `MsQuicAddRef` because it read a cached `MsQuicLib.Loaded==FALSE`.

As a result, Thread2 will trigger the `CXPLAT_FRE_ASSERT(MsQuicLib.Loaded);` assertion error in function `MsQuicLibraryUnload`, but the value of `MsQuicLib.LoadRefCount` is 2.

Code is running on x64 platform.

Please have a look at this problem.

**Comment by nibanks** [comment]
If you are dynamically linking the library, then the dll load function will also call `MsQuicLibraryLoad` and not call `MsQuicLibraryUnload` until the library is being unloaded. So in that case, there is no issue.

If you are statically linking the library, we made a conscious design choice to restrict static linking callers to require them to do synchronization. Static linking means you're not sharing the library with any other caller, and do not have to worry about racing calls with code outside your control, so you have the ability to ensure no parallel calls are made.

**Comment by Wizmann** [comment]
Yes, we're statically linking MsQuic to our APP.

But according to the doc, there's no explict restriction to stop us from calling `MsQuicOpenVersion` in parallel. And I see some synchronization code in `library.c`, seems like MsQuic is aware of the problem, but not 100% avoid it yet.

**Comment by nibanks** [comment]
Yes, you are correct that we do not document this restriction. We should do that, but otherwise, I don't believe we should complicate the code inside MsQuic for this scenario. I can definitely use this issue to update the documentation.

**Comment by Wizmann** [comment]
OK.

Maybe you can also add this: "it's safe for different to share `QuicApi` among connections on different threads".

**Comment by Wizmann** [comment]
One more question, do you think it's necessary to create a `QuicApi` instance for each NUMA node?

**Comment by nibanks** [comment]
> One more question, do you think it's necessary to create a `QuicApi` instance for each NUMA node?

No. Just one is all you need.
