### ISSUE TITLE
Disable Quic encryption

### ISSUE THREAD

**Issue by Yafeng1991** [microsoft/msquic#2651]
### Describe the bug

Hello experts,

I'm trying to check if MSQuic can work without packets encryption/decryption, then i found someting seems suitable like QUIC_PARAM_CONN_DISABLE_1RTT_ENCRYPTION. So I set this param in quicsample (src/tools/sample/sample.c). But it seems not working at all. I still can see encryted packets between client and server.

Below are my changes in sample.c. Did i miss anything ?

In RunClient() function:

`

    /* + test */
    BOOLEAN value = TRUE;
    Status =
        MsQuic->SetParam(
                Connection,
                QUIC_PARAM_CONN_DISABLE_1RTT_ENCRYPTION,
                sizeof(value),
                &value);
    /* - test */

    if ((ResumptionTicketString = GetValue(argc, argv, "ticket")) != NULL) {
        //
        // If provided at the command line, set the resumption ticket that can
        // be used to resume a previous session.
        //
        uint8_t ResumptionTicket[1024];
        uint16_t TicketLength = (uint16_t)DecodeHexBuffer(ResumptionTicketString, sizeof(ResumptionTicket), ResumptionTicket);
        if (QUIC_FAILED(Status = MsQuic->SetParam(Connection, QUIC_PARAM_CONN_RESUMPTION_TICKET, TicketLength, ResumptionTicket))) {
            printf("SetParam(QUIC_PARAM_CONN_RESUMPTION_TICKET) failed, 0x%x!\n", Status);
            goto Error;
        }
    }

`

In ServerListenerCallback() function: 

`

    /* + test */
    BOOLEAN value = TRUE;
    /* - test */

    UNREFERENCED_PARAMETER(Listener);
    UNREFERENCED_PARAMETER(Context);
    QUIC_STATUS Status = QUIC_STATUS_NOT_SUPPORTED;
    switch (Event->Type) {
    case QUIC_LISTENER_EVENT_NEW_CONNECTION:
        /* + test */
        MsQuic->SetParam(
                Event->NEW_CONNECTION.Connection,
                QUIC_PARAM_CONN_DISABLE_1RTT_ENCRYPTION,
                sizeof(value),
                &value);
        /* - test */
        //
        // A new connection is being attempted by a client. For the handshake to
        // proceed, the server must provide a configuration for QUIC to use. The
        // app MUST set the callback handler before returning.
        //
        MsQuic->SetCallbackHandler(Event->NEW_CONNECTION.Connection, (void*)ServerConnectionCallback, NULL);
        Status = MsQuic->ConnectionSetConfiguration(Event->NEW_CONNECTION.Connection, Configuration);

`

Thanks.

### Affected OS

- [ ] All
- [ ] Windows Server 2022
- [ ] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [X] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### MsQuic version

release/2.0

### Steps taken to reproduce bug

1. Change sample.c to set QUIC_PARAM_CONN_DISABLE_1RTT_ENCRYPTION
2. Run quicsample client and server
./quicsample -server -cert_file:cacert.pem -key_file:privkey.pem  
./quicsample -client -target:127.0.0.1 -unsecure

### Expected behavior

The packets should NOT be encryted any more.

### Actual outcome

The packets are still encrytped somehow.

**Comment by nibanks** [comment]
How are you validating that 1-RTT encryption is being disabled or not? Also, this doesn't disable encryption for the QUIC handshake (long header packets).

**Comment by Yafeng1991** [comment]
<img width="567" alt="disable_1rtt_encryption" src="https://user-images.githubusercontent.com/44762963/164705759-8e602548-11c6-4657-877d-58833d1ed19e.PNG">

I noticed this in Client-Hello after setting QUIC_PARAM_CONN_DISABLE_1RTT_ENCRYPTION.

**Comment by nibanks** [comment]
Wireshark doesn't understand/support this extension, so it will never show up as unencrypted in Wireshark.

**Comment by Yafeng1991** [comment]
I find this in crypto_tls.c, so i guess it's not supported ? I'm using release/2.0 version.

#define QUIC_TP_ID_DISABLE_1RTT_ENCRYPTION                  **0xBAAD**          // N/A

**Comment by nibanks** [comment]
No, it's supported by MsQuic. If you can grab our logs of a repro, it will say whether the extension was negotiated or not. https://github.com/microsoft/msquic/blob/main/docs/Diagnostics.md#trace-collection

**Comment by qzhuyan** [comment]
Just found this, looks like it is driven by Msquic. 
https://tools.ietf.org/id/draft-banks-quic-disable-encryption-00.html

 just curious to know are you pushing this to happen,  becoming standard?

**Comment by Yafeng1991** [comment]
> No, it's supported by MsQuic. If you can grab our logs of a repro, it will say whether the extension was negotiated or not. https://github.com/microsoft/msquic/blob/main/docs/Diagnostics.md#trace-collection

Thanks Nick. I can see "disable-1RTT-encryption" is negotiated from logs.

**Comment by Karthikdasari0423** [comment]
@Yafeng1991 Can you share me the compiled binary which you are using
