### ISSUE TITLE
Duplicate Packet KPI value is mismatching from captured wireshark.

### ISSUE THREAD

**Issue by Testing18** [microsoft/msquic#2661]
### Describe the bug

Duplicate Packet KPI value is mismatching from captured wireshark.

### Affected OS

- [ ] All
- [ ] Windows Server 2022
- [ ] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [ ] Ubuntu
- [ ] Debian
- [X] Other (specify below)

### Additional OS information

CentOS Linux release 8.4.2105

### MsQuic version

release/1.1

### Steps taken to reproduce bug

Steps to setup environment:
1.	We have configured Server and Client in different linux machines.
2.	We have introduced delay on both server and client machines using tc tool to replicate duplicate packets as below command:
a.	tc qdisc add dev enp0s1 root netem delay 500ms duplicate 30%
3.	We have started the Server and then Client, so it will be downloading data with 100k bytes from Server.
4.	Once the test at client side is completed below is the QUIC statistic KPI’s.
 ![image](https://user-images.githubusercontent.com/42167438/165503039-e785fbf1-e866-498d-83a0-e5b8c743cd06.png)
5.	Please find the captured pcap file and sslkeylog file are attached in the below:
            
[client_dup_mismatch_pcap.zip](https://github.com/microsoft/msquic/files/8571370/client_dup_mismatch_pcap.zip)

[sslkeylogfile.txt](https://github.com/microsoft/msquic/files/8571352/sslkeylogfile.txt)

Steps to Validate Duplicate Packet KPI:
1.	Captured the wireshark packets for QUIC protocol and loaded sshkeylog file and we are able to see the packets are decrypted.
2.	Once we opened the wireshak captured file and filtered the packets with “quic && ip.dst==10.182.21.30”, the ip address is from the client machine.
3.	Added the Packet Number column to identify the duplicate packets.
![image](https://user-images.githubusercontent.com/42167438/165503446-d029c74f-ba61-4b68-a281-d927e0da7a73.png)
 
4.	We have copied all the packets and pasted in the XL sheet to filter and identify the duplicate packets and the count as well.
 
![image](https://user-images.githubusercontent.com/42167438/165503474-0acb127c-7301-4192-9caf-f470379b89d1.png)

5.	Select the G Column and added duplicate values formula from **Home -> Conditional Formatting -> Highlighted Cell Rules -> Duplicate Values**.
![image](https://user-images.githubusercontent.com/42167438/165503515-fefda091-46ca-415e-894c-6571ee2a0bf6.png)

6.	Apply filter for G column and select the sort by color
![image](https://user-images.githubusercontent.com/42167438/165503594-dbde47a8-d398-461b-88d9-0562c60d8a31.png)
![image](https://user-images.githubusercontent.com/42167438/165503619-4112b4b5-b04e-4fc7-b4f4-8bfd328ee4c6.png)

7.	Remove the duplicates or get unique values from the duplicate selection and count of the value and match with output result.
Note: Please ignore the last record from the duplicate list as per code.
![image](https://user-images.githubusercontent.com/42167438/165503637-8ef204e7-93e2-439a-b02d-3af31e83d24c.png)
![image](https://user-images.githubusercontent.com/42167438/165503645-092259cf-3cae-4027-b118-fc4d6ffc31fb.png)

8.	Duplicate in quic statistics = 61 while in pcap it shows 60 after ignoring last values, so there is mismatch in duplicate packets in value.

### Expected behavior

The duplicate_packets KPI for client should match from the wireshark.

### Actual outcome

Validation of duplicate_packets KPI value from CLI to wireshark is mismatching.

### Additional details

Actually we have used 1.9 MSQuic version. Please let me know if you need additional information.

**Comment by nibanks** [comment]
Seems like a duplicate issue that we fixed in the latest builds. I'll see about finding the issue number to reference.

**Comment by nibanks** [comment]
Fixed by https://github.com/microsoft/msquic/pull/2612.
