### ISSUE TITLE
MsQuicStreamSend may return QUIC_STATUS_ABORTED before indicating corresponding event.

### ISSUE THREAD

**Issue by rzikm** [microsoft/msquic#2727]
### Describe the bug

When processing incoming `CONNECTION_CLOSE` or `STOP_SENDING` frames, MsQuic sets particular flags on the corresponding objects (`Connection->State.ClosedRemotely` or `Stream->Flags.ReceivedStopSending`). While setting the flag is immediately followed by indicating the corresponding event, there is a brief window of time where calls to `MsQuicStreamSend` may return `QUIC_STATUS_ABORTED` while the reason (or the error code) wasn't yet indicated.

This makes it difficult for applications to reliably report the failure to send data (e.g. via exceptions). Consider following pseudo-code:

```cs
long connectionErrorCode = -1; // set when `QUIC_CONNECTION_EVENT_SHUTDOWN_INITIATED_BY_*` event is indicated
long streamWriteErrorCode = -1; // set when `QUIC_STREAM_EVENT_PEER_RECEIVE_ABORTED` event is indicated

void Send(data)
{
    // check before we even attempt the actual send.
    if (connectionErrorCode != -1) throw ConnectionAbortedException(connectionErrorCode);
    if (streamWriteErrorCode != -1) throw StreamAbortedException(streamWriteErrorCode);

    // now MsQuic thread starts to process incoming CONNECTION_CLOSE or STOP_SENDING

    var status = MsQuicStreamSend(Stream, data, ....);

    if (status == QUIC_STATUS_ABORTED) // just got aborted
    {
        // now we are racing with the MsQuic processing thread and can only hope that the event was indicated in time
        // or we need to spin/block on some synchronization primitive until the actual event is signalled.
        if (connectionErrorCode != -1) throw ConnectionAbortedException(connectionErrorCode);
        throw StreamAbortedException(streamWriteErrorCode);
    }
}

```

### Affected OS

- [ ] All
- [ ] Windows Server 2022
- [X] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [X] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

We have functional tests which when run in a tight loop sometimes produce weird behavior due to the race, but we don't have a single simple repro, sorry.

### Expected behavior

No data race between `MsQuicStreamSend` and background MsQuic thread. I.e. the function returns ABORTED only if the abort was previously signaled in an event.

### Actual outcome

data race, see description.

**Comment by nibanks** [comment]
My initial thoughts on this. Instead of forcing additional synchronization (and taking a perf hit from it), somehow return/expose the necessary state/status when `StreamSend` fails.

**Comment by nibanks** [comment]
This might consist of a new `GetParam` parameter you can call to query the error.

**Comment by rzikm** [comment]
What about postponing setting of `Connection->State.ClosedRemotely` and `Stream->Flags.ReceivedStopSending` after the event has been signalled? I think that would solve the problem. Or would it break something else?

**Comment by nibanks** [comment]
Per recent email exchange, this is no longer required by .NET. I would prefer not to make any changes here, as it might increase contention or cause a (hopefully minor) breaking behavior change; if it's possible at all. So I am closing this with no further action. Please let us know if this comes back as a requirement.
