### ISSUE TITLE
Improve Schannel certificate retrieval speed

### ISSUE THREAD

**Issue by anrossi** [microsoft/msquic#2750]
### Describe the feature you'd like supported

Replace the existing call to `SECPKG_ATTR_REMOTE_CERTIFICATES` with the faster in-proc version. Update the portable certificates code to parse this new structure.

### Proposed solution

See above.

### Additional context

This is a breaking change since the platform-dependent data structure in the `PEER_CERTIFICATE_RECEIVED` event will change.
Splitting this out from #2573 because it's more work and the breaking change aspect is risky.

**Comment by nibanks** [comment]
We could wrap the behavior change in a new flag that must be passed down from the app.

**Comment by anrossi** [comment]
Matthew suggested the new behavior be the default because it's faster. Forcing callers to opt-in to the new behavior kind of kills the benefit.

**Comment by nibanks** [comment]
I'm not suggesting a new API call. I'm suggesting a new configuration flag that changes the default behavior. The speed will be unchanged.
