### ISSUE TITLE
Possibly incorrect comparison of MaxWorkerQueueDelayUs in QuicLossDetectionComputeProbeTimeout

### ISSUE THREAD

**Issue by GaneshRapolu** [microsoft/msquic#2767]
See https://github.com/microsoft/msquic/blob/1bb201f271597917ecfade64630ed6de39e09e64/src/core/loss_detection.c#L237

Should this say

`
    if (Pto > Connection->Settings.MaxWorkerQueueDelayUs) {
        Pto = Connection->Settings.MaxWorkerQueueDelayUs;
    }
`

instead of the current code which is

`
    if (Pto < Connection->Settings.MaxWorkerQueueDelayUs) {
        Pto = Connection->Settings.MaxWorkerQueueDelayUs;
    }
`

**Comment by nibanks** [comment]
Thanks for brining up, but the code is correct as is. `Pto` is expected to get fairly large, especially after multiple retransmits. `MaxWorkerQueueDelayUs` is generally smaller, and meant to provide a **lower** bounds for `Pto`.

**Comment by GaneshRapolu** [comment]
Ah thanks for the quick response; think it might be helpful for future readers if you add

"Pto is expected to get fairly large, especially after multiple retransmits. MaxWorkerQueueDelayUs is generally smaller, and meant to provide a lower bounds for Pto" as a comment in the code.
