### ISSUE TITLE
GetParam for QUIC_PARAM_GLOBAL_TEST_DATAPATH_HOOKS, QUIC_PARAM_GLOBAL_ALLOC_FAIL_DENOMINATOR and QUIC_PARAM_GLOBAL_ALLOC_FAIL_CYCLE

### ISSUE THREAD

**Issue by ami-GS** [microsoft/msquic#2779]
### Describe the feature you'd like supported

QUIC_PARAM_GLOBAL_TEST_DATAPATH_HOOKS, QUIC_PARAM_GLOBAL_ALLOC_FAIL_DENOMINATOR and QUIC_PARAM_GLOBAL_ALLOC_FAIL_CYCLE can be used only for SetParam, but GetParam is not supported.

### Proposed solution

Write them in QuicLibraryGetGlobalParam, but is there any reason why these have not been there?

### Additional context

Wanted to use TestHelpers.h::GlobalSettingScope for these three parameter #2774

**Comment by nibanks** [comment]
These are test-only hooks, used to help us test other parts of the code effectively. We don't need to do anything extra for these.
