### ISSUE TITLE
Assert in CxPlatDpRawPlumbRulesOnSocket

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#2793]
### Describe the bug

Found from the latest main run of the CI. We're hitting a debug assert (but would crash on the following line if wasn't there) here:
```c
            } else {
                CXPLAT_DBG_ASSERT(Rule);    <========
                CxPlatDpRawClearPortBit(
                    Rule->Pattern.IpPortSet.PortSet.PortSet, Socket->LocalAddress.Ipv4.sin_port);
```
This seems to indicate that we failed to find a matching rule to delete.
```
0:011> k
 # Child-SP          RetAddr           Call Site
...
0c 000000fa`b11fe480 00007ffd`17748303 ntdll!KiUserExceptionDispatch+0x2e [minkernel\ntos\rtl\amd64\trampoln.asm @ 751] 
0d 000000fa`b11ff1d0 00007ffd`1773c946 msquic!CxPlatDpRawPlumbRulesOnSocket+0x713 [D:\a\1\msquic\src\platform\datapath_raw_xdp.c @ 1295] 
0e 000000fa`b11ff420 00007ffd`176cf016 msquic!CxPlatSocketDelete+0x16 [D:\a\1\msquic\src\platform\datapath_raw.c @ 471] 
0f 000000fa`b11ff450 00007ffd`176c378e msquic!QuicBindingUninitialize+0x106 [D:\a\1\msquic\src\core\binding.c @ 210] 
10 000000fa`b11ff4c0 00007ffd`176e1a50 msquic!QuicLibraryReleaseBinding+0x17e [D:\a\1\msquic\src\core\library.c @ 1977] 
11 000000fa`b11ff5c0 00007ffd`176d35bb msquic!QuicConnFree+0x5f0 [D:\a\1\msquic\src\core\connection.c @ 374] 
12 000000fa`b11ff660 00007ffd`17700e0d msquic!QuicConnRelease+0x24b [D:\a\1\msquic\src\core\connection.h @ 1005] 
13 000000fa`b11ff6c0 00007ffd`176ffafd msquic!QuicWorkerProcessConnection+0x64d [D:\a\1\msquic\src\core\worker.c @ 569] 
14 000000fa`b11ff820 00007ffd`17750b5e msquic!QuicWorkerLoop+0x15d [D:\a\1\msquic\src\core\worker.c @ 671] 
15 000000fa`b11ff880 00007ffd`177508bb msquic!CxPlatRunExecutionContexts+0xbe [D:\a\1\msquic\src\platform\platform_worker.c @ 231] 
16 000000fa`b11ff8d0 00007ffd`533d4ed0 msquic!CxPlatWorkerThread+0x14b [D:\a\1\msquic\src\platform\platform_worker.c @ 267] 
17 000000fa`b11ffa90 00007ffd`53e2e39b kernel32!BaseThreadInitThunk+0x10 [clientcore\base\win32\client\thread.c @ 75] 
18 000000fa`b11ffac0 00000000`00000000 ntdll!RtlUserThreadStart+0x2b [minkernel\ntdll\rtlstrt.c @ 1152] 
```
I'm not sure, but I think we should just silently ignore missing rules to be removed. But we should double check the logic first.

### Affected OS

- [ ] All
- [X] Windows Server 2022
- [ ] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [ ] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

Run spinquic on Windows+XDP.

### Expected behavior

No crash

### Actual outcome

Assert/crash occur.

### Additional details

[spinquic.exe.5384.zip](https://github.com/microsoft/msquic/files/8840133/spinquic.exe.5384.zip)

**Comment by csujedihy** [comment]
I will take a look. The assert is there because we never really remove the port set rule once added. It's unexpected that assert will ever get hit.

**Comment by csujedihy** [comment]
@nibanks does spinquic exercise memory allocation failures?

**Comment by csujedihy** [comment]
Ok it does exercise memory alloc failures. So, very likely the allocation of the new rule failed in the first place and then rule look-up couldn't find anything and then hit the assert.
