### ISSUE TITLE
Better control on ACK Frequency Reduction

### ISSUE THREAD

**Issue by Fkfijhy** [microsoft/msquic#2823]
### Describe the feature you'd like supported

I would like to select myself the value to use for `PeerPacketTolerance` when sending an ACK_FREQUENCY frame, for performance test purpose. Current behaviour is the use of [this extension](https://datatracker.ietf.org/doc/html/draft-ietf-quic-ack-frequency-01) to adapt the ACK Frequency (or PacketTolerance) when the connection is scheduling limited. However I have no power over the new `PeerPacketTolerance` value.

What I would like is a way to **de-activate the extension** and call the function QuicConnUpdatePeerPacketTolerance with **my value** after the start of the connection. Moreover, as I am working with the Rust API with @Sparika, I would like to have access to this function through the API.

### Proposed solution

Benefits for having this feature is a more controllable use of the ACK Frequency parameter to evaluate the performance gain with few different values. For example, [this draft](https://datatracker.ietf.org/doc/html/draft-fairhurst-quic-ack-scaling-04) motivates an increase in the ratio of ACK packets to data packets from 1:2 to 1:10 for QUIC flows. Currently, the extension sets its value to 1:45 which seems large in case of loss on the connection (actually one of the use case of QUIC over TCP).

### Additional context

Currently working with @Sparika on a Rust QUIC performance test prototype with a simple client/server implementation, I evaluate the impact of some QUIC parameters (such as encryption or ACK Frequency) on CPU usage and performance. We plan to introduce network disturbance in the future in order to evaluate robustness of the protocol.

**Comment by nibanks** [comment]
While I understand the desire to play around with this value for testing, I don't agree that ultimately the app should ever be in control of this parameter. IMHO, MsQuic should have the necessary logic to pick the right value. I agree the current logic could be improved upon, especially in the cases of not being CPU-limited.

My preference, if you want to experiment in this area, would be to modify MsQuic internals to try out different logic to tweak this parameter.

**Comment by Fkfijhy** [comment]
Thanks for your very quick feedback ! I will let you know if our performance experiments show interesting results.

**Comment by nibanks** [comment]
I am going to close this issue since I don't plan on exposing anything here to the app. Please reopen if you need anything. Thanks!
