### ISSUE TITLE
Build error when commenting out `QUIC_API_ENABLE_PREVIEW_FEATURES` macro in `precomp.h`

### ISSUE THREAD

**Issue by Wizmann** [microsoft/msquic#2858]
`precomp.h` is a common header for many msquic source files. In the latest main branch, the macro `QUIC_API_ENABLE_PREVIEW_FEATURES` flag is set by default.

However, commenting out `QUIC_API_ENABLE_PREVIEW_FEATURES` macro will lead to a compile error as `struct QUIC_VERSION_SETTINGS` is missing.

It means that `QUIC_API_ENABLE_PREVIEW_FEATURES` flag is useless because we can't really turn that off.

Is that expected?

**Comment by nibanks** [comment]
The `QUIC_API_ENABLE_PREVIEW_FEATURES` flag is only configurable (off by default) for external application code. While the features is covers are experimental, they are always compiled into the core library. It's then an app build-time decision to enable that flag for their code, so they can decide if they want to use these features.

**Comment by Wizmann** [comment]
So the preview features is only turned off for the interfaces.
And on the binary level (.dll / .lib), the features and new fields (e.g. `QUIC_VERSION_SETTINGS`) are still there but never be used.

Is that ture?

**Comment by nibanks** [comment]
Yes

**Comment by Wizmann** [comment]
I was thinking about eliminating the newly added field for BBR with the "preview features" flag...
It looks like not a feasible way here.

**Comment by janksenhu** [comment]
append 
i find the code like scripts/generate-dotnet.ps1:42:    "-D QUIC_API_ENABLE_PREVIEW_FEATURES" # Enable preview features to be generated

if compile with cmake , no need pass any option like cmake -DQUIC_API_ENABLE_PREVIEW_FEATURES=XXXX right?

thanks

**Comment by nibanks** [comment]
The library automatically build with preview features enabled. It's then just to the apps to decide if they want to try them out, they have to set the flag.
