### ISSUE TITLE
How to issue an "immediate graceful shutdown" for a QUIC stream?

### ISSUE THREAD

**Issue by Wizmann** [microsoft/msquic#2874]
As it described in the doc of `closesocket` function for winsock TCP ([link][1]):

>  However, any data queued for transmission will be sent, if possible, before the underlying socket is closed. This is also called a graceful disconnect or close. In this case, the Windows Sockets provider cannot release the socket and other resources for an arbitrary period, thus affecting applications that expect to use all available sockets. This is the default behavior for a socket.

This seems like a combination of `QUIC_STREAM_SHUTDOWN_FLAG_IMMEDIATE` and `QUIC_STREAM_SHUTDOWN_FLAG_ABORT`, but adding a grace period to let the queued data to be sent. 

Is that possible for MsQuic immitating the behavoir of TCP? This could lead to some subtle problems when we trying to replace our existing TCP component with MsQuic.

[1]: https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-closesocket

**Comment by nibanks** [comment]
The reason we don't support immediate + graceful is because the peer may still abort. There is a race condition, and we must indicate the necessary events to the app to handle. If we were to support immediate shutdown, then those events would be silently swallowed up and the app wouldn't know. This would result in an unbalanced understanding of the state between client and server.

**Comment by Wizmann** [comment]
I changed the description and sorry for the potential confusion.
It's not "immediate + graceful" for winsock, actually it's a "immediate + grace period + abort" (or name it as "soft abortive close")
I think it's still useful as it's the default behavior of TCP. But I admit it's strange for app layer to rely on the behavior of `closesocket`.

**Comment by nibanks** [comment]
Closing this issue for lack of any more updated. @wizmann feel free to reactivate if needed.
