### ISSUE TITLE
Support for FreeBSD

### ISSUE THREAD

**Issue by scopedog** [microsoft/msquic#2917]
### Describe the feature you'd like supported

I could successfully build msquic cloned yesterday on FreeBSD 13.1-RELEASE.
It may affect other platforms and I haven't checked yet if it really works, but it compiled and output libmsquic.so.2 anyway.

By the way, as I'm not very familiar with cmake, I manually changed build.make, etc so FreeBSD uses 
datapath_kqueue.c not datapath_epoll.c.
FreeBSD is basically similar to Mac OS X and kqueue should be used for event polling.

### Proposed solution

Here is the patch (not very organized though):
[msquic.freebsd.patch.txt](https://github.com/microsoft/msquic/files/9221576/msquic.freebsd.patch.txt)

### Additional context

It will be very helpful for many people if msquic officially supports FreeBSD.

Thank you.

**Comment by nibanks** [comment]
We'd definitely be interested in support for that. Would you be willing to make a PR from your patch? We can let the CI try to run it to see if anything breaks.

**Comment by scopedog** [comment]
Thanks for quic(k) response.
I guess PR means Pull request but am not sure how to do it.
However, I'll try.

**Comment by nibanks** [comment]
If you're unfamiliar with the process, feel free to ask questions here (or on our Discord). You should actually be able to do pretty much everything through the browser itself. You can press `.` (I think) to get an editor and use that to change your files and then go to https://github.com/microsoft/msquic/pulls (or your fork's version) to create the PR.

**Comment by scopedog** [comment]
Well, I did... Hope it will work.

Thanks.
