### ISSUE TITLE
PowerShell Script to Open Dump from Azure Pipelines

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#293]
It's a bit of a pain to manually find and download all of the necessary artifact files for a test crash. It should be doable to make a PowerShell script to use the Azure Pipeline REST API to do it automatically.

https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1&viewFallbackFrom=azure-devops

**Comment by ThadHouse** [comment]
Doing some digging, I got a connection, however you can only grab full artifacts (the root). You can't just grab, or even list inner files. This can be implemented fairly easily, and then the parsing of folders and files could happen on the client side pretty easily as well.

**Comment by nibanks** [comment]
Cool. Does it pull down all the raw fails or a zip of them?

**Comment by ThadHouse** [comment]
It's a zip of all of them.

**Comment by Jayadiman** [comment]
Good

**Comment by nibanks** [comment]
Still need the ability to open the dump file.

**Comment by nibanks** [comment]
We don't see crashes very often any more. I think it's fine just to close this with the current level of support.
