### ISSUE TITLE
published Linux packages do not state dependency on libcrypto.so.1.1 

### ISSUE THREAD

**Issue by wfurt** [microsoft/msquic#2975]
### Describe the bug

This is related to https://github.com/dotnet/arcade/issues/10253
libmsquic package was installed on .NET test queues but tests dir not run successfully. 
After some investigation I found there are missing dependencies:
```
toweinfu@toweinfu-u22:~$ ldd /usr/lib/x86_64-linux-gnu/libmsquic.so.2.1.0
	linux-vdso.so.1 (0x00007ffd9b1fe000)
	libcrypto.so.1.1 => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd21fcd6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd21fcd1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd21faa9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd21fe32000)
```

It is going to be confusing for users if the package installs but does not work. We should properly claim dependencies so
1) the package would fail to install on old distributions where openssl 1.1 is not available (with possible --no-dpes override)
2) dependencies are installed automatically where available 
 

### Affected OS

- [ ] All
- [ ] Windows Server 2022
- [ ] Windows 11, version 22H2
- [ ] Windows 11, version 21H2
- [ ] Windows Insider Preview (specify affected build below)
- [x] Ubuntu
- [X] Debian
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

apt-get install libmsquic

### Expected behavior

libmsquic is useable

### Actual outcome

libmsquic may miss dependencies

**Comment by wfurt** [comment]
re-opening for RPMs

**Comment by nibanks** [comment]
@wfurt can we close this now? I think we have everything we need, right?

**Comment by wfurt** [comment]
closed with https://github.com/microsoft/msquic/pull/3396.
