### ISSUE TITLE
Windows 11 security reports Trojan:Win32/Mirai!ml for msquic source code.

### ISSUE THREAD

**Issue by SilentHill** [microsoft/msquic#3077]
### Describe the bug

Hi,
I downloaded the main branch zip file of msquic source code.
Windows security reported that it contains trojan.
Emm, I think it is unexpected.
[msquic-main.zip](https://github.com/microsoft/msquic/files/9638754/msquic-main.zip)

Windows Information
Windows Version: Win11 21H2 OS Build 22000.978

Windows Security Information
Antimalware Client Version: 4.18.2207.7
Engine Version:1.1.19600.3
Antivirus Version:1.375.903.0
Antispyware Version:1.375.903.0
![SecurityReport](https://user-images.githubusercontent.com/10977992/192099528-0124974a-7982-4636-baf8-2595d6a66548.png)
![SecurityAbout](https://user-images.githubusercontent.com/10977992/192099531-87da8b3a-117c-41f1-834b-57344ab87075.png)
![Windows11Version](https://user-images.githubusercontent.com/10977992/192099537-2ad902d9-d22d-49a2-ab46-b391b15dd40d.png)

### Affected OS

- [ ] All
- [ ] Windows Server 2022
- [ ] Windows 11, version 22H2
- [ ] Windows 11, version 21H2
- [ ] Windows Insider Preview (specify affected build below)
- [ ] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

Just download the main branch source code

### Expected behavior

No threat report is expected.

### Actual outcome

Windows Security reports threat  - Trojan:Win32/Mirai!ml

**Comment by nibanks** [comment]
I just tried to download from here and Windows didn't complain about a virus to me.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/20663557/192100453-652d6cf3-8a4c-4f0f-b9ee-e52e39612f01.png">

I also ran an explicit scan with no issues.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/20663557/192100501-fadd0072-e817-4ab4-9069-d55b5752bf23.png">

Where is that `Trojan:Win32/Mirai!ml` file coming from?

**Comment by nibanks** [comment]
Closing since we got no response.
