### ISSUE TITLE
Always use UDP (rather than IP) MTU in core code

### ISSUE THREAD

**Issue by maolson-msft** [microsoft/msquic#311]
QuicDataPathBindingGetLocalMtu returns the IP MTU, and in several places in the core code that is mapped to UDP MTU, but in some places it isn't (like in CC, for example, where this is a bug).

Let's change the core code to uniformly use the UDP MTU.

**Comment by nibanks** [comment]
@maolson-msft since you opened the bug, I nominate you for the fix. :)

**Comment by nibanks** [comment]
Closing this as we've gone this long without seeing a need to do this. If someone wishes to propose a PR in the future it'd still be welcome though.
