### ISSUE TITLE
Multiple StreamShutdown cause Null-dereference READ in CxPlatHashtableRemove

### ISSUE THREAD

**Issue by ami-GS** [microsoft/msquic#3205]
### Describe the bug

OSS-Fuzz report
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52792&q=msquic&can=2&sort=-reported
This happens when client calls QuicStreamShutdown multiple times

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

Follow OSS-Fuzz reproduction step

### Expected behavior

SEGV

### Actual outcome

No issue

**Comment by nibanks** [comment]
My initial guess at what is happening here is that spinquic's code that calls `StreamShutdown` in response to the `QUIC_STREAM_EVENT_PEER_SEND_SHUTDOWN` is actually happening after the worker has called `StreamClose`. We likely need to have some code to make sure we haven't already closed the stream (though I'm not immediately sure how best to do that).

**Comment by ami-GS** [comment]
Closed automatically. Maybe false positive
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52792&q=msquic&can=2&sort=-reported
