### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by fofewyoung** [microsoft/msquic#3211]
### Describe the bug

![image](https://user-images.githubusercontent.com/22018091/199691187-26be6325-0a0c-4c85-820e-c9e212bc753c.png)

i start  an appliction that has 1000 msquic clients to  connect  msquic server,  send some bytes,  and close,  connect again and go on...

after a long time 
![image](https://user-images.githubusercontent.com/22018091/199694525-54c3ce70-1134-4319-9307-f4f28b6c2094.png)

the memory diff tool(in vs2019) show  some memory is leaked

### Affected OS

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

windows 10

### MsQuic version

release/2.1

### Steps taken to reproduce bug

no

### Expected behavior

no memeory leak

### Actual outcome

memory is more and more ...

**Comment by nibanks** [comment]
MsQuic uses a pool allocator, also known as a lookaside list, which caches previously allocated items for faster reuse. This is especially important for performance on the data path, such in the callstack you list above. To verify it's not actually a leak, could you please call `MsQuicClose`? All the memory should be freed when you do that.

**Comment by nibanks** [comment]
Yeah, that stuff comes from OpenSSL. They don't free some of their memory until process clean up. But it should be pretty minimal.

**Comment by fofewyoung** [comment]
Yes,  it is pretty minimal.
i will close the issue

**Comment by fofewyoung** [comment]
Today , i did the same Test;  there is another Memory that not freed, below:
![image](https://user-images.githubusercontent.com/22018091/202078193-9c93ceb1-7364-4eff-92b9-4508652e3c48.png)

is this right?

**Comment by nibanks** [comment]
These also use a pool allocator. Additionally, if they're still allocated after cleanup, it's most likely an app bug that didn't close the stream.

**Comment by fofewyoung** [comment]
yeah, i didn't shutdown the stream Explicitly when disconnect;  but i closed the stream when receive QUIC_STREAM_EVENT_SHUTDOWN_COMPLETE 
i am sure i closed the connection,  so i think  QUIC_STREAM_EVENT_SHUTDOWN_COMPLETE  will be received, is it right?

**Comment by fofewyoung** [comment]
i think the streams is belonged to the connection, so  when connection is closed, the stream should be freed.
the test shows most stream is  freed,  some one is not.

**Comment by fofewyoung** [comment]
i reconstruct my code  to sure stream_close is called explicitly, the problem is fixed

**Comment by smartom101** [comment]
> i reconstruct my code to sure stream_close is called explicitly, the problem is fixed

 @fofewyoung  兄弟，能否联系一下237672294@qq.com，请教一些msquic的问题，资料太少了。。。
