### ISSUE TITLE
Cross compile MsQuic and parse params to openssl 

### ISSUE THREAD

**Issue by JaylinYu** [microsoft/msquic#3242]
### Describe the bug

OpenSSL is giving me troubles when cross compile MsQuic for aarch64/arm7hf/arm7el
I searched docs of MsQuic but there is nothing related to a detailed cross-compile procedure. 
So what I did on X86_64_Ubuntu 22.04 is :
"cmake -G Ninja -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc .."
``` "ninja"

then gets:

make[1]: *** Waiting for unfinished jobs....
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-m64'
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-m64'
make[1]: *** [Makefile:663: apps/apps.o] Error 1
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-m64'
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-m64'
make[1]: *** [Makefile:665: apps/bf_prefix.o] Error 1
make[1]: *** [Makefile:669: apps/s_cb.o] Error 1
make[1]: *** [Makefile:667: apps/opt.o] Error 1
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-m64'
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-m64'
make[1]: *** [Makefile:671: apps/s_socket.o] Error 1
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-m64'
make[1]: *** [Makefile:676: crypto/aes/aes_cbc.o] Error 1
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-m64'
make[1]: *** [Makefile:680: crypto/aes/aes_core.o] Error 1
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-m64'
make[1]: *** [Makefile:678: crypto/aes/aes_cfb.o] Error 1
make[1]: *** [Makefile:682: crypto/aes/aes_ecb.o] Error 1

**Comment by JaylinYu** [comment]
This is a common issue for Cross compiling openssl, seems like it is easy to fix this in openssl folder alone.
But is there a easy way to configure it from the top level cmake(only find related information on #433)?  And I have included msquic as one of my submodules, I just don't know how to parse parameters to msquic, and penetrate to OpenSSL...


 


### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

Ubuntu 22.04
target: aarch64

### MsQuic version

release/2.1

### Steps taken to reproduce bug

"cmake -G Ninja -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc .."
"ninja"


### Expected behavior

no errors

### Actual outcome

unrecognized command-line option '-m64'

### Additional details

**Comment by JaylinYu** [comment]
seems like no matter what toolchain I pick on top level cmake, it will automatically change to whatever it detects ...........
Any way to set this manually?

**Comment by ThadHouse** [comment]
You need to pass a toolchain file into cmake. The openssl install should then pick those up. 

https://github.com/microsoft/msquic/tree/main/cmake/toolchains

Theres a few we already have, including arm32 and arm64. You might need to find more for your specific platform, if those are not enough. Passing just CMAKE_C_COMPILER is not enough.

**Comment by JaylinYu** [comment]
Hi Thad, 
Thanks for your hint. I do import some other params but not as complete as the toolchain.cmake from msquic.
But, I still stuck with :
aarch64-linux-gnu-gcc: error: unrecognized command line option ‘-m64’
Other toolchain file is working fine, is this a bug of my aarch64 gcc alone?

**Comment by JaylinYu** [comment]
by parsing -DCMAKE_TARGET_ARCHITECTURE=arm64 solve my last issue
