### ISSUE TITLE
libmsquic package is missing from Microsoft's Ubuntu 22.10 package repository

### ISSUE THREAD

**Issue by alexrp** [microsoft/msquic#3296]
### Describe the bug

It seems that a Ubuntu 22.10 package is missing from the Microsoft package repository.

* 22.04: https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/
* 22.10: https://packages.microsoft.com/ubuntu/20.10/prod/pool/main/

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

Ubuntu 22.10

### MsQuic version

main

### Steps taken to reproduce bug

```
wget https://packages.microsoft.com/config/ubuntu/22.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
sudo apt install libmsquic
```

### Expected behavior

A libmsquic package should be installed.

### Actual outcome

libmsquic is not present in the repository.

### Additional details

(Not sure if this is actually the right repo to post this on.)

**Comment by nibanks** [comment]
Thanks! We'll look into adding it!

**Comment by alexrp** [comment]
Hmm, 2.2 seems to be a few months out judging by the milestone due date, and MsQuic is needed to run .NET 7 apps that use QUIC. In the meantime, is there an 'easy' alternative way to install it on Ubuntu 22.10? (I can obviously build it from source, I'm just not super keen on installing a bunch of build tools on the relevant servers.)

**Comment by wfurt** [comment]
Packages are published in https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/libm/libmsquic/ 
You can probably fetch it form there as it is generally identical binary. 
Any particular reason why you use 22.10 instead of 22.04? 

The caveat is that currently MsQuic needs OpenSSL 1.1 and Ubuntu 22 does not have it. 
You would also need something like:
```
curl -OL http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb &&  sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
```

**Comment by csujedihy** [comment]
@wfurt do we need to publish packages for 22.10? I forgot to add ubuntu 22.10 to the list when I was adding support for fedora 36/37 and mariner2.

**Comment by wfurt** [comment]
.NET does not use 22.10 in CI. so the impact is really on the consumers.
cc: @carnaviire

**Comment by janksenhu** [comment]
compiled on Ubuntu 22.04 LTS (same steps, run success on ubuntu 16.04) quicsample coredump

msquic/build/bin/Release# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
openssl req  -nodes -new -x509  -keyout server.key -out server.cert
gdb quicsample


For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./quicsample...
(No debugging symbols found in ./quicsample)
(gdb) set args -server -cert_file:./server.cert -key_file:./server.key
(gdb) r
Starting program: /home/msquic/build/bin/Release/quicsample -server -cert_file:./server.cert -key_file:./server.key
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff78e3640 (LWP 1738097)]
[New Thread 0x7ffff70e2640 (LWP 1738098)]
[New Thread 0x7ffff68e1640 (LWP 1738099)]
[New Thread 0x7ffff60e0640 (LWP 1738100)]
ListenerStart failed, 0x61!
[Thread 0x7ffff78e3640 (LWP 1738097) exited]
[Thread 0x7ffff70e2640 (LWP 1738098) exited]
[Thread 0x7ffff60e0640 (LWP 1738100) exited]
[Thread 0x7ffff68e1640 (LWP 1738099) exited]
[Inferior 1 (process 1738094) exited normally]
(gdb) bt
No stack.

**Comment by nibanks** [comment]
@csujedihy Did this get fixed with the latest publishing?

**Comment by csujedihy** [comment]
Yes
