### ISSUE TITLE
Faild to load driver on Windows

### ISSUE THREAD

**Issue by ussrhero** [microsoft/msquic#3305]
### Describe the bug

A have failed toload driver on Windows platform because of import 'ksecdd!QueryContextAttributesExW'
It exists in ksecdd.lib, but it there is no such export in ksecdd.sys

If i had commented this code

```C
      //case QUIC_PARAM_TLS_SCHANNEL_CONTEXT_ATTRIBUTE_EX_W: {
        //    if (*BufferLength < sizeof(QUIC_SCHANNEL_CONTEXT_ATTRIBUTE_EX_W)) {
        //        *BufferLength = sizeof(QUIC_SCHANNEL_CONTEXT_ATTRIBUTE_EX_W);
        //        Status = QUIC_STATUS_BUFFER_TOO_SMALL;
        //        break;
        //    }

        //    if (Buffer == NULL) {
        //        Status = QUIC_STATUS_INVALID_PARAMETER;
        //        break;
        //    }

        //    QUIC_SCHANNEL_CONTEXT_ATTRIBUTE_EX_W *ContextAttribute =
        //        (QUIC_SCHANNEL_CONTEXT_ATTRIBUTE_EX_W*)Buffer;

        //    Status =
        //        SecStatusToQuicStatus(
        //        QueryContextAttributesExW(
        //            &TlsContext->SchannelContext,
        //            ContextAttribute->Attribute,
        //            ContextAttribute->Buffer,
        //            ContextAttribute->BufferLength));
        //    break;
        //}
```
the driver began to start normally

### Affected OS

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

Windows 10

### MsQuic version

main

### Steps taken to reproduce bug

Try to start driver build from src/bin/winkernel/

### Expected behavior

The driver should start normally

### Actual outcome

The driver can not  be loaded

**Comment by nibanks** [comment]
I think that function is not available on Win10. The Windows kernel driver for MsQuic isn't meant to be runnable separate from Windows (since it's installed by default).

**Comment by ussrhero** [comment]
Default msquic.sys does not support 2.0 msquic lib version

**Comment by nibanks** [comment]
You cannot change the version of msquic.sys that already ships in Windows, as other components **in** Windows depend on it (HTTP & SMB), and will break/crash if you switch things out from under them. We hope to ship/update msquic v2.1 to Windows Server 2022 in a few months; likely March.

**Comment by ussrhero** [comment]
I might  build my own kernel mode quic client with statically linked msquic lib and dont use the standard driver. But I can not do it because of  QueryContextAttributesExW. In fact, I've rebuild lib with commented QUIC_PARAM_TLS_SCHANNEL_CONTEXT_ATTRIBUTE_EX_W but I'm not sure it will work welll

**Comment by nibanks** [comment]
Just curious, why do you need QUIC in the kernel anyways?

**Comment by ussrhero** [comment]
I want to do a sort of vpn with quic as transport.

**Comment by nibanks** [comment]
I believe @anrossi has been playing around with something similar, but in user mode. You might want to sync with him.

**Comment by anrossi** [comment]
The driver library which provides functions from ksecdd is cng.sys. If you link cng.lib, you should be able to load your driver.
