### ISSUE TITLE
Packaging for Mariner Linux 2.0

### ISSUE THREAD

**Issue by wfurt** [microsoft/msquic#3376]
### Describe the feature you'd like supported

Ability to use MsQuic on Mariner Linux easily.

### Proposed solution

Mariner linux comes with OpenSSL 1.1 and existing binaries should work. It also has signing keys and repo configuration for packages.microsoft.com. But we don't publish package (rpm) there so it is difficult to consume msquic

https://packages.microsoft.com/cbl-mariner/2.0/prod/

Ideally, it should go under Microsoft as it is outside of core OS but provided by Microsoft.

**Comment by nibanks** [comment]
@csujedihy Don't we already build these packages and they just need to be published?

**Comment by wfurt** [comment]
Yes, I think we only miss the publishing @nibanks.

**Comment by csujedihy** [comment]
> @csujedihy Don't we already build these packages and they just need to be published?

Yes, just need to be published. But if they have changed the signature for signing packages for CBL, then we have some work to do.

**Comment by wfurt** [comment]
I don't think it they did @csujedihy. I "borrowed" Centos package in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/779 and it looks ok. I should have results from .NET functional tests in next week or so.

**Comment by csujedihy** [comment]
@wfurt We are publishing packages for mariner 2.0 now.

See https://packages.microsoft.com/cbl-mariner/2.0/prod/Microsoft/x86_64/Packages/l/

**Comment by wfurt** [comment]
thanks. I'll update our test containers accordingly.
