### ISSUE TITLE
Update packages to prevent installation on Debian 12+ and Ubuntu 22.04+

### ISSUE THREAD

**Issue by richlander** [microsoft/msquic#3393]
### Describe the feature you'd like supported

The msquic packages don't work on platforms that exclusively offer OpenSSL 3. It shouldn't be possible to install the msquic .deb packages on those distros.

As you can see, I was able to and had a bad experience: https://github.com/microsoft/msquic/pull/3375#issuecomment-1404471296

### Proposed solution

Do one or more of:

- Add an OpenSSL 1.x package dependency.
- Remove msquic from feeds where it is known to not work.
- Adopt a static linking model.

**Comment by richlander** [comment]
Related to https://github.com/microsoft/msquic/pull/3390

**Comment by wfurt** [comment]
https://github.com/microsoft/msquic/pull/3390 is unrelated e.g. that is build problem. What you describing is essentially dup of  #2975.

**Comment by samsp-msft** [comment]
Doesn't #3392 fix this problem?

**Comment by richlander** [comment]
Kinda. I'm asking why the packages are even in the jammy feed.

**Comment by wfurt** [comment]
It seems like we have internal partners that consume MsQuic on `jammy` so this would break them. They simply worked out the dependency even if disco vendor did not make it easy. 

I would suggest to close this and focus on #2039.

**Comment by richlander** [comment]
Interesting. Sounds good. We should also move #3375 forward.
