### ISSUE TITLE
OpenSSL 3 Linux Build error

### ISSUE THREAD

**Issue by ami-GS** [microsoft/msquic#3426]
### Describe the bug

`$ pwsh ./scripts/build.ps1`
```
....
/bin/sh: 1: /home/daiki/workspace/msquic/submodules/openssl3/config: not found
gmake[2]: *** [_deps/opensslquic-build/CMakeFiles/OpenSSL_Target.dir/build.make:81: _deps/opensslquic-build/submodules/openssl3/Makefile] Error 127
gmake[2]: Leaving directory '/home/daiki/workspace/msquic/build/linux/x64_openssl3'
gmake[1]: *** [CMakeFiles/Makefile2:545: _deps/opensslquic-build/CMakeFiles/OpenSSL_Target.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

pwsh ./scripts/build.ps1

### Expected behavior

finish successfully

### Actual outcome

CMAKE-Execute $Arguments failure by 
....
/bin/sh: 1: /home/daiki/workspace/msquic/submodules/openssl3/config: not found
gmake[2]: *** [_deps/opensslquic-build/CMakeFiles/OpenSSL_Target.dir/build.make:81: _deps/opensslquic-build/submodules/openssl3/Makefile] Error 127
gmake[2]: Leaving directory '/home/daiki/workspace/msquic/build/linux/x64_openssl3'
gmake[1]: *** [CMakeFiles/Makefile2:545: _deps/opensslquic-build/CMakeFiles/OpenSSL_Target.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

### Additional details

_No response_

**Comment by nibanks** [comment]
You need to load submodules. Either via prepare-machine.ps1 or directly via `git`.

**Comment by ami-GS** [comment]
@wfurt 
By the commit https://github.com/microsoft/msquic/commit/289323d8b3882a1c32196db1f012b809463be359, build.ps1 select openssl3, however prepare-machine.ps1 downloads openssl.

**Comment by ManickaP** [comment]
AFAIK, it depends on Ubuntu version. Since 22.04 OpenSSL 3.0 is the default and only OpenSSL installed on the machine. You can pull OpenSSL 1.1 for compat, but it's not there without any extra steps. Similarly for other distributions where newer versions prefer OpenSSL 3.0.

**Comment by ami-GS** [comment]
Thanks for your help!
