### ISSUE TITLE
Remove PowerShell dependency from Unix builds

### ISSUE THREAD

**Issue by am11** [microsoft/msquic#345]
To bring up this project to platforms, where dotnet(1) is not readily available (FreeBSD, NetBSD, SunOS etc.), PowerShell dependency is a huge prerequisite to satisfy. PowerShell itself depends on https://github.com/microsoft/omi/, which further depends on other components that do not yet build on platforms other than Linux/macOS.

Since this repository mainly constitutes C/C++ code, please consider using portable POSIX shell scripts on Unix (or move most of the logic to CMake functions) to make it possible to build anywhere where cmake and compiler toolchains are present.

**Comment by nibanks** [comment]
Thanks for the feedback @am11. While PowerShell is the documented way to build, it's still only used as a helper on top of CMake to actually build. You should be able to directly call cmake if you so wish.
