### ISSUE TITLE
prepare-machine script won't run

### ISSUE THREAD

**Issue by Wiladams** [microsoft/msquic#347]
### Describe the bug
Can't run prepare-machine.ps1 as it's not digitally signed

A description of what the bug is.
I am following the instructions to build msquic on my Windows 10 64-bit machine.  I can not run the first step, which is to run scripts\prepare-machine.ps1.  I get in error message.

.\scripts\prepare-machine.ps1 : File D:\repos\msquic\scripts\prepare-machine.ps1 cannot be loaded. The file
D:\repos\msquic\scripts\prepare-machine.ps1 is not digitally signed. You cannot run this script on the current system.
For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\scripts\prepare-machine.ps1 -Configuration Dev
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

I've run as a regular user (who has administrator privs) as well as "Run as administrator"

### Steps to reproduce the behavior

1. .\scripts\prepare-machine.ps1 -Configuration Dev

2. View output
3. See error

### Expected vs actual behavior
Expected to run to completion.
The build.ps1 script doesn't run either, same error

A description of what you expected to happen and what actually happened.

**Comment by nibanks** [comment]
As the PowerShell output indicates, you're going to have to change your execution policy to run the scripts:

For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.

Also, are you using the [latest PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7) to run this?

**Comment by Wiladams** [comment]
I downloaded the latest powershell.

Given that my environment is pretty basic setup, doesn't it make sense to give more guidance than pointing people at a page that talks about policies in general?

Why not just tell me what I need to set, or why does this need to change at all?

No other software that I compile from GitHub has me go and change a policy just to compile it.  It seems like a barrier to entry that's unnecessary.


-- William
________________________________

**Comment by Wiladams** [comment]
Additionally, I'm not a PowerShell user.  So, reading about policies, although informative, still doesn't tell me exactly what policy these scripts require to run.  And, since I'm not a regular PowerShell user, I don't know the general impact of what I'm doing to change policy, so if I just set it to bypass, is that a good thing or not?  Some guidance on your build instructions would be beneficial.

-- William
________________________________

**Comment by Wiladams** [comment]
After bypassing policies in PowerShell, I'm left with the following
D:\repos\msquic\scripts\prepare-machine.ps1 : A positional parameter cannot be found that accepts argument 'scripts'.
This failure might be caused by applying the default parameter binding. You can disable the default parameter binding
in $PSDefaultParameterValues by setting $PSDefaultParameterValues["Disabled"] to be $true, and retry. The following
default parameter was successfully bound for this cmdlet when the error occurred: -ErrorAction
At line:1 char:1
+ ./scripts/prepare-machine.ps1 -Configuration Dev
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [prepare-machine.ps1], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,prepare-machine.ps1



and if I just ignore all that and try to run the build script, I get the following:

PS D:\repos\msquic> .\scripts\build.ps1
D:\repos\msquic\scripts\build.ps1 : The variable '$IsWindows' cannot be retrieved because it has not been set.
At line:1 char:1
+ .\scripts\build.ps1
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (IsWindows:String) [build.ps1], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined,build.ps1

So, again, it says right there what's wrong '$IsWindows' canno be retrieved.  but, what am I supposed to do about that?  I'm sure I can figure it out, but it's just step by step harder than it should be.  My machine is a typical dev machine with Visual Studio, VS Code, various other tools.  I've never run PowerShell on it before, and did a completely fresh download of the repo.  Maybe your dev boxes have been configured correctly for so long that you've missed the case where a machine is relatively brand new with respect to PowerShell usage?

I'd try this whole flow on a new machine and see what challenges you run into.

**Comment by nibanks** [comment]
@wiladams it sounds like you aren't actually running the new PowerShell. It's a completely separate app from the preinstalled PowerShell.

![image](https://user-images.githubusercontent.com/20663557/80636830-e688f080-8a12-11ea-83b9-6f37e5a5abed.png)

**Comment by nxrighthere** [comment]
@Wiladams You can grab the latest stable release there https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0

You can install it or use as a portable application at your choice.

**Comment by Wiladams** [comment]
I did that and can confirm it worked.  Running the msquictest now.

This was a frustrating process though.  I hope it can improve.  I did have to download latest SDK as well, just for added measure.  Using the .sln files doesn't seem to work for me.  Just more mystery to sort through.

**Comment by nibanks** [comment]
We'll see what we can do about improving the documentation. The .sln files are not for the normal user mode code, and that's why they're not currently documented. CMake is the mechanism for external folks to use the code.
