### ISSUE TITLE
wincrypt on linux

### ISSUE THREAD

**Issue by bentucker** [microsoft/msquic#348]
msquic/src/platform/cert_capi.c:23:10: fatal error: wincrypt.h: No such file or directory
   23 | #include <wincrypt.h>
      |          ^~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/platform/CMakeFiles/platform.dir/build.make:161: src/platform/CMakeFiles/platform.dir/cert_capi.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:497: src/platform/CMakeFiles/platform.dir/all] Error 2
gmake: *** [Makefile:115: all] Error 2
CMake-Execute: msquic/scripts/build.ps1:186
Line |
 186 |      CMake-Execute $Arguments
     |      ~~~~~~~~~~~~~~~~~~~~~~~~
     | [04/29/2020 21:41:13] CMake exited with status code 2

**Comment by nibanks** [comment]
You'll need to set '-Tls openssl' on Linux.

**Comment by bentucker** [comment]
`$ pwsh scripts/build.ps1 -Tls openssl`

seems to work well. Thanks so much for the prompt reply.

This should be added to [BUILD.md](https://github.com/microsoft/msquic/blob/master/docs/BUILD.md#running-a-build)
