### ISSUE TITLE
msquic crashing on Windows (built from current main)

### ISSUE THREAD

**Issue by wfurt** [microsoft/msquic#3484]
### Describe the bug

I recently submit change to use msquic main as our base for .NET test runs. 
We start seeing occasional crashes on Windows platform.

<img width="1721" alt="quic" src="https://user-images.githubusercontent.com/14356188/223563211-ff20073c-c808-4fb0-85bf-fe7eb79baab4.png">

### Affected OS

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

Windos 11 in CI

### MsQuic version

main

### Steps taken to reproduce bug

no clear repro. I tried to run our test suite locally on Windows and I did not get crash. 
It may be timing. IT seems like this is overlapped completion. 

### Expected behavior

msquic should not crash

### Actual outcome

crash on AV. 

### Additional details

https://dev.azure.com/dnceng-public/public/_build/results?buildId=194019&view=ms.vss-test-web.build-test-results-tab&runId=3682560&resultId=209584&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

has link to core dump. I tried to peek at the `SocketProc` but it is optimized out. Somebody with better Windows debugging skills may have better luck. My guess is that the `SockProc->Parent` is null. 

I can also share the core dump if easier. 

cc: @manickap @CarnaViire

**Comment by nibanks** [comment]
Fixed by #3489.
