### ISSUE TITLE
When SetKeepAlive is greater than or equal to SetDestCidUpdateIdleTimeoutMs (while SetIdleTimeoutMs is 0) very high bandwidth bug.

### ISSUE THREAD

**Issue by timprepscius** [microsoft/msquic#3523]
### Describe the bug

When SetKeepAlive is greater than SetDestCidUpdateIdleTimeoutMs (while SetIdleTimeoutMs is 0) very high bandwidth bug.

It is not clear to me whether or not this is a bug in that "this should not happen" or, "this configuration should be invalid" or "this needs to be documented"

Create a server and client.
On both set:
SetKeepAlive = any value greater than or equal to 20,000 (default SetDestCidUpdateIdleTimeoutMs)
SetIdleTimeoutMs = 0 (not sure if this has any affect)
If your SetDestCidUpdateIdleTimeoutMs is somehow not the default, set it to the default, 20,000

On my side I am sending a few messages immediately from client->server-- but I don't think this affects the bug.

After KeepAlive timeout, server and client start sending to each other a lot of bandwidth.  0.5mb a second no my computer.

--branch v2.1.7

### Affected OS

- [ ] Windows
- [X] Linux
- [X] macOS
- [X] Other (specify below)

### Additional OS information

iOS

### MsQuic version

release/2.1

### Steps taken to reproduce bug

See above.

### Expected behavior

See above.

### Actual outcome

See above.

### Additional details

KeepAlive = 19s Idle_0
![KeepAlive_19s_Idle_0](https://user-images.githubusercontent.com/3345382/226329126-4ea4d25d-9051-4498-82a4-47a0a681b3be.png)

KeepAlive = 20s Idle_0
![KeepAlive_20s_Idle_0](https://user-images.githubusercontent.com/3345382/226329153-0587a3ec-d15b-47c4-a3c9-13cc9cb1a5a3.png)

KeepAlive = 20s Idle_0 CIDUpdateTimeout 40s
![KeepAlive_20s_Idle_0_CIDUpdate_40s](https://user-images.githubusercontent.com/3345382/226329265-ec9754a9-b9d4-41dc-8d55-537c28b0a8ec.png)

**Comment by nibanks** [comment]
Would you mind grabbing the logs: https://github.com/microsoft/msquic/blob/main/docs/Diagnostics.md#trace-collection? You'll have to do it on Windows or Linux though.

**Comment by timprepscius** [comment]
Ok, will take a bit though.  Is there a best "simplest" test that I could modify in order to generate the logs?

**Comment by nibanks** [comment]
@timprepscius any updates on logs or a repro?

**Comment by nibanks** [comment]
@timprepscius I'm going to close this until we have more info.
