### ISSUE TITLE
Publish packages for Fedora 36+

### ISSUE THREAD

**Issue by CarnaViire** [microsoft/msquic#3529]
### Describe the feature you'd like supported

Libmsquic package on Fedora is published only for Fedora 34: https://packages.microsoft.com/fedora/34/prod/Packages/l/
Fedora 34 and 35 have already reached EOL; supported releases are 36 and 37, but the package is not available for them: https://packages.microsoft.com/fedora/36/prod/Packages/. Please add the missing packages.

### Proposed solution

Publish the package for Fedora 34+ to include security updates for already published package; starting from 2.2 it can be only published to 36+

/cc @wfurt @ManickaP

**Comment by csujedihy** [comment]
@CarnaViire @wfurt I have added fedora 36/37 and mariner 2.0 to PMC package publish list. If you want, I can run the pipeline to get v2.18 uploaded to these repos and close these 2 issues.

**Comment by csujedihy** [comment]
Just published packages for fedora 36/37 and mariner 2.0. Closing the issues now. Feel free to reopen if you think there's anything missing.
