### ISSUE TITLE
Debug build crashes when active_connection_id_limit transport parameter is 2

### ISSUE THREAD

**Issue by rzikm** [microsoft/msquic#358]
### Describe the bug

The library terminates program due to following assert (send.c, line 662), changing > to >= seems to fix the issue
``` C
                QUIC_DBG_ASSERT(Connection->SourceCidLimit > QUIC_TP_ACTIVE_CONNECTION_ID_LIMIT_MIN);
```
### Steps to reproduce the behavior

I could not find a way to set this parameter in msquic, I ran into this issue when testing interop between msquic and my QUIC implementation, but the repro should be trivial for someone who knows the codebase, just don't send the active_connection_id_limit TP or send default value 2.

### Expected vs actual behavior

Actual: library terminates the application with sigabort
Expected: library does not terminate the application with sigabort :)

**Comment by nibanks** [comment]
Thanks @rzikm for opening the issue! Your analysis of the problem seems correct. I will send out a PR with your proposed fix.
