### ISSUE TITLE
Wrong libmsquic 2.2 package for Ubuntu 22 (and potentially other distros with OpenSSL 3 by default)

### ISSUE THREAD

**Issue by CarnaViire** [microsoft/msquic#3587]
### Describe the bug

MsQuic 2.2 should support OpenSSL 3+, however, the 2.2 package in packages.microsoft.com is still for OpenSSL 1.1:

```
apt-get install -y libmsquic

...

The following packages have unmet dependencies:
 libmsquic : Depends: libssl1.1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

cc @ManickaP @wfurt

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

Ubuntu 22.04 and other distros with OpenSSL 3 by default

### MsQuic version

v2.2

### Steps taken to reproduce bug

```sh
apt-get install -y libmsquic
```

or for specific package

```sh
curl -LO https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/libm/libmsquic/libmsquic_2.2.0_amd64.deb
dpkg -i libmsquic_2.2.0_amd64.deb
```

### Expected behavior

libmsquic (dependent on OpenSSL 3+) installs on the system

### Actual outcome

libmsquic dependent on OpenSSL 1.1 so installation fails:

```
Preparing to unpack libmsquic_2.2.0_amd64.deb ...
Unpacking libmsquic (2.2.0) over (2.2.0) ...
dpkg: dependency problems prevent configuration of libmsquic:
 libmsquic depends on libssl1.1; however:
  Package libssl1.1 is not installed.

dpkg: error processing package libmsquic (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libmsquic
```

**Comment by wfurt** [comment]
Ubuntu 22+ & Debian 12+, Centos 9+ (and perhaps others) should publish packages from the `-tls openssl3` build.

**Comment by CarnaViire** [comment]
@nibanks I think we should reopen to track until there are correct packages in packages.microsoft.com?

**Comment by nibanks** [comment]
Agreed.

**Comment by CarnaViire** [comment]
Packages are published, and I verified that they are successfully consumed in our Ubuntu 22.04 images. Thanks!
Closing.
