### ISSUE TITLE
libmsquic package is missing for Fedora 38

### ISSUE THREAD

**Issue by wfurt** [microsoft/msquic#3610]
### Describe the bug

This is related to https://github.com/microsoft/msquic/issues/3529
It seems like we published only 36 & 37 for 2.2.x
Since this is new release I fell we can only push the latest release.

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

Fedora 38

### MsQuic version

v2.2

### Steps taken to reproduce bug

try to install msquic on Fedora 38 using package manager

### Expected behavior

libmsquic package should be available in https://packages.microsoft.com/fedora/38/prod/Packages/

### Actual outcome

package only exist for 36 & 37

**Comment by wfurt** [comment]
cc: @CarnaViire

**Comment by lbussell** [comment]
@wfurt it looks like these are available now: https://packages.microsoft.com/fedora/38/prod/Packages/l/

**Comment by wfurt** [comment]
I assume this was fixed by https://github.com/microsoft/msquic/pull/3652 and can be closed @csujedihy ?

**Comment by csujedihy** [comment]
@wfurt Yes. That repo is in our publish list now.
