### ISSUE TITLE
Expose the initial client CID

### ISSUE THREAD

**Issue by lucaamblard** [microsoft/msquic#3613]
### Describe the feature you'd like supported

It would be great to be able to access the initial client CID that is shared by both the client and server application.

### Proposed solution

The feature would make it easy to identify which client attempted to connect to a given server. This would help troubleshoot why a client is not being granted access to the server.

**Comment by nibanks** [comment]
Hey @lucaamblard, we'll take a look as soon as we can, though this should be pretty easy to add. Here's what needs to be changed:

## Walkthrough

1. Add a new `GetParam` parameter for the connection to query the original client destination CID.
2. Update `QuicConnGetParam` to support the new parameter.
3. Return the value of `Connection->OrigDestCID` in the handler.
4. Add some tests to validate it works
