### ISSUE TITLE
Official Linux Packages aren't Being Built with numa.h

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#3619]
### Describe the bug

```
Setting up libmsquic (2.2.1) ...
furt@ubu20:~/github/msquic/src$ ldd /usr/lib/x86_64-linux-gnu/libmsquic.so.2
    linux-vdso.so.1 (0x00007ffebc393000)
    libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f24730ef000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f24730e9000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f24730c6000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2472ed4000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f2473539000)
```
@wfurt pointed out that our 2.2.1 packages don't actually have the libnuma dependency and I just checked [our build pipeline](https://mscodehub.visualstudio.com/msquic/_build/results?buildId=365093&view=logs&j=e9a1f452-7fc9-5a13-1cb6-a1ca2e953631&t=d304c971-adb6-5780-23b0-beb86ffc0df5) and I see:
```
-- Found libnuma: /usr/lib/x86_64-linux-gnu/libnuma.so.1
-- numa.h not found. If build fails, install libnuma-dev
```
I don't know why it can find `libnuma.so` but not `numa.h`. We build the docker container with `libnuma-dev` installed, so it _should_ have everything we need, but apparently it doesn't?

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

v2.2

### Steps taken to reproduce bug

Run official Linux builds

### Expected behavior

Depends on libnuma

### Actual outcome

No libnuma dependency because it wasn't fully available at build time.

**Comment by csujedihy** [comment]
It's been fixed by #3620.

```
jedihy@HUANYI-DEV ~> ldd libmsquic.so.2.3.0
        linux-vdso.so.1 (0x00007ffd54fbc000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f0c1e3dd000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0c1e3d7000)
        libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f0c1e3ca000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0c1e3a7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0c1e1b5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0c1e81c000)
```
