### ISSUE TITLE
Publish MsQuic packages for all Linux distros supported by .NET

### ISSUE THREAD

**Issue by CarnaViire** [microsoft/msquic#3640]
### Describe the bug

Officiall list of .NET supported distros: https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#linux

The following versions don't have msquic packages:
_(*) distro has OpenSSL 3 by default_

- **Fedora**
  - [x] 38 (*) (https://packages.microsoft.com/fedora/38/prod/Packages/)
- **Mariner**
  - [x] 2.0 (https://packages.microsoft.com/cbl-mariner/2.0/prod/Microsoft/x86_64/Packages/l/)
    - libmsquic 2.2.0 is present, but 2.2.1 is missing
- **RHEL**
  - [x] 8 (https://packages.microsoft.com/rhel/8/prod/Packages/)
  - [x] 9 (*) (https://packages.microsoft.com/rhel/9/prod/Packages/)
- **Ubuntu**
  - [x] 22.10 (*) (https://packages.microsoft.com/ubuntu/22.10/prod/pool/main/)
  - [x] 23.04 (*) (https://packages.microsoft.com/ubuntu/23.04/prod/pool/main/)

Upcoming releases (not sure if we want to track them separately or we can publish packages in advance):

- Debian 12 (2023-06-10)
- Fedora 39 (~2023-11)
- openSUSE 16.0 (Fall 2023)
- Ubuntu 23.10 (2023-10-12)

The following distros don't even have a dedicated directory in packages.microsoft.com (I don't know whether you can create one, so I'm not sure whether something can be done)

- RHEL family
  -  CentOS Stream 8&9
  - AlmaLinux 8&9
  - Rocky Linux 8&9

cc @wfurt @ManickaP

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

v2.2

### Steps taken to reproduce bug

Checking packages.microsoft.com for each of the distros

### Expected behavior

Package exists in packages.microsoft.com and can be installed

### Actual outcome

Package doesn't exist in packages.microsoft.com 

### Additional details

<details>
<summary>List of all supported distros with EOL dates</summary>

```
UPD: 2023-05-18

alpine

cycle    eol
-----    ---
3.15     2023-11-01 (!)
3.16     2024-05-23
3.17     2024-11-22
3.18 (*) 2025-05-09


centos

cycle eol
----- ---
7     2024-06-30


centos-stream

cycle eol
----- ---
8     2024-05-31
9     2027-05-31


debian

cycle eol
----- ---
11    2024-07-01


fedora
                                                                                                                        
cycle  eol
-----  ---
37     2023-12-15 (!)
38 (*) 2024-05-18


opensuse
                                                                                                                        
cycle eol
----- ---
15.4  2023-12-01 (!)


rhel

cycle eol
----- ---
7     2024-06-30
8     2029-05-31
9     2032-05-31


oraclelinux
                                                                                                                        
cycle eol
----- ---
7     2024-07-01
8     2029-07-01
9     2032-06-30


sles
                                                                                                                        
cycle eol
----- ---
12    2027-10-31
15    2031-07-31


ubuntu

cycle     eol
-----     ---
18.04     2023-05-31 (!)
20.04     2025-04-02
22.04     2027-04-01
22.10     2023-07-20 (!)
23.04 (*) 2024-01-20


(*) - released less than 3 months ago
(!) - EOL before the end of the year
```

</details>

<details>
<summary>OpenSSL 3 by default</summary>

- alpine 3.17+ https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.17.0
- debian 12+ (?) -- need to check release notes once released
- fedora 36+ https://fedoraproject.org/wiki/Changes/OpenSSL3.0  https://fedoraproject.org/wiki/Releases/36/ChangeSet#OpenSSL3.0
- RHEL 9+ https://www.redhat.com/en/blog/experience-bringing-openssl-30-rhel-and-fedora
- Ubuntu 22.04+ https://launchpad.net/ubuntu/+source/openssl

Still 1.1:
- openSUSE
- SLES https://www.suse.com/support/kb/doc/?id=000019582

</details>

Issues for Ubuntu 22.10 (https://github.com/microsoft/msquic/issues/3296) and Fedora 38 (https://github.com/microsoft/msquic/issues/3610) can be closed as duplicates of this one. I don't have rights to edit issues, so I had to create new one.

**Comment by ManickaP** [comment]
Centos is here: https://packages.microsoft.com/centos/

**Comment by CarnaViire** [comment]
> Centos is here: https://packages.microsoft.com/centos/

yes, but Stream is not...

**Comment by CarnaViire** [comment]
I believe it's for discontinued Centos 8

**Comment by CarnaViire** [comment]
CentOS Stream's directory should be inside `centos`, but the version directory should be `8-stream`/`9-stream`, judging by http://mirror.centos.org/centos/ and https://mirror.stream.centos.org/

**Comment by wfurt** [comment]
I don't think the name really matters when somebody adds new repo manually. 
adding @tmds and @omajid for any more comments on repo naming.

**Comment by csujedihy** [comment]
It looks like fedora36+ has openssl3 out of box but we still publish openssl1.1 based msquic packages to them.

**Comment by csujedihy** [comment]
Addressing this issue in #3652

**Comment by CarnaViire** [comment]
Thanks, @csujedihy! I see the packages are present; let me check that they work correctly with .NET on these distros

**Comment by CarnaViire** [comment]
Progress of check so far:
- Fedora 38 package works, but has an unstated libnuma dependencies (tracked in https://github.com/microsoft/msquic/issues/3421)
- Fedora 37 package does NOT work with a strange error (even though OpenSSL 3 is installed on the system)
 
```
/lib64/libmsquic.so.2: /lib64/libcrypto.so.3: version `OPENSSL_3.0.3' not found (required by /lib64/libmsquic.so.2)
```

(workaround is to fallback to 2.1.8 and install openssl1.1 package)

/cc @wfurt @ManickaP 

<details>

```
[root@521663ee22d7 /]# ldd /lib64/libmsquic.so.2
/lib64/libmsquic.so.2: /lib64/libcrypto.so.3: version `OPENSSL_3.0.3' not found (required by /lib64/libmsquic.so.2)
        linux-vdso.so.1 (0x00007ffcf29ff000)
        libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007fc327543000)
        libnuma.so.1 => /lib64/libnuma.so.1 (0x00007fc327535000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc327358000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fc32733e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc327ad5000)
[root@521663ee22d7 /]# rpm -qa | grep ssl
openssl-libs-3.0.9-1.fc37.x86_64
```

Dockerfile:

```
FROM fedora:37

RUN dnf install -y \
        dnf-plugins-core \
        libicu \
        vim

COPY  microsoft.asc /tmp
RUN dnf config-manager --add-repo https://packages.microsoft.com/fedora/37/prod/ && \
    rpm --import /tmp/microsoft.asc && \
    rm /tmp/microsoft.asc

RUN dnf install -y \
        numactl-libs \
        libmsquic && \
    dnf clean all
```
</details>

**Comment by nibanks** [comment]
Closing this, as everything that was asked for should be published. Let me know if it's not.
