### ISSUE TITLE
cmake compile error, quic_platform.h:174:2: error: #error "Unsupported Platform"

### ISSUE THREAD

**Issue by janksenhu** [microsoft/msquic#3648]
### Describe the bug

msquic_master/include/quic_platform.h:174:2: error: #error "Unsupported Platform"
 #error "Unsupported Platform"

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

ubuntu 16.04
cmake 3.26

### MsQuic version

main

### Steps taken to reproduce bug

cmake compile error
quic_platform.h:174:2: error: #error "Unsupported Platform"

### Expected behavior

compile failed

### Actual outcome

quic_platform.h:174:2: error: #error "Unsupported Platform"

**Comment by nibanks** [comment]
We don't explicitly support Ubuntu 16.04. I don't know what it would take to fix, but we don't have the resources to investigate ourselves. We'd be happy to take a PR if you know what is wrong. Otherwise, we'll likely have to close this as "Won't Fix." Please let us know. Thanks!

**Comment by janksenhu** [comment]
current issue could close directly ,i will paste more infor
