### ISSUE TITLE
quicsample  always fail to run 

### ISSUE THREAD

**Issue by lancelotluo** [microsoft/msquic#371]
it's a bug in ubuntu18.04.  when i run "./quicsample -server -cert_file:cert -key_file:key " it will always fail to run and return "Failed to load certificate from file! "

the reason is as follows:
in funcation GetSecConfigForFile, the default paramter is "QUIC_SEC_CONFIG_FLAG_CERTIFICATE_FILE",
![image](https://user-images.githubusercontent.com/800879/81366431-3a838b80-911d-11ea-8dc7-d4695af837df.png)

but tls_stub.c: QuicTlsServerSecConfigCreate , if the flags is "Flags & QUIC_SEC_CONFIG_FLAG_CERTIFICATE_FILE", it will goto error.
![image](https://user-images.githubusercontent.com/800879/81366441-41aa9980-911d-11ea-89fe-bf222aa7d15a.png)

i think the if condition of "Flags & QUIC_SEC_CONFIG_FLAG_CERTIFICATE_FILE" is unneccary. i made a pull request, it's pity that  external code contributions will not be accepted~

**Comment by nibanks** [comment]
Again, I'm sorry for the inconvenience. Thanks for filing the issue. Have you tried running with something other than stub TLS? On Ubuntu if you build with `-Tls openssl` I believe this will work. As for fixing stub, I believe the change is going to be a little more complicated than you proposed in your PR.

**Comment by lancelotluo** [comment]
> Again, I'm sorry for the inconvenience. Thanks for filing the issue. Have you tried running with something other than stub TLS? On Ubuntu if you build with `-Tls openssl` I believe this will work. As for fixing stub, I believe the change is going to be a little more complicated than you proposed in your PR.

thank you , i built it with default parameters, maybe not with "-Tls openssl". i'll try it.
