### ISSUE TITLE
Add support for Windows 10

### ISSUE THREAD

**Issue by Arclight3** [microsoft/msquic#3749]
### Describe the feature you'd like supported

Please add support for Windows 10.

I am a dotnet developer and I want to continue to use dotnet for QUIC calls. I don't want to be forced to move to Windows 11.
For now I kind of lost hope on dotnet and I am using python's aioquic library which works super fine in Windows 10.
My codebase is 99% written in dotnet and it's not a pleasant experience having to invoke a python script when I want to do a QUIC call.

To be honest it's a bit disappointing that other languages have support for QUIC in Windows 10 but msquic doesn't.

### Proposed solution

Add support for Windows 10

**Comment by nibanks** [comment]
MsQuic supports Win 10 just fine if you use openssl.

**Comment by Arclight3** [comment]
I am already using openssl but QUIC still doesnt work in C#

I have this configuration in my csproj:
```C#
<ItemGroup>
    <PackageReference Include="Microsoft.Native.Quic.MsQuic.OpenSSL" Version="2.2.2" />
    <RuntimeHostConfigurationOption Include="System.Net.SocketsHttpHandler.Http3Support" Value="true" />
</ItemGroup>
````

And this code:
```C#
using var request = new HttpRequestMessage(HttpMethod.Get, "https://my-server-url");
request.Version = HttpVersion.Version30;
request.VersionPolicy = HttpVersionPolicy.RequestVersionExact;

using var response = await client.SendAsync(request);
await (await response.Content.ReadAsStreamAsync()).CopyToAsync(streamToWriteTo);
```

But I get this error:
System.Net.Http.HttpRequestException: 'Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.'

Also I read in the dotnet documentation (https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-http3#windows) and it says it only supports Windows 11 or Windows Server 2022.

So how can I make msquic work in dotnet and Windows 10?

**Comment by eveloki** [comment]
I think this should be more convenient(It should even be configuration free), such as relying on Openssl first because Windows 10 is still a popular operating system.

**Comment by nibanks** [comment]
This is more of a .NET issue, and has been brought up a few times. MsQuic supports the different scenarios, but .NET only uses the schannel version on Windows by default.

**Comment by Arclight3** [comment]
I understand it's a dotnet limitation.. But since dotnet and msquic are both Microsoft projects, can you please collaborate on adding support in dotnet for msquic in Windows 10?

I don't want to be rude but other than forcing people to move to Windows 11 I see no reason not to have support for it in Windows 10 😞

**Comment by ManickaP** [comment]
If you want to use .NET with msquic (openssl) on Windows 10, you need to build the app as self-contained and replace the msquic.dll in the resulted package.

And why we (as dotnet) don't support OpenSSL msquic on Windows. It's shipping and security. With SChannel, security updates are part of Windows updates, whereas with OpenSSL the responsibility would be on us and that's something we're not able to do.

**Comment by Arclight3** [comment]
I understand better the problem now.
I will use your solution and close this issue.

Thank you very much for the detailed explanation @ManickaP! 😄

**Comment by mastahg** [comment]
This is the top result for when you search for this issue so I thought I would share a "solution"

```  
internal static class HarmonyHelper
   {

       static Harmony harmony;
       public static void Apply()
       {
           if (Environment.OSVersion.Version.Build < 22000)
           {
               harmony = new Harmony("com.dot.net.really");
               var original = typeof(NativeLibrary).GetMethods().FirstOrDefault(r => r.Name == "TryLoad" && r.GetParameters().Length > 2);
               harmony.Patch(original, prefix: new HarmonyMethod(Prefix));
           }

       }

       static bool Prefix(ref string libraryName, System.Reflection.Assembly assembly, System.Runtime.InteropServices.DllImportSearchPath? searchPath, out IntPtr handle)
       {
           handle = IntPtr.Zero;

           if (libraryName.EndsWith("\\msquic.dll"))
           {
               var target = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "msquic.dll");
               if (File.Exists(target))
                   libraryName = target;
               harmony.UnpatchAll("com.dot.net.really");

           }

           return true;
       }
   }
```

This uses the harmony patching library to intercept the request to load the msquic native dll and redirect it to the one in the local folder.

Based on the idea presenting in https://github.com/dotnet/runtime/pull/103351/ that was never merged.
