### ISSUE TITLE
Trying to connect to a QUIC server/Trying to create a Web server

### ISSUE THREAD

**Issue by WindowsNT** [microsoft/msquic#3794]
### Bug Description

A. I 've successfully compiled MSQUIC in Windows and create my own sample which works between clients.
Now I 'm trying to connect, say, to quic.rocks:4433. The ALPN list is as such (although I 'm not quite sure).

    QUIC_BUFFER bProtocols[5] =
    {
        { 2,(uint8_t*)"h3" },
        { 5,(uint8_t*)"h3-27" },
        { 5,(uint8_t*)"h3-28" },
        { 5,(uint8_t*)"h3-29" },
        { 8,(uint8_t*)"http/1.1" },
    };

When doing curl -vI --tls-max 1.3 https://quic.rocks I noticed the "ALPN: offers http/1.1" message.

No matter what I try, I always get a QUIC_CONNECTION_EVENT_SHUTDOWN_INITIATED_BY_TRANSPORT with {Status=0x80410004 : The QUIC connection encountered a protocol violation. ErrorCode=10 }

B. I'm trying to buidl a local web server. For that I already built a sample HTTPS server (which a certificate locally trusted to localhost) and this server sends back as headers:

 `sprintf_s(temp.data(), 10000, "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nConnection: Close\r\nalt-svc: h3=\":%i\"; ma=86400, h3-27=\":%i\"; ma=86400, h3-28=\":%i\"; ma=86400, h3-29=\":%i\"; ma=86400\r\n\r\nHello<b>There",p2,p2,p2,p2);
`
This causes chrome to actually connect to my listening QUIC server at port p2. However this also causes a  QUIC_CONNECTION_EVENT_SHUTDOWN_INITIATED_BY_TRANSPORT with {Status=0x8041012e ErrorCode=302 }.

I'm not sure of the ALPN protocols I should use and I'm not sure what I 'm doing wrong in both cases.

### Affected OS

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

Windows 11 Insider 22631.2129

### MsQuic version

main

### Steps taken to reproduce bug

1. Try to connect the sample to quic.rocks instead of the local server.

### Expected behavior

It should work, based on the ALPN.

### Actual outcome

Rejected in both client/server modes with the "transport" drop error.

**Comment by nibanks** [comment]
Only h3* ALPNs will work over QUIC. But, perhaps a better place for you to start is https://github.com/nibanks/msh3, which is a working HTTP/3 client and server on top of MsQuic.

**Comment by WindowsNT** [comment]
Thanks, the issue was at QUIC_SETTINGS.
Needs a UnidiStreamCount also;

        qs.IsSet.PeerUnidiStreamCount = TRUE;
        qs.PeerUnidiStreamCount = 3;
