### ISSUE TITLE
libmsquic unavailable for debian 12 (bookworm)

### ISSUE THREAD

**Issue by WhatzGames** [microsoft/msquic#3795]
### Describe the bug

libmsquic package is unavailable in https://packages.microsoft.com/ for debian 12 (bookworm)

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

debian 12 (bookworm)

### MsQuic version

main

### Steps taken to reproduce bug

Steps taken as described in microsoft/linux-package-repositories/issues/74

### Expected behavior

packages should be available in the repository

### Actual outcome

packages were not located in the repository for debian 12 (bookworm)

**Comment by WhatzGames** [comment]
Okay, I just found the pr microsoft/msquic/pull/3789 😅

But packages are not yet available?
Is this due to some delay?

**Comment by nibanks** [comment]
We just haven't published them yet. We will follow up in #3789. Thanks!
