### ISSUE TITLE
Invalid RECEIVE.Buffers when peer shutdown

### ISSUE THREAD

**Issue by lauix** [microsoft/msquic#3966]
### Describe the bug

msquic server-side  still received QUIC_STREAM_EVENT_RECEIVE event in the stream callback after peer shutdown the connection, the Event->RECEIVE.Buffers[0].Buffer is null and event->RECEIVE.Buffers[0].Length is a negative, like this -1771830300. Event->RECEIVE.Buffers is not thread-safe?

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

Occurring from time to time

### Expected behavior

after peer shutdown, server-side should not received QUIC_STREAM_EVENT_RECEIVE event.

### Actual outcome

Ktv_Director::recvDatabuffer, recvReminSize: 3799
Ktv_Director::recvDatabuffer, new dir msquic, data is null: 0, recvLength: -1771830300
Segmentation fault (core dumped)

**Comment by lauix** [comment]
recvLength is Event->RECEIVE.Buffers[0].Length, data is null means Event->RECEIVE.Buffers[0].Buffer is null.

**Comment by nibanks** [comment]
`Event->RECEIVE.Buffers` is a stack allocated variable, so it is not safe to use past the lifetime of the callback. If you're returning `QUIC_STATUS_PENDING` from the callback and using the buffers on your own thread(s) then you need to copy the `QUIC_BUFFER`(s) or just use the pointers & lengths directly.
