### ISSUE TITLE
Go (Language) Binding Support

### ISSUE THREAD

**Issue by giorgiozoppi** [microsoft/msquic#397]
### Describe the feature you'd like supported

We would like to support a go binding for this library, I would dedicate part of my time as contributor.

**Comment by nibanks** [comment]
Hi @giorgiozoppi! Thanks for opening the issue/feature request. We're not quite ready to accept outside contributions just yet (see [here](https://github.com/microsoft/msquic#contributing)), but hopefully soon; especially for these type of contributions. Feel free to make a PR and we'll try to take a look in (hopefully) the near future.

**Comment by giorgiozoppi** [comment]
We can close it since cgo is no way. The only way to support go and quick is a rewrite of a go stack for quick.

**Comment by noboruma** [comment]
If anyone else is interested in having Golang bindings:
https://github.com/noboruma/go-msquic
