### ISSUE TITLE
Unexpected delay between reception of data and sending an ACK

### ISSUE THREAD

**Issue by ralfluebben** [microsoft/msquic#3971]
### Describe the bug

I do some measurement between two directly connected machines. From time to time there is a delay spike in my measurements. From tcpdump traces I can see that between the reception of the data and related ACK there is a delay of about 8 ms. In the ACK Frame also a ACK Delay of 27 is reported.

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

I run a program derived from the sample.c with sends data periodically in streams.  Normally, a streams duration is about 8-9 ms. Seldom, the duration goes up to about 200 ms. 

### Expected behavior

There should be no delay spikes.

### Actual outcome

Looking into tcpdump traces shows, that the ACK frames are delayed. The figures shows a delay of 8 ms between frame 108693 and 108694, this repeats multiple times during the steam, so that the stream duration that is normally about 9 ms goes up to 200 ms. Furthermore, the sender only sends 4 packets after each ACK.

![grafik](https://github.com/microsoft/msquic/assets/75110400/81147b89-7d9e-439c-a44b-5c9be6182cd5)

### Additional details

I tested it on virtual machines as well as on bare metal hardware, with the same result. Also the delays occur nearly (but not exactly) at the same moment of the connection, i.e., since I send multiple streams (also the same size) it occurs typically at about stream 400.

Are there any features in msquic that could produce such delays between reception of packets and ACKs?

**Comment by nibanks** [comment]
The only thing that comes to mind is the delayed ACK timer, which is  ~25 ms. The best next steps will be to collect logs to see what's going on: https://github.com/microsoft/msquic/blob/main/docs/Diagnostics.md#trace-collection. Please collect and convert the logs, and share them.

**Comment by ralfluebben** [comment]
Thank you for the fast response. I think, the receiver answers late due to the delayed ACK timer, still it is unclear to me why the sender only sends four packets. I attached the log extract from the sender: at time 05:41:42.800999 the sender sets "Send Blocked Flags: 8", which should be related to congestion control, but at time 05:41:42.800998 packets InFlight are much smaller than CWnd, so congestion control should not block, at 05:41:42.808281 the (delayed) ACK is received and again four packets are sent and so on.

So here I do not understand why only four packets are sent, congestion control should allow for more.

I modified the "delayed ACK" timer therefore it is less than 25 ms. 

```[1][10b02.10b06][05:41:42.800993][S][TX][55800] SH DestCid: KP:0 SB:0 (Payload 1455 bytes)
[1][10b02.10b06][05:41:42.800994][S][TX][55800]   STREAM ID:612 Offset:4334 Len:1444
[1][10b02.10b06][05:41:42.800994][pack][2199023311353] Encrypting
[1][10b02.10b06][05:41:42.800997][pack][2199023311353] Finalizing
[1][10b02.10b06][05:41:42.800998][conn][0x7fc7bc012d20][TX][55800] 5 (1472 bytes)
[1][10b02.10b06][05:41:42.800998][conn][0x7fc7bc012d20] OUT: BytesSent=80029730 InFlight=5930 CWnd=699994 ConnFC=134211950 ISB=663552 PostedBytes=512000 SRtt=1314 1Way=1801772594
[1][10b02.10b06][05:41:42.800998][conn][0x7fc7bc012d20] OUT: StreamFC=33548654 StreamSendWindow=33554432
[1][10b02.10b06][05:41:42.800999][conn][0x7fc7bc012d20] Send Blocked Flags: 8
[1][10b02.10b06][05:41:42.801000][conn][0x7fc7bc012d20] Sending batch. 4 datagrams
[1][10b02.10b06][05:41:42.801000][data][0x5575e5d22890] Send 5888 bytes in 4 buffers (segment=1472) Dst=172.23.1.7:60354, Src=172.23.1.78:4567
[1][10b02.10b06][05:41:42.801014][pack][2199023258276] Batch sent
[1][10b02.10b06][05:41:42.801014][conn][0x7fc7bc012d20] Setting loss detection 2 timer for 9661 us. (ProbeCount=0)
[1][10b02.10b06][05:41:42.801014][conn][0x7fc7bc012d20] Setting 2, delay=9661 us
[1][10b02.10b06][05:41:42.801014][time][0x5575e5c41110] Updating Connection 0x7fc7bc012d20.
[1][10b02.10b06][05:41:42.801015][time][0x5575e5c41110] Next Expiration = {527875962264, 0x7fc7bc012d20}.
[1][10b02.10b06][05:41:42.801015][conn][0x7fc7bc012d20] Flush complete flags=0x0
[1][10b02.10b06][05:41:42.801015][conn][0x7fc7bc012d20] Scheduling: 0
[1][10b02.10b06][05:41:42.801017][wrkr][0x5575e5c41070] IsActive = 0, Arg = 3889952152
[1][10b02.10b06][05:41:42.801017][wrkr][0x5575e5c41070] QueueDelay = 0
[1][10b02.10b06][05:41:42.808281][data][0x5575e5d22890] Recv 38 bytes (segment=0) Src=172.23.1.78:4567 Dst=172.23.1.7:60354
```

**Comment by nibanks** [comment]
Can you share the whole file? I can't tell what's going on from just this part. And to be clear, this is the sender side, right?

**Comment by nibanks** [comment]
And assuming this is on Windows, can you share the raw ETL file?

**Comment by ralfluebben** [comment]
At that moment it is the sender side, just before it was the receiving side. The effect occurs just after the transition from receiver to sender, only 4 packets are sent. 

The sending/receiving pattern is, the client sends 1,3 MByte of data, the server answers with 500 kByte, the server sends 200 kByte. The problem occurs from the transition from client and server when they change sending/ receiving direction the first time. These transmissions belong to a stream and the transmission is repeated again and again in a new stream. In this experiment the transmission time of the stream is 12-14 ms until stream number 612 , there it increases to 215 ms, stream 616 is still at 119ms, stream 620 at 19 ms, and afterwards the effect is gone.

That is the log of my client application:
```
...
[strm][0x7fe100002ab0] Stop stream id 596 in 14 ms
[strm][0x7fe100002ab0] Stop stream id 600 in 13 ms
[strm][0x7fe100002ab0] Stop stream id 604 in 14 ms
[strm][0x7fe100002ab0] Stop stream id 608 in 12 ms
[strm][0x7fe100002ab0] Stop stream id 612 in 215 ms
[strm][0x7fe100002520] Stop stream id 616 in 119 ms
[strm][0x7fe100002f10] Stop stream id 620 in 19 ms
[strm][0x7fe100002f10] Stop stream id 624 in 12 ms
[strm][0x7fe100002f10] Stop stream id 628 in 12 ms
[strm][0x7fe100002f10] Stop stream id 632 in 11 ms
...
```
Attached you find the log files, truncated after stream 632, due to the upload limit of 25MB. If helpful, I can also upload the related Tcpdump file and decryption key somewhere else. Unfortunately, the traces are from a Linux system 

[client_quic_trunc.zip](https://github.com/microsoft/msquic/files/13470032/client_quic_trunc.zip)
[server_quic_trunc.zip](https://github.com/microsoft/msquic/files/13470034/server_quic_trunc.zip)

**Comment by ralfluebben** [comment]
It is related to the variable kMinCwndInMss in https://github.com/microsoft/msquic/blob/4fa54d99b3a023e900b64afbc335d177e3eec429/src/core/bbr.c#L56C12-L56C12, which is set to 4 MSS

**Comment by nibanks** [comment]
Can you try Cubic and see how it compares?

**Comment by ralfluebben** [comment]
Yes, it performs better in the sense, that no delay spikes are visible at all. Nevertheless, my current network setup is quite simple and congestion control should not play a role (as long as it does not lowers CWND to four packets artificially). It is just two virtual machines. To my understanding in BBRv3 this drastic reduction in CWND is avoided, but this is another story.
