### ISSUE TITLE
Not compiling with stdout logging enabled

### ISSUE THREAD

**Issue by mgrichardvanharten** [microsoft/msquic#4001]
### Describe the bug

Create build files with the following:
QUIC_LOGGING_TYPE:STRING=stdout
QUIC_ENABLE_LOGGING:BOOL=ON

This results in the following compile errors when compiling:
src\inc\msquichelper.h(53,5): error C2051: case expression not constant
src\inc\msquichelper.h(54,5): error C2051: case expression not constant
src\inc\msquichelper.h(57,5): error C2051: case expression not constant
src\inc\msquichelper.h(60,5): error C2051: case expression not constant
src\inc\msquichelper.h(62,5): error C2051: case expression not constant

### Affected OS

- [X] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

v2.2

### Steps taken to reproduce bug

Create build files with the following:
QUIC_LOGGING_TYPE:STRING=stdout
QUIC_ENABLE_LOGGING:BOOL=ON

### Expected behavior

Successful compilation

### Actual outcome

Compile errors 

src\inc\msquichelper.h(53,5): error C2051: case expression not constant
src\inc\msquichelper.h(54,5): error C2051: case expression not constant
src\inc\msquichelper.h(57,5): error C2051: case expression not constant
src\inc\msquichelper.h(60,5): error C2051: case expression not constant
src\inc\msquichelper.h(62,5): error C2051: case expression not constant

**Comment by nibanks** [comment]
Thanks for the report. Just sent a PR that should fix this. It'd be great if you could verify too. Thanks!
