### ISSUE TITLE
Allow Multiple Pending Buffers Simultaneously

### ISSUE THREAD

**Issue by kamrey2** [microsoft/msquic#4018]
### Describe the feature you'd like supported

When data on a  QUIC stream is available, MSQuic gives the buffer with the data to the application. The application can hold on to the buffer as long as it needs. The current API allows only a single buffer to be given to the application, i.e. pending, at the time. 
Currently htp.sys copies the data from the buffer to its own buffer and gives the buffer back to MSQuic as fast as possible. Http.sys would like to avoid the copy and hold on to the MSQuic buffer until it is given the the application on top of http.sys. To make this new approach performant, http.sys will need to have multiple MSQuic buffers pending at a time.

### Proposed solution

N/A

**Comment by nibanks** [comment]
Completing the task since the code has been merged.
