### ISSUE TITLE
Certificate rejection via ConnectionCertificateValidationComplete leads to connection timeout.

### ISSUE THREAD

**Issue by rzikm** [microsoft/msquic#4132]
### Describe the bug

I am offloading computation-heavy certificate validation to a non-MsQuic thread in System.Net.Quic, and a unit test where the cert is rejected keeps failing.

Wireshark capture of when the `ConnectionCertificateValidationComplete` function is invoked from inside the `PEER_CERTIFICATE_RECEIVED` handler:

<img width="966" alt="image" src="https://github.com/microsoft/msquic/assets/32671551/bb684941-205f-457f-8cef-27fe6dc80b95">

Notably, the Connection Close frame is sent at the Handshake protection level. This works fine.

When the invocation is moved to be done later from another thread:

<img width="964" alt="image" src="https://github.com/microsoft/msquic/assets/32671551/b2f22099-61b5-4090-ab72-47594fd89666">

Note that this time, the Connection Close is sent at 1RTT level, which seems to get ignored by the server. The connection attempt times out and get's closed by the server (the last line). The capture is attached below, together with sslkeylogfile to decrypt it.

[quic-cert-validation.zip](https://github.com/microsoft/msquic/files/14270310/quic-cert-validation.zip)

### Affected OS

- [x] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

Reproduced on Windows, didn't try other OSes

### MsQuic version

main

### Steps taken to reproduce bug

Use `ConnectionCertificateValidationComplete` to reject certificate from another thread.

### Expected behavior

The server-side connection receives TLS alert which was sent by the client.

### Actual outcome

The connection attempt times out

**Comment by nibanks** [comment]
Go ahead and create the PR. We can go from there. Let's see if all the tests still pass.
