### ISSUE TITLE
Test immediately get aborted

### ISSUE THREAD

**Issue by ami-GS** [microsoft/msquic#4198]
### Describe the bug

`msquictest` and `msquicplatformtest` immediately aborted at

https://github.com/microsoft/msquic/blob/cacfccae195ab36f91fd7e2c27ab56a863935ba3/src/inc/quic_platform_posix.h#L883

@nigriMSFT 

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

- Ubuntu 22.04 (amd64) on Hyper-V
- Raspbian (arm32)

### MsQuic version

main

### Steps taken to reproduce bug

pwsh ./scripts/build.ps1
./artifacts/bin/linux/x64_Debug_openssl3/msquictest

### Expected behavior

Test runs without abort

### Actual outcome

![image](https://github.com/microsoft/msquic/assets/5763034/becf1127-3267-4763-87f3-20f56c9b9c8b)

**Comment by nigriMSFT** [comment]
As discussed during review of that PR, this assert catches cases where the caller is incorrectly calling WaitWithTimeout when they should've instead called WaitForever.

**Comment by nibanks** [comment]
@ami-DS which tests/callstacks are hitting this?

**Comment by ami-GS** [comment]
@nibanks 
msquictest and msquicplatformtest

> (gdb) bt
> #0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737336817216) at ./nptl/pthread_kill.c:44
> #1  __pthread_kill_internal (signo=6, threadid=140737336817216) at ./nptl/pthread_kill.c:78
> #2  __GI___pthread_kill (threadid=140737336817216, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
> #3  0x00007ffff7842476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
> #4  0x00007ffff78287f3 in __GI_abort () at ./stdlib/abort.c:79
> #5  0x000055555563272f in quic_bugcheck (File=0x55555598b010 "/home/daiki/workspace/msquic/src/bin/../inc/quic_platform_posix.h", Line=883,
>     Expr=0x55555598b052 "TimeoutMs != (4294967295U)") at /home/daiki/workspace/msquic/src/platform/platform_posix.c:93
> #6  0x00005555555c777f in CxPlatInternalEventWaitWithTimeout (TimeoutMs=<optimized out>, Event=<optimized out>)
>     at /home/daiki/workspace/msquic/src/bin/../inc/quic_platform_posix.h:883
> #7  CxPlatEvent::WaitTimeout (TimeoutMs=<optimized out>, this=<optimized out>) at /home/daiki/workspace/msquic/src/bin/../inc/msquic.hpp:61
> #8  CxPlatWatchdog::WatchdogThreadCallback (Context=<optimized out>) at /home/daiki/workspace/msquic/src/bin/../inc/msquic.hpp:225
> #9  0x00007ffff7894ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
> #10 0x00007ffff7926850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

**Comment by ami-GS** [comment]
Seems to be fixed on latest main
