### ISSUE TITLE
Linux XDP instructions break the machine

### ISSUE THREAD

**Issue by larseggert** [microsoft/msquic#4299]
### Describe the bug

This step in `docs/BUILD.md`
```
sudo apt-add-repository "deb http://mirrors.kernel.org/ubuntu noble main" -y
```
hoses a 22.04 machine, because it unconditionally adds debs from 24.04.

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

Followed XDP steps in `docs/BUILD.md`

### Expected behavior

Expected to not have a broken machine after :-)

### Actual outcome

Base 22.04 debs get overwritten with 24.04 ones.

**Comment by nibanks** [comment]
@ami-GS please take a look.

**Comment by ami-GS** [comment]
@nibanks  This is expected, or we need to build from source

**Comment by larseggert** [comment]
The it would be good to call out in big, red letters that following the steps will render a 22.04 machine un-updatable.

**Comment by ami-GS** [comment]
@larseggert PR was merged
