### ISSUE TITLE
Enable building for UWP user mode

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#436]
### Describe the feature you'd like supported

Building the library for UWP user mode could be useful. The following functions and definitions don't exist in UWP mode.

`ReadNoFence64` does not exist. Need to find an alternative. Since the function is defined in a header, and just forwards to another function, might be able to see if the other function exists.

Much of the code related to setting thread name in `QuicThreadCreate` does not exist. However, because UWP is separate binaries in all cases, we can safely use `SetThreadDescription` instead for UWP.

That looks to be it.

**Comment by ThadHouse** [comment]
Those 2 calls were just the initial blockers. There are a lot more functions that are missing. Here is a list. Not sure we could realistically remove all of them.

RegOpenKeyEx
RegNotifyChangeKeyValue
RegCloseKey
RegQueryValueEx
Get/SetCurrentThreadCompartmentId
GetModuleHandle
GetActiveProcessorCount

And to add on to that, schannel is not available either. I don't think its going to  be feasible to get UWP user mode working without gutting functionality.

**Comment by nibanks** [comment]
Ok. Let's keep this issue open for now. I'll try to start an internal email thread with folks that might be able to help here.

**Comment by ThadHouse** [comment]
So it turns out the following functions even if you get them to compile they're blocked from the store.

GetActiveProcessorCount 
GetCurrentThreadCompartmentId 
SetCurrentThreadCompartmentId 
NtQueryTimerResolution 

I'll ping around and see if there is a legal to use API for these. Otherwise, we'll be able to build and deploy QUIC locally, but will not be able to publish to the Windows store.

**Comment by hummeleBop** [comment]
If I understand correctly, it's currently not possible to publish UWP app on the windows store with msquic as dependency, right ?

Is this feature will be available at some point ?
