### ISSUE TITLE
build android x86 in ubuntu error

### ISSUE THREAD

**Issue by yourihua** [microsoft/msquic#4394]
### Describe the bug

cd /mnt/d/code/tnt/msquic/build/android/x86_openssl3/src/platform && /root/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=i686-none-linux-android29 --sysroot=/root/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DCX_PLATFORM_LINUX -DHAS_SENDMMSG -DHAS_SYSCONF -DHAS__SC_PHYS_PAGES -DQUIC_ENABLE_CA_CERTIFICATE_FILE_TESTS -DQUIC_EVENTS_STUB -DQUIC_LOGS_STUB -DQUIC_SHARED_EPHEMERAL_WORKAROUND -DQUIC_TELEMETRY_ASSERTS=1 -DQUIC_TEST_OPENSSL_FLAGS=1 -DVER_BUILD_ID=0 -DVER_GIT_HASH=933f7b79949bc588945672396d70b661143bb8f0 -DVER_SUFFIX=-private -D_GNU_SOURCE -I/mnt/d/code/tnt/msquic/src/inc -I/mnt/d/code/tnt/msquic/build/android/x86_openssl3/_deps/opensslquic-build/openssl3/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O3 -fno-omit-frame-pointer  -DNDEBUG -ggdb3 -fPIC -fms-extensions -fPIC -Werror -Wall -Wextra -Wformat=2 -Wno-type-limits -Wno-unknown-pragmas -Wno-multichar -Wno-missing-field-initializers -Wno-missing-braces -Wno-microsoft-anon-tag -MD -MT src/platform/CMakeFiles/platform.dir/platform_posix.c.o -MF CMakeFiles/platform.dir/platform_posix.c.o.d -o CMakeFiles/platform.dir/platform_posix.c.o -c /mnt/d/code/tnt/msquic/src/platform/platform_posix.c
gmake[2]: Leaving directory '/mnt/d/code/tnt/msquic/build/android/x86_openssl3'
/usr/bin/gmake  -f src/core/CMakeFiles/core.dir/build.make src/core/CMakeFiles/core.dir/build
/mnt/d/code/tnt/msquic/src/platform/platform_posix.c:323:9: error: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes) [-Werror,-Watomic-alignment]
    if (__atomic_add_fetch(RefCount, 1, __ATOMIC_SEQ_CST)) {
        ^
1 error generated.
gmake[2]: *** [src/platform/CMakeFiles/platform.dir/build.make:160: src/platform/CMakeFiles/platform.dir/platform_posix.c.o] Error 1
gmake[2]: Leaving directory '/mnt/d/code/tnt/msquic/build/android/x86_openssl3'
gmake[1]: *** [CMakeFiles/Makefile2:613: src/platform/CMakeFiles/platform.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[2]: Entering directory '/mnt/d/code/tnt/msquic/build/android/x86_openssl3'
gmake[2]: Nothing to be done for 'src/core/CMakeFiles/core.dir/build'.
gmake[2]: Leaving directory '/mnt/d/code/tnt/msquic/build/android/x86_openssl3'
[ 47%] Built target core
gmake[1]: Leaving directory '/mnt/d/code/tnt/msquic/build/android/x86_openssl3'
gmake: *** [Makefile:146: all] Error 2
Write-Error: /mnt/d/code/tnt/msquic/scripts/build.ps1:525
Line |
 525 |      CMake-Execute $Arguments
     |      ~~~~~~~~~~~~~~~~~~~~~~~~
     | [07/09/2024 16:55:45] CMake exited with status code 2
PS /mnt/d/code/tnt/msquic> ./scripts/build.ps1 -Config Release -Platform android -Arch x86

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

v2.3

### Steps taken to reproduce bug

run
./scripts/build.ps1 -Config Release -Platform android -Arch x86

output
[ 19%] Building C object src/platform/CMakeFiles/platform.dir/platform_posix.c.o
cd /mnt/d/code/tnt/msquic/build/android/x86_openssl3/src/platform && /root/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=i686-none-linux-android29 --sysroot=/root/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DCX_PLATFORM_LINUX -DHAS_SENDMMSG -DHAS_SYSCONF -DHAS__SC_PHYS_PAGES -DQUIC_ENABLE_CA_CERTIFICATE_FILE_TESTS -DQUIC_EVENTS_STUB -DQUIC_LOGS_STUB -DQUIC_SHARED_EPHEMERAL_WORKAROUND -DQUIC_TELEMETRY_ASSERTS=1 -DQUIC_TEST_OPENSSL_FLAGS=1 -DVER_BUILD_ID=0 -DVER_GIT_HASH=933f7b79949bc588945672396d70b661143bb8f0 -DVER_SUFFIX=-private -D_GNU_SOURCE -I/mnt/d/code/tnt/msquic/src/inc -I/mnt/d/code/tnt/msquic/build/android/x86_openssl3/_deps/opensslquic-build/openssl3/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O3 -fno-omit-frame-pointer  -DNDEBUG -ggdb3 -fPIC -fms-extensions -fPIC -Werror -Wall -Wextra -Wformat=2 -Wno-type-limits -Wno-unknown-pragmas -Wno-multichar -Wno-missing-field-initializers -Wno-missing-braces -Wno-microsoft-anon-tag -MD -MT src/platform/CMakeFiles/platform.dir/platform_posix.c.o -MF CMakeFiles/platform.dir/platform_posix.c.o.d -o CMakeFiles/platform.dir/platform_posix.c.o -c /mnt/d/code/tnt/msquic/src/platform/platform_posix.c
gmake[2]: Leaving directory '/mnt/d/code/tnt/msquic/build/android/x86_openssl3'
/usr/bin/gmake  -f src/core/CMakeFiles/core.dir/build.make src/core/CMakeFiles/core.dir/build
/mnt/d/code/tnt/msquic/src/platform/platform_posix.c:323:9: error: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes) [-Werror,-Watomic-alignment]
    if (__atomic_add_fetch(RefCount, 1, __ATOMIC_SEQ_CST)) {
        ^
1 error generated.
gmake[2]: *** [src/platform/CMakeFiles/platform.dir/build.make:160: src/platform/CMakeFiles/platform.dir/platform_posix.c.o] Error 1
gmake[2]: Leaving directory '/mnt/d/code/tnt/msquic/build/android/x86_openssl3'
gmake[1]: *** [CMakeFiles/Makefile2:613: src/platform/CMakeFiles/platform.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[2]: Entering directory '/mnt/d/code/tnt/msquic/build/android/x86_openssl3'
gmake[2]: Nothing to be done for 'src/core/CMakeFiles/core.dir/build'.
gmake[2]: Leaving directory '/mnt/d/code/tnt/msquic/build/android/x86_openssl3'
[ 47%] Built target core
gmake[1]: Leaving directory '/mnt/d/code/tnt/msquic/build/android/x86_openssl3'
gmake: *** [Makefile:146: all] Error 2
Write-Error: /mnt/d/code/tnt/msquic/scripts/build.ps1:525
Line |
 525 |      CMake-Execute $Arguments
     |      ~~~~~~~~~~~~~~~~~~~~~~~~
     | [07/09/2024 16:55:45] CMake exited with status code 2

### Expected behavior

buid x86_Release_openssl3 succ

### Actual outcome

error

### Additional details

android {
    ndkVersion "25.2.9519653"
}

_No response_

**Comment by nibanks** [comment]
I believe this was resolved with a recent change.
