### ISSUE TITLE
Register fails on system with many cores

### ISSUE THREAD

**Issue by ddavila0** [microsoft/msquic#4409]
### Describe the bug

Trying to execute the sample binary fails when calling RegistrationOpen (https://github.com/microsoft/msquic/blob/main/src/tools/sample/sample.c#L1015) with the following error:
```
[ lib][0xa5aa20] Worker start [PlatformWorkerThreadStart:/home/users/ddavila/projects/tcp/quic/git/msquic/src/platform/platform_worker.c:477]
[ lib][0xa5aab0] Worker start [PlatformWorkerThreadStart:/home/users/ddavila/projects/tcp/quic/git/msquic/src/platform/platform_worker.c:477]
[ lib] ERROR, CxPlatEventQInitialize. [LibraryError:/home/users/ddavila/projects/tcp/quic/git/msquic/src/platform/platform_worker.c:173]
```
This happens to thread number 254 out of 255 (might be a hint). If I reduce the number of threads to start to 16, by modifying the code (adding CxPlatWorkerCount=16; here: https://github.com/microsoft/msquic/blob/main/src/platform/platform_worker.c#L137) (couldn't find how to configure this on Linux), the registration works (it fails somewhere else down the road as I'd expect).

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

AlmaLinux release 8.10 (Cerulean Leopard)
Linux uaf-3.t2.ucsd.edu 6.3.8-1.el8.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 14 16:16:07 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### MsQuic version

main

### Steps taken to reproduce bug

build with -DCMAKE_BUILD_TYPE=Debug -DQUIC_BUILD_TOOLS=True
./sample

### Expected behavior

I'll get to the part where it complains about missing arguments.

### Actual outcome

Fails with: 
RegistrationOpen failed, 0xc!

### Additional details

In a very similar system (with 16 cores) it works just fine

**Comment by nibanks** [comment]
The logs indicate this is failing:
```c
inline
BOOLEAN
CxPlatEventQInitialize(
    _Out_ CXPLAT_EVENTQ* queue
    )
{
    return (*queue = epoll_create1(EPOLL_CLOEXEC)) != -1;
}
```
Do you not have enough handles or something configured? (I'm not a Linux expert)

**Comment by nibanks** [comment]
Probably one of these errors:
```
       EMFILE The per-process limit on the number of open file
              descriptors has been reached.

       ENFILE The system-wide limit on the total number of open files
              has been reached.
```
https://www.man7.org/linux/man-pages/man2/epoll_create.2.html

**Comment by ddavila0** [comment]
Thanks for the reply @nibanks, doing `ulimit -n 2048` made the trick. Thanks!
```
[1730] root@uaf-2 /opt/msquic/build# ulimit -n 1024
[1730] root@uaf-2 /opt/msquic/build# bin/Release/quicsample -client -target:test-007.t2.ucsd.edu 
RegistrationOpen failed, 0xc!
[1730] root@uaf-2 /opt/msquic/build# ulimit -n 2048
[1730] root@uaf-2 /opt/msquic/build# bin/Release/quicsample -client -target:test-007.t2.ucsd.edu 
[conn][0x23eb590] Connecting...
[conn][0x23eb590] Shut down by transport, 0x71
[conn][0x23eb590] All done
```

**Comment by 825126369** [comment]
Win11操作系统,   .Net 9  System.Net.Quic 报错:  RegistrationOpen failed
