### ISSUE TITLE
When the server requires client authentication, an error occurs when using the Resumption Ticket

### ISSUE THREAD

**Issue by smartom101** [microsoft/msquic#4436]
### Error description
When reconnecting using a resumption ticket, if QUIC_CREDENTIAL_FLAG_REQUIRE_CLIENT_AUTHENTICATION is set, an error message is displayed: Shut down by transport, 0x "FFFFFFFF80410150".
### Testing

- In Windows 10, using the msquic library, **without** using a resumption ticket, **requiring** client and server mutual authentication, and correctly configuring the client certificate and server certificate, I can reconnect successfully.

- In Windows 10, using the msquic library, **with** using a resumption ticket, **only require** server mutual authentication(**Without** QUIC_CREDENTIAL_FLAG_REQUIRE_CLIENT_AUTHENTICATION set), and correctly configuring the server certificate, I can reconnect successfully.
- The above situations are all tested under the condition of using openssl.
### question
Is this a bug or is there something wrong with my usage?

**Comment by smartom101** [comment]
Could anyone help me answer this, thank you very much

**Comment by nibanks** [comment]
I don't think anyone over head knows off hand. What would really help us (if you're willing) is to add a PR for a new test case that tests what you're trying to do. Then we can analyze failure logs, and follow up as necessary.

**Comment by smartom101** [comment]
OK, thanks all the same. I will add the PR.
