### ISSUE TITLE
ODR violations in every test library built

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#444]
### Describe the bug

Trying to implement #438, I noticed that the way we are building all the test and tool libraries violates ODR pretty badly. On linux, this hasn't been noticeable because libmsquic.so exports everything by default, however on Windows I'm a bit shocked this hasn't completely bit us yet, but maybe it has and we just haven't noticed it yet.

We statically link `platform` and `core` into `msquic.dll`. This causes any functions in those libraries that are used from `MsQuicOpen` and `MsQuicClose` and all its dependencies (so basically everything) to be included in the shared library. However, because of the .def file, those dependencies are not visible from from outside the shared library. However, many of our test and tool libraries need to hook into some of the APIs in platform and core. The way this is being done in the build is by including platform and core in the link libraries list after msquic.dll. This causes a copy of all functions used directly by the tool or test to be included in the executable. If the executable calls one of these functions, it will call the function embedded in the executable rather then the copy in the shared library. If the function is called from inside the shared library however, it will call the copy embedded in the shared library. For leaf functions, this isn't a huge deal, but if the function manipulates global state or allocates memory, this can cause major issues. For global state, the other set of functions won't see that state change. For allocating memory, if the memory is freed from the other set of functions, the free is happening from the wrong heap.

This isn't a bug that can easily be reproduced is it requires the right set of circumstances which we might not be using, but when it does issues will happen.

### Possible fixes
Fixing this requires doing 1 of 2 things. Either we export the internal functions we wish to use from the DLL so we only have to link to the DLL itself, or we perform all testing and tool usage using only the `platform` and `core` libraries, and leave the final shared library to only be used for distribution, or tests that can be performed using exclusively the public API.

**Comment by nibanks** [comment]
It is by design that those libraries are statically linked into the test code. We don't want them exported from msquic. We want to use a separate copy. We want the DLL to be self-contained.

**Comment by ThadHouse** [comment]
Do none of the functions we're using modify global state or allocate memory? If that's the case then I guess we're ok, but if not, thats a nasty bug just waiting to happen.

**Comment by nibanks** [comment]
We just duplicate any global state. The DLL has a copy of the global state used internally. The tests/tools that use the platform library have their own copy.

**Comment by ThadHouse** [comment]
Ok. They also end up with their own copy of `core` as well. We just need to be extra sure we never accidentally share that state, or need to share that state.

**Comment by nibanks** [comment]
Sure. I'm pretty sure everything is in the expected state right now.

**Comment by ThadHouse** [comment]
I guess I'll close this then. It scares me immensely, but if we can be sure of the invariants I guess we're ok.
