### ISSUE TITLE
libmsquic missing from Azure Linux 3.0

### ISSUE THREAD

**Issue by richlander** [microsoft/msquic#4450]
### Describe the feature you'd like supported

```bash
root [ / ]# cat /etc/os-release | grep PRETTY_
PRETTY_NAME="Microsoft Azure Linux 3.0"
root [ / ]# tdnf install libmsquic
Loaded plugin: tdnfrepogpgcheck
libmsquic package not found or not installed
Error(1011) : No matching packages
```

### Proposed solution

Make the package available.

**Comment by ami-GS** [comment]
@richlander 
Do you have docker image?
I found this `mcr.microsoft.com/cbl-mariner/base/core:2.0`, but cannot find 3.0

**Comment by richlander** [comment]
Here is the Dockerfile we just merged.

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/azurelinux/3.0/helix/Dockerfile

**Comment by richlander** [comment]
FYI: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1170

**Comment by ami-GS** [comment]
Generally How can we find repository name?
 
Azure pipeline cannot find `cbl-mariner-3.0-prod-Microsoft-x86_64-yum`.
I just incremented the name from `cbl-mariner-2.0-prod-Microsoft-x86_64-yum` which has been working

**Comment by jslobodzian** [comment]
In 3.0 there were two important changes:
1) Rebranding as "azure-linux"
2) repository name for "Microsoft" changed names to "ms-oss" (Microsoft Open Source Software) to more clearly delineate it from "ms-non-oss" (which was previously known as Extras).

The repositories are here: https://packages.microsoft.com/azurelinux/3.0/prod/ms-oss/

**Comment by ami-GS** [comment]
Thanks, but what is the associated repository name, previously named as `cbl-mariner-2.0-prod-Microsoft-x86_64-yum`?

**Comment by ami-GS** [comment]
maybe combining path by `-`?
https://packages.microsoft.com/cbl-mariner/2.0/prod/Microsoft/x86_64/ -> `cbl-mariner-2.0-prod-Microsoft-x86_64-yum`
https://packages.microsoft.com/azurelinux/3.0/prod/ms-oss/x86_64/ -> `azurelinux-3.0-prod-ms-oss-x86_64-yum`
?

**Comment by ami-GS** [comment]
assumption is correct, `azurelinux-3.0-prod-ms-oss-x86_64-yum` works

**Comment by ami-GS** [comment]
@richlander @jslobodzian 
Do you have list of linux kernel version of azure linux 1.0, 2.0 and 3.0?

**Comment by jslobodzian** [comment]
@ami-GS azure-linux 1.0 is no longer supported but it was the 5.10 kernel.  2.0 is the 5.15 kernel and 3.0 is the 6.6 kernel.  There are many micro and sub-micro versions of each supported as the kernel is continually rolled and updated.  You can browse the packages on packages.microsoft.com for future needs/reference.  Repos are here.

[2.0] https://packages.microsoft.com/cbl-mariner/2.0/prod/base/
[3.0] https://packages.microsoft.com/azurelinux/3.0/prod/base/

**Comment by ami-GS** [comment]
https://github.com/microsoft/msquic/pull/4455

**Comment by ami-GS** [comment]
@richlander 
I see libmsquic is published
https://packages.microsoft.com/azurelinux/3.0/prod/ms-oss/x86_64/Packages/l/

**Comment by richlander** [comment]
Thanks! I created this PR in response.

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1183
