### ISSUE TITLE
QUIC_PARAM_TLS_HANDSHAKE_INFO is failing on server size connection

### ISSUE THREAD

**Issue by wfurt** [microsoft/msquic#4457]
### Describe the bug

I but to this when working on support for https://github.com/dotnet/runtime/issues/70184
The test is pretty simple: we establish Quic connection and we query the property on both sides and we expect them to be the same. On server, this fails with `QUIC_STATUS_INVALID_PARAMETER`. That alone is suboptimal IMHO as all the parameters _are_ valid. From quic debug it seems like the `Connection->Crypto.TLS` is NULL.

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

I only tested this on Ubuntu 22.04 but I doubt this is specific only to my version. 

### MsQuic version

main

### Steps taken to reproduce bug

1. establish Quic connection and trey to get TLS info on both sides.

### Expected behavior

The query should succeed and `QUIC_HANDSHAKE_INFO` should be filled with correct details. 

### Actual outcome

the query fails with `QUIC_STATUS_INVALID_PARAMETER`

### Additional details

https://github.com/dotnet/runtime/pull/106368 is my draft PR to expose `NegotiatedCipherSuite` in .NET.

**Comment by nibanks** [comment]
cc @anrossi can you take a look?

**Comment by anrossi** [comment]
@wfurt when are you querying this? In the `QUIC_CONNECTION_EVENT_CONNECTED` event callback? Or after?  When resumption/0-RTT is not enabled on server, it cleans up the TLS state as soon as the handshake is complete (immediately after the CONNECTED callback returns). This is a memory-saving optimization.

**Comment by wfurt** [comment]
since this is now exposed on `QuicStream` the original code would simply pass that to msquic. @rzikm put up different implementation where we query it and cache it regardless of the user here: https://github.com/dotnet/runtime/pull/106391

If anything I wish there was some more meaningful error coming back.

**Comment by anrossi** [comment]
Would an "invalid state" error be more helpful?

**Comment by wfurt** [comment]
yes, perhaps as this is related to the inner state and not passed parameters. Also it did work on client but not on server in exactly same scenario.

**Comment by anrossi** [comment]
Right, because the client keeps the TLS state around for the lifetime of the connection. This is because the server could send a resumption/0-RTT ticket at any time, and the client needs TLS still active to process that ticket.  In this case, the server and client are not perfectly symmetrical.

**Comment by anrossi** [comment]
This should have been addressed by #4518 so I'm closing this. Please re-open if you find that change insufficient.
