### ISSUE TITLE
QUIC_SEND_PACING_INTERVAL unit default to us,  not need MS_TO_US()

### ISSUE THREAD

**Issue by Bluesky202310** [microsoft/msquic#4470]
### Describe the bug

QUIC_SEND_PACING_INTERVAL unit default to us,  MS_TO_US() expand it 1000x.  so SendAllowance with no pacing will easy occur.

bbr.c
_IRQL_requires_max_(DISPATCH_LEVEL)
uint32_t
BbrCongestionControlGetSendAllowance(
    _In_ QUIC_CONGESTION_CONTROL* Cc,
    _In_ uint64_t TimeSinceLastSend, // microsec
    _In_ BOOLEAN TimeSinceLastSendValid
    )
{
...
        Bbr->MinRtt < **MS_TO_US**(QUIC_SEND_PACING_INTERVAL)) {	
         //
        // We're not in the necessary state to pace.
        //
        SendAllowance = CongestionWindow - Bbr->BytesInFlight;
...
}

quicdef.h
//
// The number of **microseconds** between pacing chunks.
//
#define QUIC_SEND_PACING_INTERVAL               1000

### Affected OS

- [X] Windows
- [X] Linux
- [X] macOS
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

just check bbr.c and quicdef.h

### Expected behavior

fixed method:
bbr.c
_IRQL_requires_max_(DISPATCH_LEVEL)
uint32_t
BbrCongestionControlGetSendAllowance(
    _In_ QUIC_CONGESTION_CONTROL* Cc,
    _In_ uint64_t TimeSinceLastSend, // microsec
    _In_ BOOLEAN TimeSinceLastSendValid
    )
{
...
        **Bbr->MinRtt < QUIC_SEND_PACING_INTERVAL**) {	
         //
        // We're not in the necessary state to pace.
        //
        SendAllowance = CongestionWindow - Bbr->BytesInFlight;
...
}

### Actual outcome

SendAllowance with no pacing will easy occur. 

### Additional details

-

**Comment by nibanks** [comment]
Good catch! Thank you! Feel free to make a PR to fix, too. Otherwise, we'll get to this soon hopefully.
