### ISSUE TITLE
Can't Run Tools Built for Linux with Logging Enabled

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#460]
### Describe the bug

If you build with logging enabled (the default experience) and then try to run a tool, you get the following output:
```
root@351ec149a3a1:/src/Debug# bin/Release/quicinteropserver
LTTng-UST: Error (-17) while registering tracepoint probe. Duplicate registration of tracepoint probes having the same name is not allowed.
Aborted
```
It's a recent regression likely caused by the changes to Linux library linking in cmake.

Either stuff is going to have to be refactored or that change reverted.

**Comment by nibanks** [comment]
I believe #445 was what caused this regression, because now libmsquic and the tools get separate copies of the LTTng stuff initialized in platform_linux.c (via the `TRACEPOINT_CREATE_PROBES` define). @thadhouse can you take a look at this?

**Comment by ThadHouse** [comment]
This is caused by having the 2 copies of global state. We could find a way to make it so the tools copy of platform has a separate name, but that's it. We would have no way to share that state without exporting more from the DSO

**Comment by ThadHouse** [comment]
This is what I was worried about in https://github.com/microsoft/msquic/issues/444

**Comment by nibanks** [comment]
> This is what I was worried about in #444

I agree. Windows already had separate state, so I knew there shouldn't be a problem with the generic platform state. But it seems LTTng doesn't like being loaded twice. Somehow we need to only load it once. We have to do one of the following:

- Don't load/use it at all in the tools/tests.
- Export it and share it outside of libmsquic.

**Comment by nibanks** [comment]
I'm trying out a fix. I'll let you know if it works out.
