### ISSUE TITLE
Onboard MsQuic to QUIC Network Simulator

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#462]
### Describe the feature you'd like supported

MsQuic should be onboarded to the [QUIC Interop Runner](https://interop.seemann.io/). More details can be found here: https://github.com/marten-seemann/quic-network-simulator/.

One down side (IMO) is that it only will support Linux, since it's Docker based.

To-do list:

- [x] Share initial Docker image
- [x] On-board server
- [x] On-board client
- [x] Create official Docker image
- [x] On-board logging
- [ ] Investigate Windows based Docker image

**Comment by larseggert** [comment]
#461 was merged...

**Comment by nibanks** [comment]
The said process above is unfortunately quite involved. I only got necessary privilege approval last night.

**Comment by larseggert** [comment]
If it helps, I can ship containers from my fork via docker hub...

**Comment by nibanks** [comment]
If you want to temporarily do that I don't mind. Then when I complete our internal process, I can update things to point to the new official location.

**Comment by larseggert** [comment]
I would, but for some reason my docker hub build is failing, because it cannot pull openssl: https://hub.docker.com/repository/registry-1.docker.io/larseggert/msquic/builds/d2797265-c36e-4c9f-8388-34cfa17025ec

**Comment by nibanks** [comment]
I tried the same thing (with my own fork) yesterday and got the same result! I cannot repro with a local clone either, Linux or Windows. I had a coworker try locally and he couldn't repro. Also, Azure Pipelines doesn't repro either. Any ideas why it doesn't like it?

**Comment by larseggert** [comment]
I have no idea. It also doesn't happen for me locally.

**Comment by nibanks** [comment]
I was able to use https://labs.play-with-docker.com/ to manually clone, build and push to my docker account. `nibanks/msquic:latest` I will send a PR to add that to the implementations for the QNS.

**Comment by nibanks** [comment]
FYI: https://github.com/marten-seemann/quic-interop-runner/pull/111

**Comment by larseggert** [comment]
@nibanks I think this can be closed.

**Comment by nibanks** [comment]
We've got some logging onboarded now, but it still has issues. See https://github.com/marten-seemann/quic-interop-runner/issues/131.

**Comment by nibanks** [comment]
Going to resolve this issue now that we have _general_ support for client and server. We still have bugs to resolve, but those will be handled separately. Also, we'll look into Windows support later.
