### ISSUE TITLE
msquictest.exe fails to run

### ISSUE THREAD

**Issue by moso1** [microsoft/msquic#466]
I have Windows 10 19041.264 that comes with inbox msquic.sys. 
I use VisualStudio 2019 to build this project but msquictest.exe failed. I see that it generated a self-signed "localhost" MsQuicTestCert but msquictest.exe fails to load it.

What else do I need to run it?

```
msquictest.exe
[==========] Running 1001 tests from 21 test suites.
[----------] Global test environment set-up.
Initializing for User Mode tests
..\..\..\src\test\bin\quic_gtest.cpp(41): error: Value of: LoadSecConfig()
  Actual: false
Expected: true
[----------] Global test environment tear-down
[==========] 1001 tests from 21 test suites ran. (8 ms total)
[  PASSED  ] 1001 tests.
[  FAILED  ] 0 tests, listed below:

 0 FAILED TESTS
```

**Comment by nibanks** [comment]
Are you running on a recent Windows Insider build? Did you run the prepare machine script that sets the TLS registry keys?

**Comment by moso1** [comment]
Thanks, it works after running the script. Perhaps it should be explicitly documented that each test machine need to run the script to enable TLS 1.3.
```
$IsWindows=1
.\prepare-machine.ps1 -Configuration Dev
```
