### ISSUE TITLE
Linux functions in msquic_linux are not considered public

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#468]
### Describe the bug

Unlike Windows, where functions such as  `QuicAddrSetFamily` are defined inline, on linux they are compiled as part of the platform library, and therefore not available in the DSO. However, `msquic_linux.h` is included from `msquic.h`, which means its part of the public API. This means we either need to export all of those functions from the DSO, we need to make them inline, or we need to remove them from the public API.

**Comment by nibanks** [comment]
They should all be inline.

**Comment by ThadHouse** [comment]
That makes the most sense. I'll fix that up.
