### ISSUE TITLE
quicsample fails to load certificate from hash

### ISSUE THREAD

**Issue by tomxmm0** [microsoft/msquic#478]
After generating a self signed certificate with Power-Shell using this command:
```
New-SelfSignedCertificate -DnsName "localhost" -CertStoreLocation "cert:\CurrentUser\My"
```
and then when trying to use the outputted thumbprint with quicsample, quicsample fails with this error:
```
.\quicsample.exe -server -cert_hash:1B3F6F8CB70958E6338F04760BE9A4F101B17E1B
Failed to load certificate from hash!
```
Is there anything I'm doing wrong?

os: windows 10
windows version: 2004
msquic branch: v0.9-draft-27
compiled with msvc x64

**Comment by nibanks** [comment]
@tomxmm0 did you run the prepare-machine powershell script to set the TLS registry keys? Also, I'm not positive, but you might need to use the latest master branch instead.

**Comment by tomxmm0** [comment]
@nibanks Ah, didn't know I had to enable TLS 1.3 in the registry. It works now, thank you.
