### ISSUE TITLE
SAL reporting buffer overrrun in QuicConnSendResumptionTicket

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#503]
Since #492, kernel mode SAL testing has been reporting a buffer overrun in QuicConnSendResumptionTicket writing to TicketBuffer

https://dev.azure.com/ms/msquic/_build/results?buildId=87412&view=results

**Comment by ThadHouse** [comment]
Was this fixed by #507?

**Comment by nibanks** [comment]
Yep. I linked them and will close this now.
