### ISSUE TITLE
errors occurred in configue

### ISSUE THREAD

**Issue by WinterChen** [microsoft/msquic#528]
download the code of master branch, when execute in ubuntu：
./scripts/build.ps1

errors occurred：
[06/19/2020 13:05:51] Generating files...
[06/19/2020 13:05:51] cmake -g 'Linux Makefiles' -DQUIC_TLS=openssl -DQUIC_OUTPUT_DIR=/msquic/artifacts/linux/x64_Debug_openssl -DCMAKE_BUILD_TYPE=Debug ../../..
-- Source Dir: /msquic
-- Host System name: 
CMake Warning at CMakeLists.txt:30 (message):
  CMake version too old to support Policy 0091; CRT static linking won't work

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- System name: Linux
-- System version: 3.10.0-693.5.2.el7.x86_64
-- Platform version: 
CMake Error at CMakeLists.txt:206 (include):
  include could not find load file:

    FindLTTngUST

-- Configuring for LTTng events and disabling logging
-- Disabling session resumption support
-- Disabling 0-RTT support
-- Configuring for OpenSSL
-- Found libatomic: /usr/lib/x86_64-linux-gnu/libatomic.so.1
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring incomplete, errors occurred!
See also "/msquic/build/linux/x64_openssl/CMakeFiles/CMakeOutput.log".
See also "/msquic/build/linux/x64_openssl/CMakeFiles/CMakeError.log".
Write-Error: /msquic/scripts/build.ps1:204
Line |
 204 |      CMake-Execute $Arguments
     |      ~~~~~~~~~~~~~~~~~~~~~~~~
     | [06/19/2020 13:05:52] CMake exited with status code 1

**Comment by nibanks** [comment]
Did you run the prepare-machine.ps1 script? That should install all the dependencies.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by WinterChen** [comment]
I had installed all the dependencies according to the instructions

**Comment by WinterChen** [comment]
I had installed all the dependencies according to the instructions

**Comment by ThadHouse** [comment]
It looks like your running Ubuntu 16.04. I wonder if it's version if cmake is too old, and we need to bump the minimum version of cmake required. Try installing a newer version of cmake and seeing if that solves the issue.

**Comment by ThadHouse** [comment]
Looks like FindLTTngUST doesn't exist until CMake 3.6, and 16.04 includes CMake 3.5. You will either need a newer version of CMake, or you can try disabling LTTng by passing `-DisableLogs` to build.ps1
