### ISSUE TITLE
Stub TLS on linux leaks a stream in AbortiveShutdown tests

### ISSUE THREAD

**Issue by anrossi** [microsoft/msquic#537]
### Describe the bug

The AbortiveShutdown tests on Linux, using Stub TLS, leak a QUIC stream.

### Steps to reproduce the behavior

1. Build with the `-SanitizeAddress` and `-Tls stub` switches
2. Run the AbortiveShutdown tests with `Filter *AbortiveShutdown*`

### Expected vs actual behavior

LeakAnalyzer shouldn't be throwing errors for these test cases.
Also, AZP should detect LeakAnalyzer failures and fail the run instead of marking the run as successful.  Perhaps gtest has an option to fail when LeakAnalyzer throws a warning?

**Comment by ThadHouse** [comment]
Just to double check @anrossi were you seeing a stream leak or were you seeing the following?


```

/home/thad/msquic/src/platform/tls_stub.c:1880:48: runtime error: store to misaligned address 0x61b00003c454 for type 'uint64_t', which requires 8 byte alignment
0x61b00003c454: note: pointer points here
  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
              ^
/home/thad/msquic/src/platform/tls_stub.c:1881:48: runtime error: store to misaligned address 0x61b00003c45c for type 'uint64_t', which requires 8 byte alignment
0x61b00003c45c: note: pointer points here
  e7 b3 53 72 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
              ^
/home/thad/msquic/src/platform/tls_stub.c:1903:9: runtime error: load of misaligned address 0x61b00001ccb4 for type 'uint64_t', which requires 8 byte alignment
0x61b00001ccb4: note: pointer points here
  00 00 00 00 b4 89 d1 c1  e7 b3 53 72 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
              ^

[08/25/2020 08:49:01] 192 test(s) run. 0 test(s) failed.
```

Trying to repro this, I'm not seeing a leak, but I am seeing those messages.
