### ISSUE TITLE
Windows Loopback Perf Results are Bimodal

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#561]
### Describe the bug

The loopback performance results are bimodal; sometimes good and sometimes awful. This is primarily because of NUMA I believe. Sometimes the test crosses NUMA nodes and sometimes it doesn't. I think it's dependent on RSS. Sometimes it helps us and sometimes it hurts.

More investigation is necessary.

### Steps to reproduce the behavior

Run Perf pipeline: https://dev.azure.com/ms/msquic/_build?definitionId=356&_a=summary

### Expected vs actual behavior

Results should be fairly consistent; but instead, generally flip-flop between two values.

**Comment by ThadHouse** [comment]
I wonder if it's differences between the machines they're being ran on, since we have 2. I'll add machines to the reporting this week.

**Comment by nibanks** [comment]
It's definitely related. And reboots of the machines can change the behavior. Each reboot randomizes the RSS key I believe, which can result in a new cross-NUMA node (or not) behavior.

**Comment by nibanks** [comment]
After the latest commit and a machine configuration change, the results seem a lot more consistent; though one machine seems to consistently do ~5% better than the other. I might just take the slower one out of rotation for now to consistent results.

**Comment by AloisKraus** [comment]
I do not think this is NUMA related. The loopback device can be configured in different modes. 
You are aware of this? 
See 
https://github.com/Alois-xx/LoopbackPerf

I have also seen fluctuating performance. According to ETW sometimes the tcp receive stack buffers all incoming packets for up to 15ms and then processes them. I do not know how this timer internally works but that is the source of the fluctuation if the TCP driver buffers incoming packets.
