### ISSUE TITLE
Support Sanitizers

### ISSUE THREAD

**Issue by Maximus-** [microsoft/msquic#606]
### Describe the feature you'd like supported
- [ ] Add support for Thread Sanitizer (TSAN) build configuration on the Linux platform (It currently does not support Windows in any capacity).
- [x] Add support for Windows ASAN 64bit https://devblogs.microsoft.com/cppblog/asan-for-windows-x64-and-debug-build-support/ (only available in VS 2019 Preview 16.7 at the moment)

### Proposed solution
Thread Sanitizer helps identify race conditions while in testing. The required change is adding -fsanitize=thread instead of -fsanitize=address. 

### Additional context
There will certainly be a bit of noise produced here. Last time I ran TSAN against MsQuic, a few things popped up that were "best efforts", so the race wasn't important and couldn't cause any memory corruption or otherwise harmful behavior. Ideally you can tag some of these false positives with `__attribute__((no_sanitize("thread"))` (this is per-function unfortunately...).

Reminder as well, that any errors found with TSAN *will not cause the program to terminate*. It will just output to stderr. 

More info here - https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual

**Comment by nibanks** [comment]
@maximus- any hope for a PR from you for these?

**Comment by Maximus-** [comment]
I'm happy to do it, but it may not happen until next week :) Although the change should be tiny; All it needs is /fsanitize=address passed to `cl`, I believe MSVC should handle the linkage to the ASAN runtime libraries automatically.

**Comment by nibanks** [comment]
@maximus- is TSAN still important? Or should we close this bug now that ASAN is integrated on Windows?

**Comment by Maximus-** [comment]
> @Maximus- is TSAN still important? Or should we close this bug now that ASAN is integrated on Windows?

MsQuic is a high performance, multi-threaded networking stack. I definitely think TSAN is worth investing in. Might need some annotations around the codebase to ignore or silence the false positives, but otherwise it's basically free race condition detection.

**Comment by nibanks** [comment]
@maximus- so what work is left for TSAN support integration?

**Comment by Maximus-** [comment]
To pass `-fsanitize=thread` to the compiler in your Linux configuration. It's not compatible with ASAN, so needs to be a mutually exclusive build option.

**Comment by nibanks** [comment]
I'm going to close this with just ASAN support for now. We can investigate possible tsan support in the future.
