### ISSUE TITLE
Official Windows User Mode Binary Distribution

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#611]
We should start looking into ways to do distribution for msquic. Right now, these are the ideas floating around.

1.  ~~vcpkg. This is becoming a lot more popular, and relatively easy to set up. I've done this before for other projects.~~

2. NuGet. Best to publish to the NuGet.org, that way no repo has to be added. This will only work from Visual Studio, but will make it easy to use in VS.

3. Keep making sure cmake is installable. This will enable the standard cmake workflow, and also allow making a submodule out of cmake. I also want to make external_project in cmake work, it shouldn't be any harder

4. Distribute the headers and shared object in a zip file on the releases page.

It might also be nice to distribute through the normal package managers as well, we could likely hook into the same repos pwsh and dotnet core use if we wanted to go this route.

**Comment by nibanks** [comment]
@thhous-msft what are we tracking with this issue now? Should we close it?

**Comment by nibanks** [comment]
Closing as complete.
