### ISSUE TITLE
QNS: Neqo-msquic fails "handshakeloss" test

### ISSUE THREAD

**Issue by agrover** [microsoft/msquic#642]
[neqo-msquic.zip](https://github.com/microsoft/msquic/files/4973706/neqo-msquic.zip)

### Describe the bug

When running quic-interop-runner locally, neqo client fails handshakeloss test against msquic server.

I've attached the logs. Looking at msquic_neqo/handshakeloss/client/qlog/server-0d8b06b027c63b68.qlog , once the server has the request at time=5819ms, there are a couple dropped packets from the server that appear to be the data or pings, but nothing gets through to the client before it times out at 37 seconds.

Do you mind taking a look? quic-transport section 10.1.2 suggests the client has the option to do more to keep the connection open when expecting data, but it also seems to me the server should probably be sending more PTO packets to get the stream response data to the client, or at least keep the connection active.

**Comment by nibanks** [comment]
Unfortunately we don't have logs quite hooked up for Linux, so I won't be able to tell you what happens on the server. But my first guess would have to do with amplification protection. @agrover is the server receiving any packets from the client after the first flight?

**Comment by nibanks** [comment]
I went through the logs with @agrover on Slack and couldn't make any progress. We will need logs from the server to debug more, and that's blocked on #24. For now I'm going to have to just close this unless we can get a repro on Windows somehow.

**Comment by nibanks** [comment]
Once I get https://github.com/microsoft/msquic/pull/675 working and merged, we should be able to make some progress on this.

**Comment by nibanks** [comment]
FYI, @agrover we now have logs *mostly* working so if you find another instance of this, please let me know. I'll keep this open for a bit longer to track the issue.

**Comment by agrover** [comment]
Suggest following up with @ddragana or @martinthomson.

**Comment by nibanks** [comment]
I've made some changes in this area recently. Please reopen if you see this again.
