### ISSUE TITLE
socket api

### ISSUE THREAD

**Issue by yfaker** [microsoft/msquic#669]
### Describe the feature you'd like supported

How about to provide socket APIs for MsQuic?

**Comment by nibanks** [comment]
@yfaker can you be more specific? We have an API. It's not related to general purpose sockets. There are a lot of differences between the functionality of a QUIC connection compared to say TCP (multiple parallel data streams for instance) that makes a basic socket API not work well for QUIC.

**Comment by yfaker** [comment]
@nibanks like bind/listen/accepte/connect/send etc，and maybe a layer of abstract encapsulation of socket fd is required.

**Comment by nibanks** [comment]
If your explicitly looking for a `socket`API, then no, we aren't planning on making one. Theoretically, you might be able to make your own as a wrapper around msquic.
