### ISSUE TITLE
Occasionally, CLOG fails to run in cmake

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#674]
https://github.com/microsoft/msquic/blob/master/CMakeLists.txt#L164

This line occasionally just seems to fail to run, causing failures later in the script.

**Comment by larseggert** [comment]
See if #683 helps?

**Comment by nibanks** [comment]
I haven't seen this recently and really, this shouldn't be a MsQuic bug, but a CLOG one. If we see this again, we should open a CLOG bug.
