### ISSUE TITLE
Improve Linux Test Runtime with Logs

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#679]
Recently we fully enabled LTTng based logs on Linux (thanks to CLOG). This seems to have caused the runtimes to go from 7-8 minutes all the way up to 23-27 minutes. We need to investigate where the overhead is coming from. Is it starting/stopping/canceling the logging? Is it from runtime log collection?

**Comment by ThadHouse** [comment]
I was curious, and its `lttng destroy` that is taking up all the time. It takes 900 ms to run. For 1200 tests, that totals to about 18 minutes, which makes sense. I'll look and see what can be done to speed that up.
