### ISSUE TITLE
Onboard a Linux Clang build to CI

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#696]
Clang is becoming more and more popular as a compiler on linux, and its a bit more particular then GCC. We should onboard a CI build using clang to ensure the build doesn't break there for external users.

**Comment by Maximus-** [comment]
On that note, may be worthwhile to add clang's scan-build to the CI backlog; Clang's static analyzer is relatively powerful and probably worthwhile to have :)

**Comment by larseggert** [comment]
@Maximus- FYI, #701 added support for running `clang-tidy` as part of the build (which is identical to running `scan-build`).

**Comment by Maximus-** [comment]
Nice timing ;P I also didn't realize that clang-tidy was a superset of scan-build. Nice to know :)
