### ISSUE TITLE
Documentation request: QUIC in IIS

### ISSUE THREAD

**Issue by Jehoel** [microsoft/msquic#735]
(As a preface, I apologise if this is the wrong place to post a question specific to IIS, though it does concern msquic - if this is the wrong place I hope that a blue-badger can route it to the right people internally)

## Describe the feature you'd like supported

I'd like official documentation on the Windows, Windows Server, IIS, or msquic documentation sites describing how the in-box QUIC implementation works with IIS.

I noticed that in Windows 10 2004 that IIS seems to support QUIC natively (yay!), but the Help button in the Bindings dialog opens up the documentation for Windows Server 2012 (wat):

![image](https://user-images.githubusercontent.com/1693078/90593159-1b74ab00-e19c-11ea-8741-47d32a4fdf06.png)

...which means I have no idea what the current level of support for QUIC, HTTP/3 and HTTP/2 is inside IIS - nor how I can configure it if I need to.

I also noticed that ARR hasn't been updated since version 3.0 was released in 2013, and it's unclear to what extent ARR 3.0 supports QUIC and HTTP/2 or not. As IIS is frequently used as a reverse-proxy on Windows, especially with ASP.NET Core applications surely it's important for everyone to understand the current (and future/planned) level of support for QUIC in Microsoft's web-server stack.

I'd also like to know to what extent we can use QUIC without TLS in IIS. As far as I can tell QUIC is only configurable with a HTTPS binding and not HTTP, but due to the lack of documentation I have no way of knowing for sure.

Finally, I'd have thought that adding QUIC support in-box to IIS would be worthy of a big announcement, [but the IIS team blog hasn't been updated since 2018](https://blogs.iis.net/iisteam), nor anything relevant in [the wider IIS blog site](https://blogs.iis.net/). Regarding HTTP/2: there's only [a single article from a team-member's personal blog from 2015](https://blogs.iis.net/davidso/http2).

### What are the benefits/reasons for having this feature?

It makes Microsoft look _less bad_.

### Additional context

None.

**Comment by nibanks** [comment]
I've forwarded this internally to the Windows HTTP team and they will take a look and pass along as necessary. Closing the issue as it's not explicitly for msquic. Thanks!

**Comment by Jehoel** [comment]
I suppose - and to reframe this as an msquic-specific question - can you document what interactions exist between `http.sys` and msquic  (for server-side) - and the same for WinInet and msquic (on the client-side)?

**Comment by nibanks** [comment]
HTTP.sys is a client of the MsQuic API, which supports the latest IETF QUIC versions. Beyond that, I cannot say how/when HTTP exposes those interfaces to its clients.

**Comment by alystair** [comment]
Still no update I'm guessing? Would love to experiment with HTTP/3 / QUIC protocol using IIS @nibanks - maybe they could open source IIS as well ;)

**Comment by nibanks** [comment]
Have you tried it out on the latest Windows Insider builds or Windows Server 2022 Preview? I believe there should be a binding property to allow HTTP/3 or QUIC (can't remember). You also need to set SNI.

I think there might be some HTTP specific global registry keys you need to set too (`EnableHttp3`, `EnableAltSvc`; DWORD=1).
