### ISSUE TITLE
Support Persistent Settings on Linux / MacOS

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#798]
### Describe the feature you'd like supported

On Windows, we use the registry for persistent, global (and per-app) settings. We don't have any corresponding implementation for Linux (or MacOS). We should have something, but we're just not sure what.

### Possible solutions

1. A global text file (format?) that contains the settings.
2. A text file (format?) in the local directory that contains the settings.

Anyone with an opinion here would be appreciated!

**Comment by Maximus-** [comment]
on macOS there is an API that is similar to the registry (NSUserDefaults). I'm not sure exactly how it works with the new macOS model where each app lives in its own sandbox, so it might be possible that MsQuic couldn't share settings between apps on the same machine, but at least it would persistent per app. 

On linux the usual place is ~/.local/ or /etc/, i guess, depending on the type of service...

Also definitely voting for something simple like .ini ;P no library dependencies, no broken json / yaml parsers, etc

**Comment by nibanks** [comment]
Going to close this as it's been opened for nearly 2 years, with no progress nor actual ask for this. We can reopen if anyone every has a scenario where it's necessary.
