### ISSUE TITLE
Kernel Mode Performance is dropping, and well down compared to User Mode

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#821]
We should look into this and figure out if this is a test issue, or an implementation issue. Performance should at least be relatively close.

![KernelPerf](https://user-images.githubusercontent.com/7727148/92630883-62c6f680-f285-11ea-9369-35b7e9657c7c.PNG)

**Comment by nibanks** [comment]
It's not really dropping, it's just kind of all over the place:

![image](https://user-images.githubusercontent.com/20663557/92654175-50a88080-f2a4-11ea-9b57-eb67791e329f.png)

We really just need to enable kernel to kernel tests.

**Comment by ThadHouse** [comment]
I'll do some testing to see if kernel to kernel mode will even get us close. I'm not convinced it will though.

**Comment by ThadHouse** [comment]
#828 solved the primary issue causing this. There are a few more low hanging issues, but the general issue is fixed.
