### ISSUE TITLE
prepare-machine.ps1 failed: cannot determine the frame size or a corrupted frame was receiveed

### ISSUE THREAD

**Issue by seppy87** [microsoft/msquic#871]
### Describe the bug

I tried to compile a newer version of msquic and received at prepare-machine line 76 Invoke-Webrequest -Uri ... Cannot determine the frame size or a corrupted frame was received.

seems like it fails to download nasm

**Comment by ThadHouse** [comment]
Can you post the exact error? I just checked to see if the file was still there, and it is. Does it happen continuously, or just once?

**Comment by nibanks** [comment]
Please reopen the issue if you can reproduce it and share the exact error. Thanks.
