### ISSUE TITLE
QUIC datagram

### ISSUE THREAD

**Issue by JonasVautherin** [microsoft/msquic#877]
Does msquic plan to support the QUIC datagram extension for unreliable streams (https://datatracker.ietf.org/doc/html/draft-pauly-quic-datagram-05)?

**Comment by nibanks** [comment]
It is already supported. https://github.com/microsoft/msquic/pull/874 actually adds the text to readme.md claiming said support. See the `DatagramSend` API in msquic.h.

**Comment by JonasVautherin** [comment]
Amazing, thanks a lot!
