### ISSUE TITLE
User Mode Download Performance is Significantly Lower than Upload

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#917]
### Describe the bug

For some reason, download perf is a lot worse than upload for user mode. We need to investigate why.

![image](https://user-images.githubusercontent.com/20663557/96155381-bc45c500-0ec4-11eb-893d-159ee0131f96.png)

**Comment by nibanks** [comment]
Made some progress on this. The problem is related to RSS and NUMA node affinity:

![image](https://user-images.githubusercontent.com/20663557/96157439-28c1c380-0ec7-11eb-9f19-1053ad022add.png)

The user mode code creates the socket on one NUMA node and RSS ends up putting the receive path on another.

**Comment by ThadHouse** [comment]
Not fully solved yet, will close once we see the results.

**Comment by ThadHouse** [comment]
This is caused by an RSS issue in Windows, and a fix will not be available in this release cycle. Removing from 1.0 milestone.
