### ISSUE TITLE
Openssl server occasionally fails handshake with error 253

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#918]
Error 253 is binder does not verify. The only place this can be thrown is https://github.com/akamai/openssl/blob/2d57a30728744b9541fe2a09eb53851c7e9bcc44/ssl/statem/extensions.c#L1646

It seems to be random when it occurs, but fairly easy to reproduce in RPS tests. Its much easier to reproduce if you turn up the number of connections per second.

**Comment by nibanks** [comment]
No longer repro'ing with the latest.
