### ISSUE TITLE
Add runtime platform support detection

### ISSUE THREAD

**Issue by scalablecory** [microsoft/msquic#92]
It would be useful to have consistent error code(s) for `MsQuicOpen` to return when the current platform doesn't have a minimum Windows/OpenSSL version, registry for TLS 1.3 isn't enabled, etc.

This would enable users to prompt the end-user, log, etc. with an obvious message indicating what they might do to get support.

**Comment by nibanks** [comment]
@scalablecory to be clear, we don't have a way to query "Is supported" from our TLS layers. For OpenSSL, it's currently statically linked, so it's always supported. For Schannel, the only way to know is to try it and see if it fails. With that in mind, what exactly is the ask here?

**Comment by nibanks** [comment]
Going to close this with no action, since there isn't really anything we can do here. @scalablecory if you have a specific ask here feel free to reopen with more info.
