### ISSUE TITLE
about sample 

### ISSUE THREAD

**Issue by fflyingfree** [microsoft/msquic#930]
In the src/tools/sample, How to specify the number of threads? Thanks

**Comment by nibanks** [comment]
@fflyingfree can you clarify your question? Number of threads for what? MsQuic to use internally?

**Comment by fflyingfree** [comment]
> 
> 
> @fflyingfree can you clarify your question? Number of threads for what? MsQuic to use internally?

The sample runs with mutil threads. The number of threads may be equal to the number of CPU cores. I want to know how to run it in single thread? Thanks

**Comment by nibanks** [comment]
Can I ask why you want to limit the threads?

**Comment by fflyingfree** [comment]
> 
> @nibanks 
> Can I ask why you want to limit the threads?
I want to integrate msquic in one single process and single thread project. Only want to make msquic has one thread not mutil thread.

**Comment by nibanks** [comment]
@fflyingfree currently, MsQuic is not designed to be single threaded. You can could force MsQuic to limit the number of threads is creates for each partition by manually changing `QUIC_MAX_PARTITION_COUNT` and rebuilding, but you still will not result in only a single thread being created. At least one at the QUIC protocol layer and one at the UDP layer will be created I believe.

**Comment by fflyingfree** [comment]
> 
> @nibanks 
> @fflyingfree currently, MsQuic is not designed to be single threaded. You can could force MsQuic to limit the number of threads is creates for each partition by manually changing `QUIC_MAX_PARTITION_COUNT` and rebuilding, but you still will not result in only a single thread being created. At least one at the QUIC protocol layer and one at the UDP layer will be created I believe.

Okay. Got it. Could you tell me what is the concept of PARTITION in msquic? Thanks

**Comment by nibanks** [comment]
A partition is a concept used in MsQuic to separate and parallelize work. Generally, we map a partition to an [RSS](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-receive-side-scaling) core. That is why we create one per processor by default.

**Comment by fflyingfree** [comment]
> [RSS](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-receive-side-scaling) core



> 
> 
> A partition is a concept used in MsQuic to separate and parallelize work. Generally, we map a partition to an [RSS](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-receive-side-scaling) core. That is why we create one per processor by default.

**Comment by fflyingfree** [comment]
> 
> 
> A partition is a concept used in MsQuic to separate and parallelize work. Generally, we map a partition to an [RSS](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-receive-side-scaling) core. That is why we create one per processor by default.

Thank you!

**Comment by nibanks** [comment]
You're welcome!
