### ISSUE TITLE
Diagnosability improvements to identify operating (normal vs defensive) mode

### ISSUE THREAD

**Issue by genghiskMSFT** [microsoft/msquic#935]
### Describe the feature you'd like supported
Diagnosability mechanisms to help identify when in defensive mode.

msquic has protection against DoS attacks, in particular [QuicBindingShouldRetryConnection](https://github.com/microsoft/msquic/blob/main/src/core/binding.c#L1201) which has a memory-based threshold to determine whether it is inundated with requests, and therefore should drop the packet/not respond to a request.

### Proposed solution

The benefits of this feature are to be able to diagnose slow-to-respond or completely unresponsive connections as due to the implementation being in defensive mode. This is useful when investigating support cases from customers.

### Additional context

The indicator of operating mode (normal, defensive, any future operating modes) should be easily observable without needing to understand the details of the implementation or even the QUIC protocol. It should be as easy as dumping a global variable or a connection-related descriptor. In debugging environments like WinDbg, a kernel extension would be nice. For other scenarios, logged events may be of better use - e.g. when a new connection comes in but the implementation chooses to drop the packet, log an event using OS-provided mechanisms (e.g. ETW) such that the event can be configured/filtered.

**Comment by nibanks** [comment]
I think it would definitely be useful to add both:

- Add ETW event to indicate the current "Retry" state (on or off) that's also fired during the ETW rundown.
- Update the debugger extension to expose this state in the `!quiclib` command.
