### ISSUE TITLE
Server shut down

### ISSUE THREAD

**Issue by wood4099** [microsoft/msquic#954]
The server listens for a Connection. After the new connection comes, it sends a buffer, but, and it will shut down. The server is the call streamenopen and streamstart. Client Connection the server.

**Comment by nibanks** [comment]
I'm going to need a lot more information here. Could you share your code out? What platform are you on? What TLS are you using? Have you tried the sample to make sure that works for you?

**Comment by nibanks** [comment]
First thing that comes to mind though, is that you're not configuring the receiving side to accept any streams. By default, a connection won't accept streams. You have to explicitly state how many unidirectional or bidirectional streams a connection's peer is allowed to open.

**Comment by nibanks** [comment]
Closing based on inactivity. Feel free to reopen if you have additional information.
