### ISSUE TITLE
Add pool tag debugging support to user mode

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#969]
#967 added complete pool tag allocations to user and kernel mode. However in user mode, these pool tags are just ignored. In debug user mode, we should add these tags to each allocation in user mode, to both make debugging easier, and to throw if an item is freed with the wrong pool tag.

**Comment by ThadHouse** [comment]
Windows was closed by #974 

Do we want to do this for unix?

**Comment by nibanks** [comment]
No. I think we're fine with just Windows.
