### ISSUE TITLE
Support Branches for Perf Database

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#991]
Currently, all perf results only contain their commit, but not which branch they come from. We need to add which branch they were uploaded with, and also make sure that when we run either a PR or merge into a branch,  we're grabbing results from that specific branch.

**Comment by nibanks** [comment]
The latest performance stuff (use `performance` branch instead of DB) has fixed this. @ThadHouse please reopen if you disagree.

**Comment by ThadHouse** [comment]
It hasn't been merged into the branches yet, but the support is there.
